// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package xai

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Grok420NonReasoning string = "grok-4.20-0309-non-reasoning"
	Grok420Reasoning    string = "grok-4.20-0309-reasoning"
	Grok420MultiAgent   string = "grok-4.20-multi-agent-0309"
	Grok43              string = "grok-4.3"
	Grok45              string = "grok-4.5"
	Grok46              string = "grok-4.6"
	GrokBuild01         string = "grok-build-0.1"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Grok420NonReasoning: {
		ID:                    Grok420NonReasoning,
		Name:                  "Grok 4.20 Non-Reasoning",
		Provider:              "xai",
		APIModel:              "grok-4.20-0309-non-reasoning",
		Currency:              "USD",
		CostPer1MIn:           1.25,
		CostPer1MOut:          2.5,
		CostPer1MInCached:     0.2,
		ContextWindow:         1000000,
		DefaultMaxTokens:      30000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok420Reasoning: {
		ID:                    Grok420Reasoning,
		Name:                  "Grok 4.20 Reasoning",
		Provider:              "xai",
		APIModel:              "grok-4.20-0309-reasoning",
		Currency:              "USD",
		CostPer1MIn:           1.25,
		CostPer1MOut:          2.5,
		CostPer1MInCached:     0.2,
		ContextWindow:         1000000,
		DefaultMaxTokens:      30000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok420MultiAgent: {
		ID:                    Grok420MultiAgent,
		Name:                  "Grok 4.20 Multi-Agent",
		Provider:              "xai",
		APIModel:              "grok-4.20-multi-agent-0309",
		Currency:              "USD",
		CostPer1MIn:           1.25,
		CostPer1MOut:          2.5,
		CostPer1MInCached:     0.2,
		ContextWindow:         1000000,
		DefaultMaxTokens:      30000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok43: {
		ID:                    Grok43,
		Name:                  "Grok 4.3",
		Provider:              "xai",
		APIModel:              "grok-4.3",
		Currency:              "USD",
		CostPer1MIn:           1.25,
		CostPer1MOut:          2.5,
		CostPer1MInCached:     0.2,
		ContextWindow:         1000000,
		DefaultMaxTokens:      30000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok45: {
		ID:                    Grok45,
		Name:                  "Grok 4.5",
		Provider:              "xai",
		APIModel:              "grok-4.5",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.3,
		ContextWindow:         500000,
		DefaultMaxTokens:      500000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok46: {
		ID:                    Grok46,
		Name:                  "Grok 4.6",
		Provider:              "xai",
		APIModel:              "grok-4.6",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.5,
		ContextWindow:         500000,
		DefaultMaxTokens:      500000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GrokBuild01: {
		ID:                    GrokBuild01,
		Name:                  "Grok Build 0.1",
		Provider:              "xai",
		APIModel:              "grok-build-0.1",
		Currency:              "USD",
		CostPer1MIn:           1,
		CostPer1MOut:          2,
		CostPer1MInCached:     0.2,
		ContextWindow:         256000,
		DefaultMaxTokens:      256000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
