// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://openrouter.ai/api/v1/models?output_modalities=speech
// Generated: 2026-08-12
//
// CostPer1MChars is USD per 1M input characters. Audio formats, default
// format and latency are not part of the models response and are carried
// over from the previous catalog.

package openrouter

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	Orpheus3B            string = "openrouter.orpheus-3b-0.1-ft"
	Aura2                string = "openrouter.aura-2"
	FishAudioS1          string = "openrouter.s1"
	FishAudioS2Pro       string = "openrouter.s2-pro"
	FishAudioS21Pro      string = "openrouter.s2.1-pro"
	S21ProFreeFree       string = "openrouter.s2.1-pro-free-free"
	Gemini31FlashTTS     string = "openrouter.gemini-3.1-flash-tts-preview"
	Kokoro82M            string = "openrouter.kokoro-82m"
	MAIVoice2            string = "openrouter.mai-voice-2"
	MAIVoice2Flash       string = "openrouter.mai-voice-2-flash"
	MiniMaxSpeech28HD    string = "openrouter.speech-2.8-hd"
	MiniMaxSpeech28Turbo string = "openrouter.speech-2.8-turbo"
	VoxtralMiniTTS       string = "openrouter.voxtral-mini-tts-2603"
	QwenAudio3TTSFlash   string = "openrouter.qwen-audio-3.0-tts-flash"
	QwenAudio3TTSPlus    string = "openrouter.qwen-audio-3.0-tts-plus"
	CSM1B                string = "openrouter.csm-1b"
	GrokVoiceTTS1        string = "openrouter.grok-voice-tts-1.0"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	Orpheus3B: {
		ID:               Orpheus3B,
		Name:             "OpenRouter – Orpheus 3B",
		Provider:         "openrouter",
		APIModel:         "canopylabs/orpheus-3b-0.1-ft",
		Currency:         "USD",
		CostPer1MChars:   7,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	Aura2: {
		ID:               Aura2,
		Name:             "OpenRouter – Aura-2",
		Provider:         "openrouter",
		APIModel:         "deepgram/aura-2",
		Currency:         "USD",
		CostPer1MChars:   30,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FishAudioS1: {
		ID:               FishAudioS1,
		Name:             "OpenRouter – S1",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s1",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FishAudioS2Pro: {
		ID:               FishAudioS2Pro,
		Name:             "OpenRouter – S2 Pro",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s2-pro",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FishAudioS21Pro: {
		ID:               FishAudioS21Pro,
		Name:             "OpenRouter – S2.1 Pro",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s2.1-pro",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	S21ProFreeFree: {
		ID:       S21ProFreeFree,
		Name:     "OpenRouter – S2.1 Pro Free (free)",
		Provider: "openrouter",
		APIModel: "fish-audio/s2.1-pro-free:free",
		Currency: "USD",
	},
	Gemini31FlashTTS: {
		ID:               Gemini31FlashTTS,
		Name:             "OpenRouter – Gemini 3.1 Flash TTS Preview",
		Provider:         "openrouter",
		APIModel:         "google/gemini-3.1-flash-tts-preview",
		Currency:         "USD",
		CostPer1MChars:   1,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	Kokoro82M: {
		ID:               Kokoro82M,
		Name:             "OpenRouter – Kokoro 82M",
		Provider:         "openrouter",
		APIModel:         "hexgrad/kokoro-82m",
		Currency:         "USD",
		CostPer1MChars:   0.62,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MAIVoice2: {
		ID:               MAIVoice2,
		Name:             "OpenRouter – MAI-Voice-2",
		Provider:         "openrouter",
		APIModel:         "microsoft/mai-voice-2",
		Currency:         "USD",
		CostPer1MChars:   22,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MAIVoice2Flash: {
		ID:               MAIVoice2Flash,
		Name:             "OpenRouter – MAI-Voice-2-Flash",
		Provider:         "openrouter",
		APIModel:         "microsoft/mai-voice-2-flash",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MiniMaxSpeech28HD: {
		ID:               MiniMaxSpeech28HD,
		Name:             "OpenRouter – Speech 2.8 HD",
		Provider:         "openrouter",
		APIModel:         "minimax/speech-2.8-hd",
		Currency:         "USD",
		CostPer1MChars:   100,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MiniMaxSpeech28Turbo: {
		ID:               MiniMaxSpeech28Turbo,
		Name:             "OpenRouter – Speech 2.8 Turbo",
		Provider:         "openrouter",
		APIModel:         "minimax/speech-2.8-turbo",
		Currency:         "USD",
		CostPer1MChars:   60,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	VoxtralMiniTTS: {
		ID:               VoxtralMiniTTS,
		Name:             "OpenRouter – Voxtral Mini TTS",
		Provider:         "openrouter",
		APIModel:         "mistralai/voxtral-mini-tts-2603",
		Currency:         "USD",
		CostPer1MChars:   16,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	QwenAudio3TTSFlash: {
		ID:               QwenAudio3TTSFlash,
		Name:             "OpenRouter – Qwen-Audio-3.0-TTS Flash",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-audio-3.0-tts-flash",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	QwenAudio3TTSPlus: {
		ID:               QwenAudio3TTSPlus,
		Name:             "OpenRouter – Qwen-Audio-3.0-TTS Plus",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-audio-3.0-tts-plus",
		Currency:         "USD",
		CostPer1MChars:   20,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	CSM1B: {
		ID:               CSM1B,
		Name:             "OpenRouter – CSM 1B",
		Provider:         "openrouter",
		APIModel:         "sesame/csm-1b",
		Currency:         "USD",
		CostPer1MChars:   7,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	GrokVoiceTTS1: {
		ID:               GrokVoiceTTS1,
		Name:             "OpenRouter – Grok Voice TTS 1.0",
		Provider:         "openrouter",
		APIModel:         "x-ai/grok-voice-tts-1.0",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
}
