package model

// Anthropic provider identifier and Claude model IDs for this registry.
const (
	ProviderAnthropic Provider = "anthropic"

	Claude3Haiku   ID = "claude-3-haiku"
	Claude4Opus    ID = "claude-4-opus"
	Claude41Opus   ID = "claude-4.1-opus"
	Claude4Sonnet  ID = "claude-4-sonnet"
	Claude45Sonnet ID = "claude-4.5-sonnet"
	Claude45Opus   ID = "claude-4.5-opus"
	Claude45Haiku  ID = "claude-4.5-haiku"
	Claude46Opus   ID = "claude-4.6-opus"
	Claude46Sonnet ID = "claude-4.6-sonnet"
	Claude47Opus   ID = "claude-4.7-opus"
	Claude48Opus   ID = "claude-4.8-opus"
	Claude5Sonnet  ID = "claude-5-sonnet"
	Claude5Fable   ID = "claude-5-fable"
)

// AnthropicModels maps Anthropic model IDs to their configurations.
var AnthropicModels = map[ID]Model{
	Claude3Haiku: {
		ID:                    Claude3Haiku,
		Name:                  "Claude 3 Haiku",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-3-haiku-20240307",
		CostPer1MIn:           0.25,
		CostPer1MInCached:     0.30,
		CostPer1MOutCached:    0.03,
		CostPer1MOut:          1.25,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude4Sonnet: {
		ID:                    Claude4Sonnet,
		Name:                  "Claude 4 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-4-20250514",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude4Opus: {
		ID:                    Claude4Opus,
		Name:                  "Claude 4 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-20250514",
		CostPer1MIn:           15.0,
		CostPer1MInCached:     18.75,
		CostPer1MOutCached:    1.50,
		CostPer1MOut:          75.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude41Opus: {
		ID:                    Claude41Opus,
		Name:                  "Claude 4.1 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-1",
		CostPer1MIn:           15.0,
		CostPer1MInCached:     18.75,
		CostPer1MOutCached:    1.50,
		CostPer1MOut:          75.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude45Sonnet: {
		ID:                    Claude45Sonnet,
		Name:                  "Claude 4.5 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-4-5-20250929",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Opus: {
		ID:                    Claude45Opus,
		Name:                  "Claude 4.5 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-5-20251101",
		CostPer1MIn:           5.0,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.50,
		CostPer1MOut:          25.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Haiku: {
		ID:                    Claude45Haiku,
		Name:                  "Claude 4.5 Haiku",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-haiku-4-5-20251001",
		CostPer1MIn:           1.0,
		CostPer1MInCached:     1.25,
		CostPer1MOutCached:    0.10,
		CostPer1MOut:          5.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Opus: {
		ID:                    Claude46Opus,
		Name:                  "Claude 4.6 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-6-20260205",
		CostPer1MIn:           5.0,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.50,
		CostPer1MOut:          25.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Sonnet: {
		ID:                    Claude46Sonnet,
		Name:                  "Claude 4.6 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-4-6",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude47Opus: {
		ID:                    Claude47Opus,
		Name:                  "Claude 4.7 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-7",
		CostPer1MIn:           5.0,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.50,
		CostPer1MOut:          25.0,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude48Opus: {
		ID:                    Claude48Opus,
		Name:                  "Claude 4.8 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-8",
		CostPer1MIn:           5.0,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.50,
		CostPer1MOut:          25.0,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Sonnet: {
		ID:                    Claude5Sonnet,
		Name:                  "Claude Sonnet 5",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-5",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Fable: {
		ID:                    Claude5Fable,
		Name:                  "Claude Fable 5",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-fable-5",
		CostPer1MIn:           10.0,
		CostPer1MInCached:     12.5,
		CostPer1MOutCached:    1.0,
		CostPer1MOut:          50.0,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
