package model

const (
	ProviderAnthropic ModelProvider = "anthropic"

	Claude35Sonnet ModelID = "claude-3.5-sonnet"
	Claude3Haiku   ModelID = "claude-3-haiku"
	Claude35Haiku  ModelID = "claude-3.5-haiku"
	Claude3Opus    ModelID = "claude-3-opus"
	Claude4Opus    ModelID = "claude-4-opus"
	Claude41Opus   ModelID = "claude-4.1-opus"
	Claude4Sonnet  ModelID = "claude-4-sonnet"
	Claude45Sonnet ModelID = "claude-4.5-sonnet"
	Claude45Opus   ModelID = "claude-4.5-opus"
	Claude45Haiku  ModelID = "claude-4.5-haiku"
)

var AnthropicModels = map[ModelID]Model{
	Claude35Sonnet: {
		ID:                    Claude35Sonnet,
		Name:                  "Claude 3.5 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-3-5-sonnet-latest",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      5000,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude3Haiku: {
		ID:                    Claude3Haiku,
		Name:                  "Claude 3 Haiku",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-3-haiku-20240307",
		CostPer1MIn:           0.25,
		CostPer1MInCached:     0.30,
		CostPer1MOutCached:    0.03,
		CostPer1MOut:          1.25,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude35Haiku: {
		ID:                    Claude35Haiku,
		Name:                  "Claude 3.5 Haiku",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-3-5-haiku-latest",
		CostPer1MIn:           0.80,
		CostPer1MInCached:     1.0,
		CostPer1MOutCached:    0.08,
		CostPer1MOut:          4.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude3Opus: {
		ID:                    Claude3Opus,
		Name:                  "Claude 3 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-3-opus-latest",
		CostPer1MIn:           15.0,
		CostPer1MInCached:     18.75,
		CostPer1MOutCached:    1.50,
		CostPer1MOut:          75.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude4Sonnet: {
		ID:                    Claude4Sonnet,
		Name:                  "Claude 4 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-4-20250514",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude4Opus: {
		ID:                    Claude4Opus,
		Name:                  "Claude 4 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-20250514",
		CostPer1MIn:           15.0,
		CostPer1MInCached:     18.75,
		CostPer1MOutCached:    1.50,
		CostPer1MOut:          75.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude41Opus: {
		ID:                    Claude41Opus,
		Name:                  "Claude 4.1 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-1-latest",
		CostPer1MIn:           15.0,
		CostPer1MInCached:     18.75,
		CostPer1MOutCached:    1.50,
		CostPer1MOut:          75.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude45Sonnet: {
		ID:                    Claude45Sonnet,
		Name:                  "Claude 4.5 Sonnet",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-sonnet-4-5-20250929",
		CostPer1MIn:           3.0,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.30,
		CostPer1MOut:          15.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude45Opus: {
		ID:                    Claude45Opus,
		Name:                  "Claude 4.5 Opus",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-opus-4-5-20251101",
		CostPer1MIn:           5.0,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.50,
		CostPer1MOut:          25.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
	Claude45Haiku: {
		ID:                    Claude45Haiku,
		Name:                  "Claude 4.5 Haiku",
		Provider:              ProviderAnthropic,
		APIModel:              "claude-haiku-4-5-20251001",
		CostPer1MIn:           1.0,
		CostPer1MInCached:     1.25,
		CostPer1MOutCached:    0.10,
		CostPer1MOut:          5.0,
		ContextWindow:         200000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: false,
	},
}
