package model

// ProviderAzure is the Azure OpenAI provider identifier.
const ProviderAzure Provider = "azure"

// Azure OpenAI chat model IDs for this registry.
const (
	AzureGPT41     ID = "azure.gpt-4.1"
	AzureGPT41Mini ID = "azure.gpt-4.1-mini"
	AzureGPT41Nano ID = "azure.gpt-4.1-nano"
	AzureGPT4o     ID = "azure.gpt-4o"
	AzureGPT4oMini ID = "azure.gpt-4o-mini"
	AzureO1        ID = "azure.o1"
	AzureO1Mini    ID = "azure.o1-mini"
	AzureO3        ID = "azure.o3"
	AzureO3Mini    ID = "azure.o3-mini"
	AzureO3Pro     ID = "azure.o3-pro"
	AzureO4Mini    ID = "azure.o4-mini"

	AzureGPT5           ID = "azure.gpt-5"
	AzureGPT5Mini       ID = "azure.gpt-5-mini"
	AzureGPT5Nano       ID = "azure.gpt-5-nano"
	AzureGPT5Codex      ID = "azure.gpt-5-codex"
	AzureGPT5Pro        ID = "azure.gpt-5-pro"
	AzureGPT51          ID = "azure.gpt-5.1"
	AzureGPT51Codex     ID = "azure.gpt-5.1-codex"
	AzureGPT51CodexMini ID = "azure.gpt-5.1-codex-mini"
	AzureGPT51CodexMax  ID = "azure.gpt-5.1-codex-max"
	AzureGPT52          ID = "azure.gpt-5.2"
	AzureGPT52Codex     ID = "azure.gpt-5.2-codex"
	AzureGPT53Codex     ID = "azure.gpt-5.3-codex"
	AzureGPT54          ID = "azure.gpt-5.4"
	AzureGPT54Mini      ID = "azure.gpt-5.4-mini"
	AzureGPT54Nano      ID = "azure.gpt-5.4-nano"
	AzureGPT54Pro       ID = "azure.gpt-5.4-pro"
	AzureGPT55          ID = "azure.gpt-5.5"
)

// AzureModels maps Azure OpenAI model IDs to their configurations.
var AzureModels = map[ID]Model{
	AzureGPT41: {
		ID:                    AzureGPT41,
		Name:                  "Azure OpenAI – GPT 4.1",
		Provider:              ProviderAzure,
		APIModel:              "gpt-4.1",
		CostPer1MIn:           OpenAIModels[GPT41].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41].DefaultMaxTokens,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT41Mini: {
		ID:                    AzureGPT41Mini,
		Name:                  "Azure OpenAI – GPT 4.1 mini",
		Provider:              ProviderAzure,
		APIModel:              "gpt-4.1-mini",
		CostPer1MIn:           OpenAIModels[GPT41Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41Mini].DefaultMaxTokens,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT41Nano: {
		ID:                    AzureGPT41Nano,
		Name:                  "Azure OpenAI – GPT 4.1 nano",
		Provider:              ProviderAzure,
		APIModel:              "gpt-4.1-nano",
		CostPer1MIn:           OpenAIModels[GPT41Nano].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41Nano].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41Nano].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41Nano].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41Nano].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41Nano].DefaultMaxTokens,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT4o: {
		ID:                    AzureGPT4o,
		Name:                  "Azure OpenAI – GPT-4o",
		Provider:              ProviderAzure,
		APIModel:              "gpt-4o",
		CostPer1MIn:           OpenAIModels[GPT4o].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT4o].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT4o].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT4o].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT4o].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT4o].DefaultMaxTokens,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT4oMini: {
		ID:                    AzureGPT4oMini,
		Name:                  "Azure OpenAI – GPT-4o mini",
		Provider:              ProviderAzure,
		APIModel:              "gpt-4o-mini",
		CostPer1MIn:           OpenAIModels[GPT4oMini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT4oMini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT4oMini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT4oMini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT4oMini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT4oMini].DefaultMaxTokens,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureO1: {
		ID:                    AzureO1,
		Name:                  "Azure OpenAI – O1",
		Provider:              ProviderAzure,
		APIModel:              "o1",
		CostPer1MIn:           OpenAIModels[O1].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O1].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O1].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O1].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O1].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O1].DefaultMaxTokens,
		CanReason:             OpenAIModels[O1].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureO1Mini: {
		ID:                    AzureO1Mini,
		Name:                  "Azure OpenAI – O1 mini",
		Provider:              ProviderAzure,
		APIModel:              "o1-mini",
		CostPer1MIn:           OpenAIModels[O1Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O1Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O1Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O1Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O1Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O1Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[O1Mini].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureO3: {
		ID:                    AzureO3,
		Name:                  "Azure OpenAI – O3",
		Provider:              ProviderAzure,
		APIModel:              "o3",
		CostPer1MIn:           OpenAIModels[O3].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureO3Mini: {
		ID:                    AzureO3Mini,
		Name:                  "Azure OpenAI – O3 mini",
		Provider:              ProviderAzure,
		APIModel:              "o3-mini",
		CostPer1MIn:           OpenAIModels[O3Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3Mini].CanReason,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	AzureO4Mini: {
		ID:                    AzureO4Mini,
		Name:                  "Azure OpenAI – O4 mini",
		Provider:              ProviderAzure,
		APIModel:              "o4-mini",
		CostPer1MIn:           OpenAIModels[O4Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O4Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O4Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O4Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O4Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O4Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[O4Mini].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureO3Pro: {
		ID:                    AzureO3Pro,
		Name:                  "Azure OpenAI – O3 pro",
		Provider:              ProviderAzure,
		APIModel:              "o3-pro",
		CostPer1MIn:           OpenAIModels[O3Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3Pro].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT5: {
		ID:                    AzureGPT5,
		Name:                  "Azure OpenAI – GPT-5",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5",
		CostPer1MIn:           OpenAIModels[GPT5].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT5].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT5].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT5].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT5].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT5].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT5].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT5Mini: {
		ID:                    AzureGPT5Mini,
		Name:                  "Azure OpenAI – GPT-5 mini",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5-mini",
		CostPer1MIn:           OpenAIModels[GPT5Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT5Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT5Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT5Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT5Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT5Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT5Mini].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT5Nano: {
		ID:                    AzureGPT5Nano,
		Name:                  "Azure OpenAI – GPT-5 nano",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5-nano",
		CostPer1MIn:           OpenAIModels[GPT5Nano].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT5Nano].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT5Nano].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT5Nano].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT5Nano].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT5Nano].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT5Nano].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT5Codex: {
		ID:                    AzureGPT5Codex,
		Name:                  "Azure OpenAI – GPT-5 codex",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5-codex",
		CostPer1MIn:           OpenAIModels[GPT5Codex].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT5Codex].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT5Codex].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT5Codex].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT5Codex].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT5Codex].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT5Codex].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT5Pro: {
		ID:                    AzureGPT5Pro,
		Name:                  "Azure OpenAI – GPT-5 pro",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5-pro",
		CostPer1MIn:           OpenAIModels[GPT5Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT5Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT5Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT5Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT5Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT5Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT5Pro].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT51: {
		ID:                    AzureGPT51,
		Name:                  "Azure OpenAI – GPT-5.1",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.1",
		CostPer1MIn:           OpenAIModels[GPT51].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT51].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT51].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT51].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT51].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT51].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT51].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT51Codex: {
		ID:                    AzureGPT51Codex,
		Name:                  "Azure OpenAI – GPT-5.1 codex",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.1-codex",
		CostPer1MIn:           OpenAIModels[GPT51Codex].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT51Codex].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT51Codex].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT51Codex].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT51Codex].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT51Codex].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT51Codex].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT51CodexMini: {
		ID:                    AzureGPT51CodexMini,
		Name:                  "Azure OpenAI – GPT-5.1 codex mini",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.1-codex-mini",
		CostPer1MIn:           OpenAIModels[GPT51CodexMini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT51CodexMini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT51CodexMini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT51CodexMini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT51CodexMini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT51CodexMini].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT51CodexMini].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT51CodexMax: {
		ID:                    AzureGPT51CodexMax,
		Name:                  "Azure OpenAI – GPT-5.1 codex max",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.1-codex-max",
		CostPer1MIn:           OpenAIModels[GPT51CodexMax].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT51CodexMax].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT51CodexMax].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT51CodexMax].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT51CodexMax].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT51CodexMax].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT51CodexMax].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT52: {
		ID:                    AzureGPT52,
		Name:                  "Azure OpenAI – GPT-5.2",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.2",
		CostPer1MIn:           OpenAIModels[GPT52].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT52Codex: {
		ID:                    AzureGPT52Codex,
		Name:                  "Azure OpenAI – GPT-5.2 codex",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.2-codex",
		CostPer1MIn:           OpenAIModels[GPT52Codex].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52Codex].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52Codex].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52Codex].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52Codex].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52Codex].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52Codex].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT53Codex: {
		ID:                    AzureGPT53Codex,
		Name:                  "Azure OpenAI – GPT-5.3 codex",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.3-codex",
		CostPer1MIn:           OpenAIModels[GPT53Codex].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT53Codex].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT53Codex].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT53Codex].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT53Codex].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT53Codex].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT53Codex].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT54: {
		ID:                    AzureGPT54,
		Name:                  "Azure OpenAI – GPT-5.4",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.4",
		CostPer1MIn:           OpenAIModels[GPT54].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT54].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT54].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT54].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT54].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT54].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT54].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT54Mini: {
		ID:                    AzureGPT54Mini,
		Name:                  "Azure OpenAI – GPT-5.4 mini",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.4-mini",
		CostPer1MIn:           OpenAIModels[GPT54Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT54Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT54Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT54Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT54Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT54Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT54Mini].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT54Nano: {
		ID:                    AzureGPT54Nano,
		Name:                  "Azure OpenAI – GPT-5.4 nano",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.4-nano",
		CostPer1MIn:           OpenAIModels[GPT54Nano].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT54Nano].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT54Nano].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT54Nano].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT54Nano].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT54Nano].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT54Nano].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT54Pro: {
		ID:                    AzureGPT54Pro,
		Name:                  "Azure OpenAI – GPT-5.4 pro",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.4-pro",
		CostPer1MIn:           OpenAIModels[GPT54Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT54Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT54Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT54Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT54Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT54Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT54Pro].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	AzureGPT55: {
		ID:                    AzureGPT55,
		Name:                  "Azure OpenAI – GPT-5.5",
		Provider:              ProviderAzure,
		APIModel:              "gpt-5.5",
		CostPer1MIn:           OpenAIModels[GPT55].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT55].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT55].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT55].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT55].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT55].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT55].CanReason,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
