package model

const (
	ProviderMistral ModelProvider = "mistral"

	MistralLarge3    ModelID = "mistral-large-3"
	MistralMedium31  ModelID = "mistral-medium-3.1"
	MistralSmall32   ModelID = "mistral-small-3.2"
	Ministral3_14B   ModelID = "ministral-3-14b"
	Ministral3_8B    ModelID = "ministral-3-8b"
	Ministral3_3B    ModelID = "ministral-3-3b"
	MistralNemo      ModelID = "mistral-nemo"
	Codestral        ModelID = "codestral"
	Devstral2        ModelID = "devstral-2"
	PixtralLarge     ModelID = "pixtral-large"
	DevstralSmall    ModelID = "devstral-small"
	MistralSmall31   ModelID = "mistral-small-3.1"
	MistralMedium3   ModelID = "mistral-medium-3"
	DevstralMedium   ModelID = "devstral-medium"
	MistralLarge2411 ModelID = "mistral-large-2411"
	Mixtral8x7B      ModelID = "mixtral-8x7b"
	Mistral7B        ModelID = "mistral-7b"
)

var MistralModels = map[ModelID]Model{
	MistralLarge3: {
		ID:                    MistralLarge3,
		Name:                  "Mistral Large 3",
		Provider:              ProviderMistral,
		APIModel:              "mistral-large-2512",
		CostPer1MIn:           0.50,
		CostPer1MOut:          1.50,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         262_144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralMedium31: {
		ID:                    MistralMedium31,
		Name:                  "Mistral Medium 3.1",
		Provider:              ProviderMistral,
		APIModel:              "mistral-medium-2508",
		CostPer1MIn:           0.40,
		CostPer1MOut:          2.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralSmall32: {
		ID:                    MistralSmall32,
		Name:                  "Mistral Small 3.2",
		Provider:              ProviderMistral,
		APIModel:              "mistral-small-2506",
		CostPer1MIn:           0.06,
		CostPer1MOut:          0.18,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3_14B: {
		ID:                    Ministral3_14B,
		Name:                  "Ministral 3 14B",
		Provider:              ProviderMistral,
		APIModel:              "ministral-14b-2512",
		CostPer1MIn:           0.20,
		CostPer1MOut:          0.20,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         262_144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3_8B: {
		ID:                    Ministral3_8B,
		Name:                  "Ministral 3 8B",
		Provider:              ProviderMistral,
		APIModel:              "ministral-8b-2512",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.15,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         262_144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3_3B: {
		ID:                    Ministral3_3B,
		Name:                  "Ministral 3 3B",
		Provider:              ProviderMistral,
		APIModel:              "ministral-3b-2512",
		CostPer1MIn:           0.10,
		CostPer1MOut:          0.10,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralNemo: {
		ID:                    MistralNemo,
		Name:                  "Mistral Nemo",
		Provider:              ProviderMistral,
		APIModel:              "open-mistral-nemo",
		CostPer1MIn:           0.02,
		CostPer1MOut:          0.04,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	Codestral: {
		ID:                    Codestral,
		Name:                  "Codestral",
		Provider:              ProviderMistral,
		APIModel:              "codestral-2508",
		CostPer1MIn:           0.30,
		CostPer1MOut:          0.90,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         256_000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	Devstral2: {
		ID:                    Devstral2,
		Name:                  "Devstral 2",
		Provider:              ProviderMistral,
		APIModel:              "devstral-2512",
		CostPer1MIn:           0.05,
		CostPer1MOut:          0.22,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         262_144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	PixtralLarge: {
		ID:                    PixtralLarge,
		Name:                  "Pixtral Large",
		Provider:              ProviderMistral,
		APIModel:              "pixtral-large-2411",
		CostPer1MIn:           2.00,
		CostPer1MOut:          6.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	DevstralSmall: {
		ID:                    DevstralSmall,
		Name:                  "Devstral Small 1.1",
		Provider:              ProviderMistral,
		APIModel:              "devstral-small-2507",
		CostPer1MIn:           0.10,
		CostPer1MOut:          0.30,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	MistralSmall31: {
		ID:                    MistralSmall31,
		Name:                  "Mistral Small 3.1",
		Provider:              ProviderMistral,
		APIModel:              "mistral-small-2503",
		CostPer1MIn:           0.03,
		CostPer1MOut:          0.11,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralMedium3: {
		ID:                    MistralMedium3,
		Name:                  "Mistral Medium 3",
		Provider:              ProviderMistral,
		APIModel:              "mistral-medium-2505",
		CostPer1MIn:           0.40,
		CostPer1MOut:          2.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	DevstralMedium: {
		ID:                    DevstralMedium,
		Name:                  "Devstral Medium",
		Provider:              ProviderMistral,
		APIModel:              "devstral-medium-2507",
		CostPer1MIn:           0.40,
		CostPer1MOut:          2.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	MistralLarge2411: {
		ID:                    MistralLarge2411,
		Name:                  "Mistral Large 2411",
		Provider:              ProviderMistral,
		APIModel:              "mistral-large-2411",
		CostPer1MIn:           2.00,
		CostPer1MOut:          6.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Mixtral8x7B: {
		ID:                    Mixtral8x7B,
		Name:                  "Mixtral 8x7B",
		Provider:              ProviderMistral,
		APIModel:              "mixtral-8x7b-instruct-v0.1",
		CostPer1MIn:           0.50,
		CostPer1MOut:          0.50,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         32_000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   false,
		SupportsStructuredOut: false,
	},
	Mistral7B: {
		ID:                    Mistral7B,
		Name:                  "Mistral 7B Instruct",
		Provider:              ProviderMistral,
		APIModel:              "mistral-7b-instruct-v0.3",
		CostPer1MIn:           0.028,
		CostPer1MOut:          0.054,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		ContextWindow:         32_768,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   false,
		SupportsStructuredOut: false,
	},
}
