package model

// OpenRouter provider identifier and routed model IDs for this registry.
const (
	ProviderOpenRouter Provider = "openrouter"

	OpenRouterGPT41             ID = "openrouter.gpt-4.1"
	OpenRouterGPT41Mini         ID = "openrouter.gpt-4.1-mini"
	OpenRouterGPT41Nano         ID = "openrouter.gpt-4.1-nano"
	OpenRouterGPT4o             ID = "openrouter.gpt-4o"
	OpenRouterGPT4oMini         ID = "openrouter.gpt-4o-mini"
	OpenRouterO1                ID = "openrouter.o1"
	OpenRouterO1Pro             ID = "openrouter.o1-pro"
	OpenRouterO3                ID = "openrouter.o3"
	OpenRouterO3Pro             ID = "openrouter.o3-pro"
	OpenRouterO3Mini            ID = "openrouter.o3-mini"
	OpenRouterO4Mini            ID = "openrouter.o4-mini"
	OpenRouterGPT52             ID = "openrouter.gpt-5.2"
	OpenRouterGPT52Pro          ID = "openrouter.gpt-5.2-pro"
	OpenRouterGPT52Instant      ID = "openrouter.gpt-5.2-instant"
	OpenRouterGemini3Pro        ID = "openrouter.gemini-3-pro"
	OpenRouterGemini31Pro       ID = "openrouter.gemini-3.1-pro"
	OpenRouterGemini25Flash     ID = "openrouter.gemini-2.5-flash"
	OpenRouterGemini25FlashLite ID = "openrouter.gemini-2.5-flash-lite"
	OpenRouterGemini25          ID = "openrouter.gemini-2.5"
	OpenRouterClaude3Haiku      ID = "openrouter.claude-3-haiku"
	OpenRouterClaude45Opus      ID = "openrouter.claude-4.5-opus"
	OpenRouterClaude46Opus      ID = "openrouter.claude-4.6-opus"
	OpenRouterClaude46Sonnet    ID = "openrouter.claude-4.6-sonnet"
	OpenRouterClaude47Opus      ID = "openrouter.claude-4.7-opus"
	OpenRouterClaude48Opus      ID = "openrouter.claude-4.8-opus"
	OpenRouterClaude5Sonnet     ID = "openrouter.claude-5-sonnet"
	OpenRouterGPT52Codex        ID = "openrouter.gpt-5.2-codex"
	OpenRouterMistralLarge3     ID = "openrouter.mistral-large-3"
	OpenRouterMistralMedium3    ID = "openrouter.mistral-medium-3"
	OpenRouterLlama4Maverick    ID = "openrouter.llama-4-maverick"
	OpenRouterLlama4Scout       ID = "openrouter.llama-4-scout"
	OpenRouterLlama3170B        ID = "openrouter.llama-3.1-70b"
	OpenRouterLlama318B         ID = "openrouter.llama-3.1-8b"
	OpenRouterDeepSeekV32       ID = "openrouter.deepseek-v3.2"
	OpenRouterDeepSeekV32Think  ID = "openrouter.deepseek-v3.2-thinking"
	OpenRouterDeepSeekR1        ID = "openrouter.deepseek-r1"
	OpenRouterDeepSeekR1Distill ID = "openrouter.deepseek-r1-distill"
	OpenRouterQwen3Max          ID = "openrouter.qwen-3-max"
	OpenRouterQwen3Coder480B    ID = "openrouter.qwen-3-coder-480b"
	OpenRouterQwen3CoderPlus    ID = "openrouter.qwen-3-coder-plus"
	OpenRouterCommandRPlus      ID = "openrouter.command-r-plus"
	OpenRouterCommandR          ID = "openrouter.command-r"
	OpenRouterSonar             ID = "openrouter.sonar"
	OpenRouterSonarPro          ID = "openrouter.sonar-pro"
	OpenRouterSonarReasoningPro ID = "openrouter.sonar-reasoning-pro"
	OpenRouterSonarDeepResearch ID = "openrouter.sonar-deep-research"
	OpenRouterGPTOss20b         ID = "openrouter.gpt-oss-20b"
	OpenRouterGPTOss120b        ID = "openrouter.gpt-oss-120b"
	OpenRouterGrok45            ID = "openrouter.grok-4.5"
	OpenRouterGrok43            ID = "openrouter.grok-4.3"
	OpenRouterGemini35Flash     ID = "openrouter.gemini-3.5-flash"
	OpenRouterGemini36Flash     ID = "openrouter.gemini-3.6-flash"
	OpenRouterClaude5Opus       ID = "openrouter.claude-5-opus"
	OpenRouterClaude5Fable      ID = "openrouter.claude-5-fable"
	OpenRouterGPT56Sol          ID = "openrouter.gpt-5.6-sol"
	OpenRouterGPT56Terra        ID = "openrouter.gpt-5.6-terra"
	OpenRouterGPT56Luna         ID = "openrouter.gpt-5.6-luna"
)

// OpenRouterModels maps OpenRouter model IDs to their configurations.
//
// Pricing source: https://openrouter.ai/api/v1/models for slugs; rates
// mirror the upstream provider registries in this package.
// Fetched: 2026-07-26.
var OpenRouterModels = map[ID]Model{
	OpenRouterGPT41: {
		ID:                    OpenRouterGPT41,
		Name:                  "OpenRouter – GPT 4.1",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-4.1",
		CostPer1MIn:           OpenAIModels[GPT41].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41].DefaultMaxTokens,
		SupportsStructuredOut: OpenAIModels[GPT41].SupportsStructuredOut,
	},
	OpenRouterGPT41Mini: {
		ID:                    OpenRouterGPT41Mini,
		Name:                  "OpenRouter – GPT 4.1 mini",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-4.1-mini",
		CostPer1MIn:           OpenAIModels[GPT41Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41Mini].DefaultMaxTokens,
		SupportsStructuredOut: OpenAIModels[GPT41Mini].SupportsStructuredOut,
	},
	OpenRouterGPT41Nano: {
		ID:                    OpenRouterGPT41Nano,
		Name:                  "OpenRouter – GPT 4.1 nano",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-4.1-nano",
		CostPer1MIn:           OpenAIModels[GPT41Nano].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT41Nano].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT41Nano].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT41Nano].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT41Nano].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT41Nano].DefaultMaxTokens,
		SupportsStructuredOut: OpenAIModels[GPT41Nano].SupportsStructuredOut,
	},
	OpenRouterGPT4o: {
		ID:                    OpenRouterGPT4o,
		Name:                  "OpenRouter – GPT 4o",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-4o",
		CostPer1MIn:           OpenAIModels[GPT4o].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT4o].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT4o].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT4o].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT4o].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT4o].DefaultMaxTokens,
		SupportsStructuredOut: OpenAIModels[GPT4o].SupportsStructuredOut,
	},
	OpenRouterGPT4oMini: {
		ID:                    OpenRouterGPT4oMini,
		Name:                  "OpenRouter – GPT 4o mini",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-4o-mini",
		CostPer1MIn:           OpenAIModels[GPT4oMini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT4oMini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT4oMini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT4oMini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT4oMini].ContextWindow,
		SupportsStructuredOut: OpenAIModels[GPT4oMini].SupportsStructuredOut,
	},
	OpenRouterO1: {
		ID:                    OpenRouterO1,
		Name:                  "OpenRouter – O1",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o1",
		CostPer1MIn:           OpenAIModels[O1].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O1].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O1].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O1].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O1].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O1].DefaultMaxTokens,
		CanReason:             OpenAIModels[O1].CanReason,
		SupportsStructuredOut: OpenAIModels[O1].SupportsStructuredOut,
	},
	OpenRouterO1Pro: {
		ID:                    OpenRouterO1Pro,
		Name:                  "OpenRouter – o1 pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o1-pro",
		CostPer1MIn:           OpenAIModels[O1Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O1Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O1Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O1Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O1Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O1Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[O1Pro].CanReason,
		SupportsStructuredOut: OpenAIModels[O1Pro].SupportsStructuredOut,
	},
	OpenRouterO3: {
		ID:                    OpenRouterO3,
		Name:                  "OpenRouter – o3",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o3",
		CostPer1MIn:           OpenAIModels[O3].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3].CanReason,
		SupportsStructuredOut: OpenAIModels[O3].SupportsStructuredOut,
	},
	OpenRouterO3Mini: {
		ID:                    OpenRouterO3Mini,
		Name:                  "OpenRouter – o3 mini",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o3-mini-high",
		CostPer1MIn:           OpenAIModels[O3Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3Mini].CanReason,
		SupportsStructuredOut: OpenAIModels[O3Mini].SupportsStructuredOut,
	},
	OpenRouterO4Mini: {
		ID:                    OpenRouterO4Mini,
		Name:                  "OpenRouter – o4 mini",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o4-mini-high",
		CostPer1MIn:           OpenAIModels[O4Mini].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O4Mini].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O4Mini].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O4Mini].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O4Mini].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O4Mini].DefaultMaxTokens,
		CanReason:             OpenAIModels[O4Mini].CanReason,
		SupportsStructuredOut: OpenAIModels[O4Mini].SupportsStructuredOut,
	},
	OpenRouterO3Pro: {
		ID:                    OpenRouterO3Pro,
		Name:                  "OpenRouter – o3 pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/o3-pro",
		CostPer1MIn:           OpenAIModels[O3Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[O3Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[O3Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[O3Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[O3Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[O3Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[O3Pro].CanReason,
		SupportsStructuredOut: OpenAIModels[O3Pro].SupportsStructuredOut,
	},
	OpenRouterGPT52: {
		ID:                    OpenRouterGPT52,
		Name:                  "OpenRouter – GPT-5.2",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.2",
		CostPer1MIn:           OpenAIModels[GPT52].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52].CanReason,
		SupportsStructuredOut: OpenAIModels[GPT52].SupportsStructuredOut,
	},
	OpenRouterGPT52Pro: {
		ID:                    OpenRouterGPT52Pro,
		Name:                  "OpenRouter – GPT-5.2 Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.2-pro",
		CostPer1MIn:           OpenAIModels[GPT52Pro].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52Pro].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52Pro].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52Pro].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52Pro].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52Pro].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52Pro].CanReason,
		SupportsStructuredOut: OpenAIModels[GPT52Pro].SupportsStructuredOut,
	},
	OpenRouterGPT52Instant: {
		ID:                    OpenRouterGPT52Instant,
		Name:                  "OpenRouter – GPT-5.2 Instant",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.2-chat-latest",
		CostPer1MIn:           OpenAIModels[GPT52Instant].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52Instant].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52Instant].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52Instant].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52Instant].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52Instant].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52Instant].CanReason,
		SupportsStructuredOut: OpenAIModels[GPT52Instant].SupportsStructuredOut,
	},
	OpenRouterGemini25Flash: {
		ID:                    OpenRouterGemini25Flash,
		Name:                  "OpenRouter – Gemini 2.5 Flash",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-2.5-flash",
		CostPer1MIn:           GeminiModels[Gemini25Flash].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini25Flash].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini25Flash].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini25Flash].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini25Flash].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini25Flash].DefaultMaxTokens,
		SupportsStructuredOut: GeminiModels[Gemini25Flash].SupportsStructuredOut,
	},
	OpenRouterGemini25: {
		ID:                    OpenRouterGemini25,
		Name:                  "OpenRouter – Gemini 2.5 Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-2.5-pro",
		CostPer1MIn:           GeminiModels[Gemini25].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini25].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini25].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini25].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini25].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini25].DefaultMaxTokens,
		SupportsStructuredOut: GeminiModels[Gemini25].SupportsStructuredOut,
	},
	OpenRouterGemini3Pro: {
		ID:                    OpenRouterGemini3Pro,
		Name:                  "OpenRouter – Gemini 3 Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-3-pro",
		CostPer1MIn:           GeminiModels[Gemini3Pro].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini3Pro].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini3Pro].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini3Pro].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini3Pro].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini3Pro].DefaultMaxTokens,
		CanReason:             GeminiModels[Gemini3Pro].CanReason,
		SupportsStructuredOut: GeminiModels[Gemini3Pro].SupportsStructuredOut,
	},
	OpenRouterGemini31Pro: {
		ID:                    OpenRouterGemini31Pro,
		Name:                  "OpenRouter – Gemini 3.1 Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-3.1-pro-preview",
		CostPer1MIn:           GeminiModels[Gemini31Pro].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini31Pro].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini31Pro].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini31Pro].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini31Pro].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini31Pro].DefaultMaxTokens,
		CanReason:             GeminiModels[Gemini31Pro].CanReason,
		SupportsStructuredOut: GeminiModels[Gemini31Pro].SupportsStructuredOut,
	},
	OpenRouterGemini25FlashLite: {
		ID:                    OpenRouterGemini25FlashLite,
		Name:                  "OpenRouter – Gemini 2.5 Flash Lite",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-2.5-flash-lite",
		CostPer1MIn:           GeminiModels[Gemini25FlashLite].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini25FlashLite].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini25FlashLite].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini25FlashLite].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini25FlashLite].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini25FlashLite].DefaultMaxTokens,
		SupportsStructuredOut: GeminiModels[Gemini25FlashLite].SupportsStructuredOut,
	},
	OpenRouterClaude3Haiku: {
		ID:                    OpenRouterClaude3Haiku,
		Name:                  "OpenRouter – Claude 3 Haiku",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-3-haiku",
		CostPer1MIn:           AnthropicModels[Claude3Haiku].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude3Haiku].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude3Haiku].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude3Haiku].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude3Haiku].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude3Haiku].DefaultMaxTokens,
		SupportsStructuredOut: false,
	},
	OpenRouterClaude45Opus: {
		ID:                    OpenRouterClaude45Opus,
		Name:                  "OpenRouter – Claude 4.5 Opus",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-opus-4-5-20251101",
		CostPer1MIn:           AnthropicModels[Claude45Opus].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude45Opus].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude45Opus].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude45Opus].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude45Opus].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude45Opus].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude45Opus].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude45Opus].SupportsStructuredOut,
	},
	OpenRouterClaude46Opus: {
		ID:                    OpenRouterClaude46Opus,
		Name:                  "OpenRouter – Claude 4.6 Opus",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-opus-4-6-20260205",
		CostPer1MIn:           AnthropicModels[Claude46Opus].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude46Opus].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude46Opus].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude46Opus].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude46Opus].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude46Opus].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude46Opus].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude46Opus].SupportsStructuredOut,
	},
	OpenRouterClaude47Opus: {
		ID:                    OpenRouterClaude47Opus,
		Name:                  "OpenRouter – Claude 4.7 Opus",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-opus-4.7",
		CostPer1MIn:           AnthropicModels[Claude47Opus].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude47Opus].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude47Opus].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude47Opus].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude47Opus].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude47Opus].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude47Opus].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude47Opus].SupportsStructuredOut,
	},
	OpenRouterClaude48Opus: {
		ID:                    OpenRouterClaude48Opus,
		Name:                  "OpenRouter – Claude 4.8 Opus",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-opus-4.8",
		CostPer1MIn:           AnthropicModels[Claude48Opus].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude48Opus].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude48Opus].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude48Opus].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude48Opus].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude48Opus].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude48Opus].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude48Opus].SupportsStructuredOut,
	},
	OpenRouterClaude46Sonnet: {
		ID:                    OpenRouterClaude46Sonnet,
		Name:                  "OpenRouter – Claude 4.6 Sonnet",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-sonnet-4-6",
		CostPer1MIn:           AnthropicModels[Claude46Sonnet].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude46Sonnet].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude46Sonnet].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude46Sonnet].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude46Sonnet].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude46Sonnet].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude46Sonnet].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude46Sonnet].SupportsStructuredOut,
	},
	OpenRouterClaude5Sonnet: {
		ID:                    OpenRouterClaude5Sonnet,
		Name:                  "OpenRouter – Claude Sonnet 5",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-sonnet-5",
		CostPer1MIn:           AnthropicModels[Claude5Sonnet].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude5Sonnet].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude5Sonnet].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude5Sonnet].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude5Sonnet].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude5Sonnet].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude5Sonnet].CanReason,
		SupportsStructuredOut: AnthropicModels[Claude5Sonnet].SupportsStructuredOut,
	},
	OpenRouterGPT52Codex: {
		ID:                    OpenRouterGPT52Codex,
		Name:                  "OpenRouter – GPT-5.2 Codex",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.2-codex",
		CostPer1MIn:           OpenAIModels[GPT52Codex].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT52Codex].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT52Codex].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT52Codex].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT52Codex].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT52Codex].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT52Codex].CanReason,
		SupportsStructuredOut: OpenAIModels[GPT52Codex].SupportsStructuredOut,
	},
	OpenRouterMistralLarge3: {
		ID:                    OpenRouterMistralLarge3,
		Name:                  "OpenRouter – Mistral Large 3",
		Provider:              ProviderOpenRouter,
		APIModel:              "mistralai/mistral-large-3-25-12",
		CostPer1MIn:           MistralModels[MistralLarge3].CostPer1MIn,
		CostPer1MInCached:     MistralModels[MistralLarge3].CostPer1MInCached,
		CostPer1MOut:          MistralModels[MistralLarge3].CostPer1MOut,
		CostPer1MOutCached:    MistralModels[MistralLarge3].CostPer1MOutCached,
		ContextWindow:         MistralModels[MistralLarge3].ContextWindow,
		DefaultMaxTokens:      MistralModels[MistralLarge3].DefaultMaxTokens,
		SupportsStructuredOut: MistralModels[MistralLarge3].SupportsStructuredOut,
	},
	OpenRouterMistralMedium3: {
		ID:                    OpenRouterMistralMedium3,
		Name:                  "OpenRouter – Mistral Medium 3.1",
		Provider:              ProviderOpenRouter,
		APIModel:              "mistralai/mistral-medium-3-1-25-08",
		CostPer1MIn:           MistralModels[MistralMedium3].CostPer1MIn,
		CostPer1MInCached:     MistralModels[MistralMedium3].CostPer1MInCached,
		CostPer1MOut:          MistralModels[MistralMedium3].CostPer1MOut,
		CostPer1MOutCached:    MistralModels[MistralMedium3].CostPer1MOutCached,
		ContextWindow:         MistralModels[MistralMedium3].ContextWindow,
		DefaultMaxTokens:      MistralModels[MistralMedium3].DefaultMaxTokens,
		SupportsStructuredOut: MistralModels[MistralMedium3].SupportsStructuredOut,
	},
	OpenRouterLlama4Maverick: {
		ID:                    OpenRouterLlama4Maverick,
		Name:                  "OpenRouter – Llama 4 Maverick",
		Provider:              ProviderOpenRouter,
		APIModel:              "meta-llama/llama-4-maverick",
		CostPer1MIn:           MetaModels[MetaLlama4Maverick].CostPer1MIn,
		CostPer1MInCached:     MetaModels[MetaLlama4Maverick].CostPer1MInCached,
		CostPer1MOut:          MetaModels[MetaLlama4Maverick].CostPer1MOut,
		CostPer1MOutCached:    MetaModels[MetaLlama4Maverick].CostPer1MOutCached,
		ContextWindow:         MetaModels[MetaLlama4Maverick].ContextWindow,
		DefaultMaxTokens:      MetaModels[MetaLlama4Maverick].DefaultMaxTokens,
		SupportsStructuredOut: MetaModels[MetaLlama4Maverick].SupportsStructuredOut,
	},
	OpenRouterLlama4Scout: {
		ID:                    OpenRouterLlama4Scout,
		Name:                  "OpenRouter – Llama 4 Scout",
		Provider:              ProviderOpenRouter,
		APIModel:              "meta-llama/llama-4-scout",
		CostPer1MIn:           MetaModels[MetaLlama4Scout].CostPer1MIn,
		CostPer1MInCached:     MetaModels[MetaLlama4Scout].CostPer1MInCached,
		CostPer1MOut:          MetaModels[MetaLlama4Scout].CostPer1MOut,
		CostPer1MOutCached:    MetaModels[MetaLlama4Scout].CostPer1MOutCached,
		ContextWindow:         MetaModels[MetaLlama4Scout].ContextWindow,
		DefaultMaxTokens:      MetaModels[MetaLlama4Scout].DefaultMaxTokens,
		SupportsStructuredOut: MetaModels[MetaLlama4Scout].SupportsStructuredOut,
	},
	OpenRouterLlama3170B: {
		ID:                    OpenRouterLlama3170B,
		Name:                  "OpenRouter – Llama 3.1 70B",
		Provider:              ProviderOpenRouter,
		APIModel:              "meta-llama/Meta-Llama-3.1-70B-Instruct",
		CostPer1MIn:           MetaModels[MetaLlama3170B].CostPer1MIn,
		CostPer1MInCached:     MetaModels[MetaLlama3170B].CostPer1MInCached,
		CostPer1MOut:          MetaModels[MetaLlama3170B].CostPer1MOut,
		CostPer1MOutCached:    MetaModels[MetaLlama3170B].CostPer1MOutCached,
		ContextWindow:         MetaModels[MetaLlama3170B].ContextWindow,
		DefaultMaxTokens:      MetaModels[MetaLlama3170B].DefaultMaxTokens,
		SupportsStructuredOut: MetaModels[MetaLlama3170B].SupportsStructuredOut,
	},
	OpenRouterLlama318B: {
		ID:                    OpenRouterLlama318B,
		Name:                  "OpenRouter – Llama 3.1 8B",
		Provider:              ProviderOpenRouter,
		APIModel:              "meta-llama/Meta-Llama-3.1-8B-Instruct",
		CostPer1MIn:           MetaModels[MetaLlama318B].CostPer1MIn,
		CostPer1MInCached:     MetaModels[MetaLlama318B].CostPer1MInCached,
		CostPer1MOut:          MetaModels[MetaLlama318B].CostPer1MOut,
		CostPer1MOutCached:    MetaModels[MetaLlama318B].CostPer1MOutCached,
		ContextWindow:         MetaModels[MetaLlama318B].ContextWindow,
		DefaultMaxTokens:      MetaModels[MetaLlama318B].DefaultMaxTokens,
		SupportsStructuredOut: MetaModels[MetaLlama318B].SupportsStructuredOut,
	},
	OpenRouterDeepSeekV32: {
		ID:                    OpenRouterDeepSeekV32,
		Name:                  "OpenRouter – DeepSeek V3.2",
		Provider:              ProviderOpenRouter,
		APIModel:              "deepseek/deepseek-v3.2",
		CostPer1MIn:           DeepSeekModels[DeepSeekV32].CostPer1MIn,
		CostPer1MInCached:     DeepSeekModels[DeepSeekV32].CostPer1MInCached,
		CostPer1MOut:          DeepSeekModels[DeepSeekV32].CostPer1MOut,
		CostPer1MOutCached:    DeepSeekModels[DeepSeekV32].CostPer1MOutCached,
		ContextWindow:         DeepSeekModels[DeepSeekV32].ContextWindow,
		DefaultMaxTokens:      DeepSeekModels[DeepSeekV32].DefaultMaxTokens,
		CanReason:             DeepSeekModels[DeepSeekV32].CanReason,
		SupportsStructuredOut: DeepSeekModels[DeepSeekV32].SupportsStructuredOut,
	},
	OpenRouterDeepSeekV32Think: {
		ID:                    OpenRouterDeepSeekV32Think,
		Name:                  "OpenRouter – DeepSeek V3.2 Thinking",
		Provider:              ProviderOpenRouter,
		APIModel:              "deepseek/deepseek-v3.2-thinking",
		CostPer1MIn:           DeepSeekModels[DeepSeekV32Thinking].CostPer1MIn,
		CostPer1MInCached:     DeepSeekModels[DeepSeekV32Thinking].CostPer1MInCached,
		CostPer1MOut:          DeepSeekModels[DeepSeekV32Thinking].CostPer1MOut,
		CostPer1MOutCached:    DeepSeekModels[DeepSeekV32Thinking].CostPer1MOutCached,
		ContextWindow:         DeepSeekModels[DeepSeekV32Thinking].ContextWindow,
		DefaultMaxTokens:      DeepSeekModels[DeepSeekV32Thinking].DefaultMaxTokens,
		CanReason:             DeepSeekModels[DeepSeekV32Thinking].CanReason,
		SupportsStructuredOut: DeepSeekModels[DeepSeekV32Thinking].SupportsStructuredOut,
	},
	OpenRouterDeepSeekR1: {
		ID:                    OpenRouterDeepSeekR1,
		Name:                  "OpenRouter – DeepSeek R1",
		Provider:              ProviderOpenRouter,
		APIModel:              "deepseek/deepseek-r1",
		CostPer1MIn:           DeepSeekModels[DeepSeekR1].CostPer1MIn,
		CostPer1MInCached:     DeepSeekModels[DeepSeekR1].CostPer1MInCached,
		CostPer1MOut:          DeepSeekModels[DeepSeekR1].CostPer1MOut,
		CostPer1MOutCached:    DeepSeekModels[DeepSeekR1].CostPer1MOutCached,
		ContextWindow:         DeepSeekModels[DeepSeekR1].ContextWindow,
		DefaultMaxTokens:      DeepSeekModels[DeepSeekR1].DefaultMaxTokens,
		CanReason:             DeepSeekModels[DeepSeekR1].CanReason,
		SupportsStructuredOut: DeepSeekModels[DeepSeekR1].SupportsStructuredOut,
	},
	OpenRouterDeepSeekR1Distill: {
		ID:                    OpenRouterDeepSeekR1Distill,
		Name:                  "OpenRouter – DeepSeek R1 Distill",
		Provider:              ProviderOpenRouter,
		APIModel:              "deepseek/deepseek-r1-distill-llama-70b",
		CostPer1MIn:           DeepSeekModels[DeepSeekR1Distill].CostPer1MIn,
		CostPer1MInCached:     DeepSeekModels[DeepSeekR1Distill].CostPer1MInCached,
		CostPer1MOut:          DeepSeekModels[DeepSeekR1Distill].CostPer1MOut,
		CostPer1MOutCached:    DeepSeekModels[DeepSeekR1Distill].CostPer1MOutCached,
		ContextWindow:         DeepSeekModels[DeepSeekR1Distill].ContextWindow,
		DefaultMaxTokens:      DeepSeekModels[DeepSeekR1Distill].DefaultMaxTokens,
		CanReason:             DeepSeekModels[DeepSeekR1Distill].CanReason,
		SupportsStructuredOut: DeepSeekModels[DeepSeekR1Distill].SupportsStructuredOut,
	},
	OpenRouterQwen3Max: {
		ID:                    OpenRouterQwen3Max,
		Name:                  "OpenRouter – Qwen 3 Max",
		Provider:              ProviderOpenRouter,
		APIModel:              "qwen/qwen-3-max",
		CostPer1MIn:           QwenModels[Qwen3Max].CostPer1MIn,
		CostPer1MInCached:     QwenModels[Qwen3Max].CostPer1MInCached,
		CostPer1MOut:          QwenModels[Qwen3Max].CostPer1MOut,
		CostPer1MOutCached:    QwenModels[Qwen3Max].CostPer1MOutCached,
		ContextWindow:         QwenModels[Qwen3Max].ContextWindow,
		DefaultMaxTokens:      QwenModels[Qwen3Max].DefaultMaxTokens,
		SupportsStructuredOut: QwenModels[Qwen3Max].SupportsStructuredOut,
	},
	OpenRouterQwen3Coder480B: {
		ID:                    OpenRouterQwen3Coder480B,
		Name:                  "OpenRouter – Qwen 3 Coder 480B",
		Provider:              ProviderOpenRouter,
		APIModel:              "qwen/qwen-3-coder-480b",
		CostPer1MIn:           QwenModels[Qwen3Coder480B].CostPer1MIn,
		CostPer1MInCached:     QwenModels[Qwen3Coder480B].CostPer1MInCached,
		CostPer1MOut:          QwenModels[Qwen3Coder480B].CostPer1MOut,
		CostPer1MOutCached:    QwenModels[Qwen3Coder480B].CostPer1MOutCached,
		ContextWindow:         QwenModels[Qwen3Coder480B].ContextWindow,
		DefaultMaxTokens:      QwenModels[Qwen3Coder480B].DefaultMaxTokens,
		SupportsStructuredOut: QwenModels[Qwen3Coder480B].SupportsStructuredOut,
	},
	OpenRouterQwen3CoderPlus: {
		ID:                    OpenRouterQwen3CoderPlus,
		Name:                  "OpenRouter – Qwen 3 Coder Plus",
		Provider:              ProviderOpenRouter,
		APIModel:              "qwen/qwen-3-coder-plus",
		CostPer1MIn:           QwenModels[Qwen3CoderPlus].CostPer1MIn,
		CostPer1MInCached:     QwenModels[Qwen3CoderPlus].CostPer1MInCached,
		CostPer1MOut:          QwenModels[Qwen3CoderPlus].CostPer1MOut,
		CostPer1MOutCached:    QwenModels[Qwen3CoderPlus].CostPer1MOutCached,
		ContextWindow:         QwenModels[Qwen3CoderPlus].ContextWindow,
		DefaultMaxTokens:      QwenModels[Qwen3CoderPlus].DefaultMaxTokens,
		SupportsStructuredOut: QwenModels[Qwen3CoderPlus].SupportsStructuredOut,
	},
	OpenRouterCommandRPlus: {
		ID:                    OpenRouterCommandRPlus,
		Name:                  "OpenRouter – Command R+",
		Provider:              ProviderOpenRouter,
		APIModel:              "cohere/command-r-plus",
		CostPer1MIn:           CohereModels[CommandRPlus].CostPer1MIn,
		CostPer1MInCached:     CohereModels[CommandRPlus].CostPer1MInCached,
		CostPer1MOut:          CohereModels[CommandRPlus].CostPer1MOut,
		CostPer1MOutCached:    CohereModels[CommandRPlus].CostPer1MOutCached,
		ContextWindow:         CohereModels[CommandRPlus].ContextWindow,
		DefaultMaxTokens:      CohereModels[CommandRPlus].DefaultMaxTokens,
		SupportsStructuredOut: CohereModels[CommandRPlus].SupportsStructuredOut,
	},
	OpenRouterCommandR: {
		ID:                    OpenRouterCommandR,
		Name:                  "OpenRouter – Command R",
		Provider:              ProviderOpenRouter,
		APIModel:              "cohere/command-r",
		CostPer1MIn:           CohereModels[CommandR].CostPer1MIn,
		CostPer1MInCached:     CohereModels[CommandR].CostPer1MInCached,
		CostPer1MOut:          CohereModels[CommandR].CostPer1MOut,
		CostPer1MOutCached:    CohereModels[CommandR].CostPer1MOutCached,
		ContextWindow:         CohereModels[CommandR].ContextWindow,
		DefaultMaxTokens:      CohereModels[CommandR].DefaultMaxTokens,
		SupportsStructuredOut: CohereModels[CommandR].SupportsStructuredOut,
	},
	OpenRouterSonar: {
		ID:                    OpenRouterSonar,
		Name:                  "OpenRouter – Sonar",
		Provider:              ProviderOpenRouter,
		APIModel:              "perplexity/sonar",
		CostPer1MIn:           PerplexityModels[Sonar].CostPer1MIn,
		CostPer1MInCached:     PerplexityModels[Sonar].CostPer1MInCached,
		CostPer1MOut:          PerplexityModels[Sonar].CostPer1MOut,
		CostPer1MOutCached:    PerplexityModels[Sonar].CostPer1MOutCached,
		ContextWindow:         PerplexityModels[Sonar].ContextWindow,
		DefaultMaxTokens:      PerplexityModels[Sonar].DefaultMaxTokens,
		CanReason:             PerplexityModels[Sonar].CanReason,
		SupportsStructuredOut: PerplexityModels[Sonar].SupportsStructuredOut,
	},
	OpenRouterSonarPro: {
		ID:                    OpenRouterSonarPro,
		Name:                  "OpenRouter – Sonar Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "perplexity/sonar-pro",
		CostPer1MIn:           PerplexityModels[SonarPro].CostPer1MIn,
		CostPer1MInCached:     PerplexityModels[SonarPro].CostPer1MInCached,
		CostPer1MOut:          PerplexityModels[SonarPro].CostPer1MOut,
		CostPer1MOutCached:    PerplexityModels[SonarPro].CostPer1MOutCached,
		ContextWindow:         PerplexityModels[SonarPro].ContextWindow,
		DefaultMaxTokens:      PerplexityModels[SonarPro].DefaultMaxTokens,
		CanReason:             PerplexityModels[SonarPro].CanReason,
		SupportsStructuredOut: PerplexityModels[SonarPro].SupportsStructuredOut,
	},
	OpenRouterSonarReasoningPro: {
		ID:                    OpenRouterSonarReasoningPro,
		Name:                  "OpenRouter – Sonar Reasoning Pro",
		Provider:              ProviderOpenRouter,
		APIModel:              "perplexity/sonar-reasoning-pro",
		CostPer1MIn:           PerplexityModels[SonarReasoningPro].CostPer1MIn,
		CostPer1MInCached:     PerplexityModels[SonarReasoningPro].CostPer1MInCached,
		CostPer1MOut:          PerplexityModels[SonarReasoningPro].CostPer1MOut,
		CostPer1MOutCached:    PerplexityModels[SonarReasoningPro].CostPer1MOutCached,
		ContextWindow:         PerplexityModels[SonarReasoningPro].ContextWindow,
		DefaultMaxTokens:      PerplexityModels[SonarReasoningPro].DefaultMaxTokens,
		CanReason:             PerplexityModels[SonarReasoningPro].CanReason,
		SupportsStructuredOut: PerplexityModels[SonarReasoningPro].SupportsStructuredOut,
	},
	OpenRouterSonarDeepResearch: {
		ID:                    OpenRouterSonarDeepResearch,
		Name:                  "OpenRouter – Sonar Deep Research",
		Provider:              ProviderOpenRouter,
		APIModel:              "perplexity/sonar-deep-research",
		CostPer1MIn:           PerplexityModels[SonarDeepResearch].CostPer1MIn,
		CostPer1MInCached:     PerplexityModels[SonarDeepResearch].CostPer1MInCached,
		CostPer1MOut:          PerplexityModels[SonarDeepResearch].CostPer1MOut,
		CostPer1MOutCached:    PerplexityModels[SonarDeepResearch].CostPer1MOutCached,
		ContextWindow:         PerplexityModels[SonarDeepResearch].ContextWindow,
		DefaultMaxTokens:      PerplexityModels[SonarDeepResearch].DefaultMaxTokens,
		CanReason:             PerplexityModels[SonarDeepResearch].CanReason,
		SupportsStructuredOut: PerplexityModels[SonarDeepResearch].SupportsStructuredOut,
	},
	OpenRouterGPTOss20b: {
		ID:                    OpenRouterGPTOss20b,
		Name:                  "OpenRouter – GPT-OSS 20B",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-oss-20b",
		CostPer1MIn:           0.029,
		CostPer1MInCached:     0.0,
		CostPer1MOut:          0.14,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	OpenRouterGPTOss120b: {
		ID:                    OpenRouterGPTOss120b,
		Name:                  "OpenRouter – GPT-OSS 120B",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-oss-120b",
		CostPer1MIn:           0.036,
		CostPer1MInCached:     0.0,
		CostPer1MOut:          0.18,
		CostPer1MOutCached:    0.0,
		ContextWindow:         131_072,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	OpenRouterGrok45: {
		ID:                    OpenRouterGrok45,
		Name:                  "OpenRouter – Grok 4.5",
		Provider:              ProviderOpenRouter,
		APIModel:              "x-ai/grok-4.5",
		CostPer1MIn:           2.0,
		CostPer1MInCached:     0.5,
		CostPer1MOut:          6.0,
		CostPer1MOutCached:    0,
		ContextWindow:         500_000,
		DefaultMaxTokens:      32_000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	OpenRouterGrok43: {
		ID:                    OpenRouterGrok43,
		Name:                  "OpenRouter – Grok 4.3",
		Provider:              ProviderOpenRouter,
		APIModel:              "x-ai/grok-4.3",
		CostPer1MIn:           XAIModels[XAIGrok43].CostPer1MIn,
		CostPer1MInCached:     XAIModels[XAIGrok43].CostPer1MInCached,
		CostPer1MOut:          XAIModels[XAIGrok43].CostPer1MOut,
		CostPer1MOutCached:    XAIModels[XAIGrok43].CostPer1MOutCached,
		ContextWindow:         XAIModels[XAIGrok43].ContextWindow,
		DefaultMaxTokens:      XAIModels[XAIGrok43].DefaultMaxTokens,
		CanReason:             XAIModels[XAIGrok43].CanReason,
		SupportsAttachments:   XAIModels[XAIGrok43].SupportsAttachments,
		SupportsStructuredOut: XAIModels[XAIGrok43].SupportsStructuredOut,
	},
	OpenRouterGemini35Flash: {
		ID:                    OpenRouterGemini35Flash,
		Name:                  "OpenRouter – Gemini 3.5 Flash",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-3.5-flash",
		CostPer1MIn:           GeminiModels[Gemini35Flash].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini35Flash].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini35Flash].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini35Flash].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini35Flash].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini35Flash].DefaultMaxTokens,
		CanReason:             GeminiModels[Gemini35Flash].CanReason,
		SupportsAttachments:   GeminiModels[Gemini35Flash].SupportsAttachments,
		SupportsStructuredOut: GeminiModels[Gemini35Flash].SupportsStructuredOut,
	},
	OpenRouterGemini36Flash: {
		ID:                    OpenRouterGemini36Flash,
		Name:                  "OpenRouter – Gemini 3.6 Flash",
		Provider:              ProviderOpenRouter,
		APIModel:              "google/gemini-3.6-flash",
		CostPer1MIn:           GeminiModels[Gemini36Flash].CostPer1MIn,
		CostPer1MInCached:     GeminiModels[Gemini36Flash].CostPer1MInCached,
		CostPer1MOut:          GeminiModels[Gemini36Flash].CostPer1MOut,
		CostPer1MOutCached:    GeminiModels[Gemini36Flash].CostPer1MOutCached,
		ContextWindow:         GeminiModels[Gemini36Flash].ContextWindow,
		DefaultMaxTokens:      GeminiModels[Gemini36Flash].DefaultMaxTokens,
		CanReason:             GeminiModels[Gemini36Flash].CanReason,
		SupportsAttachments:   GeminiModels[Gemini36Flash].SupportsAttachments,
		SupportsStructuredOut: GeminiModels[Gemini36Flash].SupportsStructuredOut,
	},
	OpenRouterClaude5Opus: {
		ID:                    OpenRouterClaude5Opus,
		Name:                  "OpenRouter – Claude Opus 5",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-opus-5",
		CostPer1MIn:           AnthropicModels[Claude5Opus].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude5Opus].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude5Opus].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude5Opus].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude5Opus].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude5Opus].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude5Opus].CanReason,
		SupportsAttachments:   AnthropicModels[Claude5Opus].SupportsAttachments,
		SupportsStructuredOut: AnthropicModels[Claude5Opus].SupportsStructuredOut,
	},
	OpenRouterClaude5Fable: {
		ID:                    OpenRouterClaude5Fable,
		Name:                  "OpenRouter – Claude Fable 5",
		Provider:              ProviderOpenRouter,
		APIModel:              "anthropic/claude-fable-5",
		CostPer1MIn:           AnthropicModels[Claude5Fable].CostPer1MIn,
		CostPer1MInCached:     AnthropicModels[Claude5Fable].CostPer1MInCached,
		CostPer1MOut:          AnthropicModels[Claude5Fable].CostPer1MOut,
		CostPer1MOutCached:    AnthropicModels[Claude5Fable].CostPer1MOutCached,
		ContextWindow:         AnthropicModels[Claude5Fable].ContextWindow,
		DefaultMaxTokens:      AnthropicModels[Claude5Fable].DefaultMaxTokens,
		CanReason:             AnthropicModels[Claude5Fable].CanReason,
		SupportsAttachments:   AnthropicModels[Claude5Fable].SupportsAttachments,
		SupportsStructuredOut: AnthropicModels[Claude5Fable].SupportsStructuredOut,
	},
	OpenRouterGPT56Sol: {
		ID:                    OpenRouterGPT56Sol,
		Name:                  "OpenRouter – GPT-5.6 Sol",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.6-sol",
		CostPer1MIn:           OpenAIModels[GPT56Sol].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT56Sol].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT56Sol].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT56Sol].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT56Sol].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT56Sol].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT56Sol].CanReason,
		SupportsAttachments:   OpenAIModels[GPT56Sol].SupportsAttachments,
		SupportsStructuredOut: OpenAIModels[GPT56Sol].SupportsStructuredOut,
	},
	OpenRouterGPT56Terra: {
		ID:                    OpenRouterGPT56Terra,
		Name:                  "OpenRouter – GPT-5.6 Terra",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.6-terra",
		CostPer1MIn:           OpenAIModels[GPT56Terra].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT56Terra].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT56Terra].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT56Terra].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT56Terra].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT56Terra].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT56Terra].CanReason,
		SupportsAttachments:   OpenAIModels[GPT56Terra].SupportsAttachments,
		SupportsStructuredOut: OpenAIModels[GPT56Terra].SupportsStructuredOut,
	},
	OpenRouterGPT56Luna: {
		ID:                    OpenRouterGPT56Luna,
		Name:                  "OpenRouter – GPT-5.6 Luna",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-5.6-luna",
		CostPer1MIn:           OpenAIModels[GPT56Luna].CostPer1MIn,
		CostPer1MInCached:     OpenAIModels[GPT56Luna].CostPer1MInCached,
		CostPer1MOut:          OpenAIModels[GPT56Luna].CostPer1MOut,
		CostPer1MOutCached:    OpenAIModels[GPT56Luna].CostPer1MOutCached,
		ContextWindow:         OpenAIModels[GPT56Luna].ContextWindow,
		DefaultMaxTokens:      OpenAIModels[GPT56Luna].DefaultMaxTokens,
		CanReason:             OpenAIModels[GPT56Luna].CanReason,
		SupportsAttachments:   OpenAIModels[GPT56Luna].SupportsAttachments,
		SupportsStructuredOut: OpenAIModels[GPT56Luna].SupportsStructuredOut,
	},
}

// OpenRouter image generation model IDs.
const (
	OpenRouterGPTImage2               ID = "openrouter.gpt-image-2"
	OpenRouterGPTImage1               ID = "openrouter.gpt-image-1"
	OpenRouterGPTImage1Mini           ID = "openrouter.gpt-image-1-mini"
	OpenRouterGPT5Image               ID = "openrouter.gpt-5-image"
	OpenRouterGPT5ImageMini           ID = "openrouter.gpt-5-image-mini"
	OpenRouterGPT54Image2             ID = "openrouter.gpt-5.4-image-2"
	OpenRouterGemini25FlashImage      ID = "openrouter.gemini-2.5-flash-image"
	OpenRouterGemini3ProImage         ID = "openrouter.gemini-3-pro-image"
	OpenRouterGemini31FlashImage      ID = "openrouter.gemini-3.1-flash-image"
	OpenRouterGemini31FlashLiteImage  ID = "openrouter.gemini-3.1-flash-lite-image"
	OpenRouterSeedream45              ID = "openrouter.seedream-4.5"
	OpenRouterFlux2Pro                ID = "openrouter.flux.2-pro"
	OpenRouterFlux2Max                ID = "openrouter.flux.2-max"
	OpenRouterFlux2Flex               ID = "openrouter.flux.2-flex"
	OpenRouterFlux2Klein4B            ID = "openrouter.flux.2-klein-4b"
	OpenRouterGrokImagineImageQuality ID = "openrouter.grok-imagine-image-quality"
	OpenRouterMAIImage25              ID = "openrouter.mai-image-2.5"
	OpenRouterMAIImage25Pro           ID = "openrouter.mai-image-2.5-pro"
	OpenRouterRiverflowV25Pro         ID = "openrouter.riverflow-v2.5-pro"
	OpenRouterRiverflowV25Fast        ID = "openrouter.riverflow-v2.5-fast"
	OpenRouterRecraftV41              ID = "openrouter.recraft-v4.1"
	OpenRouterRecraftV41Pro           ID = "openrouter.recraft-v4.1-pro"
	OpenRouterRecraftV41Vector        ID = "openrouter.recraft-v4.1-vector"
	OpenRouterRecraftV41ProVector     ID = "openrouter.recraft-v4.1-pro-vector"
	OpenRouterRecraftV4               ID = "openrouter.recraft-v4"
	OpenRouterRecraftV4Vector         ID = "openrouter.recraft-v4-vector"
)

// OpenRouterImageGenerationModels maps OpenRouter image model IDs to their
// configurations.
//
// These are known-good defaults, not a mirror of OpenRouter's catalogue:
// OpenRouter routes more image models than this package catalogues and the list
// moves weekly. Any OpenRouter image model id works with a bare
// [ImageGenerationModel] even without an entry here — see the image/openrouter
// package docs.
//
// Capability source: https://openrouter.ai/api/v1/images/models. Pricing
// source: the per-model .../endpoints route. Fetched: 2026-07-31.
//
// Pricing is only populated where OpenRouter publishes a flat per-image rate,
// or where an upstream registry in this package already carries a per-image
// estimate for the same model. It is left nil for the models OpenRouter bills
// per output token or per megapixel, and for the models it bills at several
// per-image tiers without saying which tier a given request lands in — a made-up
// per-image figure would be worse than none. Read usage.Cost off the response
// for what a request actually cost.
//
// DefaultSize is deliberately left empty across these entries. SupportedSizes
// records the resolution enum a model advertises, but advertising a tier is not
// the same as accepting it: seedream-4.5 lists 1K, 2K and 4K yet rejects both 1K
// and 2K at 16:9 with "requires at least 3,686,400 output pixels". Omitting
// resolution lets OpenRouter apply the model's real default, which is the only
// value verified to work for every entry here.
var OpenRouterImageGenerationModels = map[ID]ImageGenerationModel{
	OpenRouterGPTImage2: {
		ID:              OpenRouterGPTImage2,
		Name:            "OpenRouter – GPT Image 2",
		Provider:        ProviderOpenRouter,
		APIModel:        "openai/gpt-image-2",
		Pricing:         OpenAIImageGenerationModels[GPTImage2].Pricing,
		MaxPromptTokens: OpenAIImageGenerationModels[GPTImage2].MaxPromptTokens,
		SupportedAspectRatios: []string{
			"1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"auto", "low", "medium", "high"},
		DefaultQuality:     "auto",
		SupportsStreaming:  true,
	},
	OpenRouterGPTImage1: {
		ID:                    OpenRouterGPTImage1,
		Name:                  "OpenRouter – GPT Image 1",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-image-1",
		MaxPromptTokens:       4000,
		SupportedAspectRatios: []string{"1:1", "3:2", "2:3", "auto"},
		DefaultAspectRatio:    "1:1",
		SupportedQualities:    []string{"auto", "low", "medium", "high"},
		DefaultQuality:        "auto",
		SupportsStreaming:     true,
	},
	OpenRouterGPTImage1Mini: {
		ID:                    OpenRouterGPTImage1Mini,
		Name:                  "OpenRouter – GPT Image 1 mini",
		Provider:              ProviderOpenRouter,
		APIModel:              "openai/gpt-image-1-mini",
		MaxPromptTokens:       4000,
		SupportedAspectRatios: []string{"1:1", "3:2", "2:3", "auto"},
		DefaultAspectRatio:    "1:1",
		SupportedQualities:    []string{"auto", "low", "medium", "high"},
		DefaultQuality:        "auto",
		SupportsStreaming:     true,
	},
	OpenRouterGPT5Image: {
		ID:                 OpenRouterGPT5Image,
		Name:               "OpenRouter – GPT-5 Image",
		Provider:           ProviderOpenRouter,
		APIModel:           "openai/gpt-5-image",
		MaxPromptTokens:    4000,
		SupportedQualities: []string{"auto", "low", "medium", "high"},
		DefaultQuality:     "auto",
		SupportsStreaming:  true,
	},
	OpenRouterGPT5ImageMini: {
		ID:                 OpenRouterGPT5ImageMini,
		Name:               "OpenRouter – GPT-5 Image mini",
		Provider:           ProviderOpenRouter,
		APIModel:           "openai/gpt-5-image-mini",
		MaxPromptTokens:    4000,
		SupportedQualities: []string{"auto", "low", "medium", "high"},
		DefaultQuality:     "auto",
		SupportsStreaming:  true,
	},
	OpenRouterGPT54Image2: {
		ID:                 OpenRouterGPT54Image2,
		Name:               "OpenRouter – GPT-5.4 Image 2",
		Provider:           ProviderOpenRouter,
		APIModel:           "openai/gpt-5.4-image-2",
		MaxPromptTokens:    4000,
		SupportedQualities: []string{"auto", "low", "medium", "high"},
		DefaultQuality:     "auto",
		SupportsStreaming:  true,
	},
	OpenRouterGemini25FlashImage: {
		ID:              OpenRouterGemini25FlashImage,
		Name:            "OpenRouter – Gemini 2.5 Flash Image (Nano Banana)",
		Provider:        ProviderOpenRouter,
		APIModel:        "google/gemini-2.5-flash-image",
		Pricing:         GeminiImageGenerationModels[Gemini25FlashImage].Pricing,
		MaxPromptTokens: GeminiImageGenerationModels[Gemini25FlashImage].MaxPromptTokens,
		SupportedAspectRatios: []string{
			"1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterGemini3ProImage: {
		ID:              OpenRouterGemini3ProImage,
		Name:            "OpenRouter – Gemini 3 Pro Image (Nano Banana Pro)",
		Provider:        ProviderOpenRouter,
		APIModel:        "google/gemini-3-pro-image",
		Pricing:         GeminiImageGenerationModels[Gemini3ProImage].Pricing,
		MaxPromptTokens: GeminiImageGenerationModels[Gemini3ProImage].MaxPromptTokens,
		SupportedAspectRatios: []string{
			"1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterGemini31FlashImage: {
		ID:              OpenRouterGemini31FlashImage,
		Name:            "OpenRouter – Gemini 3.1 Flash Image (Nano Banana 2)",
		Provider:        ProviderOpenRouter,
		APIModel:        "google/gemini-3.1-flash-image",
		Pricing:         GeminiImageGenerationModels[Gemini31FlashImagePreview].Pricing,
		MaxPromptTokens: GeminiImageGenerationModels[Gemini31FlashImagePreview].MaxPromptTokens,
		SupportedAspectRatios: []string{
			"1:1", "1:4", "1:8", "2:3", "3:2", "3:4", "4:1", "4:3", "4:5",
			"5:4", "8:1", "9:16", "16:9", "21:9",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"512", "1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterGemini31FlashLiteImage: {
		ID:              OpenRouterGemini31FlashLiteImage,
		Name:            "OpenRouter – Gemini 3.1 Flash Lite Image (Nano Banana 2 Lite)",
		Provider:        ProviderOpenRouter,
		APIModel:        "google/gemini-3.1-flash-lite-image",
		Pricing:         GeminiImageGenerationModels[Gemini31FlashLiteImage].Pricing,
		MaxPromptTokens: GeminiImageGenerationModels[Gemini31FlashLiteImage].MaxPromptTokens,
		SupportedAspectRatios: []string{
			"1:1", "1:4", "1:8", "2:3", "3:2", "3:4", "4:1", "4:3", "4:5",
			"5:4", "8:1", "9:16", "16:9", "21:9",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterSeedream45: {
		ID:       OpenRouterSeedream45,
		Name:     "OpenRouter – Seedream 4.5",
		Provider: ProviderOpenRouter,
		APIModel: "bytedance-seed/seedream-4.5",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.04},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "1:2", "2:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4",
			"9:16", "16:9", "9:19.5", "19.5:9", "9:20", "20:9", "9:21",
			"21:9", "auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterFlux2Pro: {
		ID:              OpenRouterFlux2Pro,
		Name:            "OpenRouter – FLUX.2 Pro",
		Provider:        ProviderOpenRouter,
		APIModel:        "black-forest-labs/flux.2-pro",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterFlux2Max: {
		ID:              OpenRouterFlux2Max,
		Name:            "OpenRouter – FLUX.2 Max",
		Provider:        ProviderOpenRouter,
		APIModel:        "black-forest-labs/flux.2-max",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterFlux2Flex: {
		ID:              OpenRouterFlux2Flex,
		Name:            "OpenRouter – FLUX.2 Flex",
		Provider:        ProviderOpenRouter,
		APIModel:        "black-forest-labs/flux.2-flex",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterFlux2Klein4B: {
		ID:              OpenRouterFlux2Klein4B,
		Name:            "OpenRouter – FLUX.2 Klein 4B",
		Provider:        ProviderOpenRouter,
		APIModel:        "black-forest-labs/flux.2-klein-4b",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterGrokImagineImageQuality: {
		ID:              OpenRouterGrokImagineImageQuality,
		Name:            "OpenRouter – Grok Imagine Image Quality",
		Provider:        ProviderOpenRouter,
		APIModel:        "x-ai/grok-imagine-image-quality",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "3:4", "4:3", "9:16", "16:9", "2:3", "3:2", "9:19.5",
			"19.5:9", "9:20", "20:9", "1:2", "2:1", "auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K", "2K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterMAIImage25: {
		ID:              OpenRouterMAIImage25,
		Name:            "OpenRouter – MAI-Image-2.5",
		Provider:        ProviderOpenRouter,
		APIModel:        "microsoft/mai-image-2.5",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterMAIImage25Pro: {
		ID:              OpenRouterMAIImage25Pro,
		Name:            "OpenRouter – MAI-Image-2.5 Pro",
		Provider:        ProviderOpenRouter,
		APIModel:        "microsoft/mai-image-2.5-pro",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRiverflowV25Pro: {
		ID:              OpenRouterRiverflowV25Pro,
		Name:            "OpenRouter – Riverflow V2.5 Pro",
		Provider:        ProviderOpenRouter,
		APIModel:        "sourceful/riverflow-v2.5-pro",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRiverflowV25Fast: {
		ID:              OpenRouterRiverflowV25Fast,
		Name:            "OpenRouter – Riverflow V2.5 Fast",
		Provider:        ProviderOpenRouter,
		APIModel:        "sourceful/riverflow-v2.5-fast",
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1", "4:3", "3:4", "3:2", "2:3", "16:9", "9:16", "21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedSizes:     []string{"1K", "2K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV41: {
		ID:       OpenRouterRecraftV41,
		Name:     "OpenRouter – Recraft V4.1",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4.1",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.035},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV41Pro: {
		ID:       OpenRouterRecraftV41Pro,
		Name:     "OpenRouter – Recraft V4.1 Pro",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4.1-pro",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.21},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV41Vector: {
		ID:       OpenRouterRecraftV41Vector,
		Name:     "OpenRouter – Recraft V4.1 Vector",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4.1-vector",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.08},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV41ProVector: {
		ID:       OpenRouterRecraftV41ProVector,
		Name:     "OpenRouter – Recraft V4.1 Pro Vector",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4.1-pro-vector",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.3},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV4: {
		ID:       OpenRouterRecraftV4,
		Name:     "OpenRouter – Recraft V4",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.04},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
	OpenRouterRecraftV4Vector: {
		ID:       OpenRouterRecraftV4Vector,
		Name:     "OpenRouter – Recraft V4 Vector",
		Provider: ProviderOpenRouter,
		APIModel: "recraft/recraft-v4-vector",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.08},
		},
		MaxPromptTokens: 4000,
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
	},
}

// OpenRouter text-to-speech model IDs.
const (
	OpenRouterMAIVoice2            ID = "openrouter.mai-voice-2"
	OpenRouterMAIVoice2Flash       ID = "openrouter.mai-voice-2-flash"
	OpenRouterVoxtralMiniTTS       ID = "openrouter.voxtral-mini-tts-2603"
	OpenRouterGrokVoiceTTS1        ID = "openrouter.grok-voice-tts-1.0"
	OpenRouterAura2                ID = "openrouter.aura-2"
	OpenRouterGemini31FlashTTS     ID = "openrouter.gemini-3.1-flash-tts-preview"
	OpenRouterQwenAudio3TTSFlash   ID = "openrouter.qwen-audio-3.0-tts-flash"
	OpenRouterQwenAudio3TTSPlus    ID = "openrouter.qwen-audio-3.0-tts-plus"
	OpenRouterFishAudioS1          ID = "openrouter.s1"
	OpenRouterFishAudioS2Pro       ID = "openrouter.s2-pro"
	OpenRouterFishAudioS21Pro      ID = "openrouter.s2.1-pro"
	OpenRouterMiniMaxSpeech28HD    ID = "openrouter.speech-2.8-hd"
	OpenRouterMiniMaxSpeech28Turbo ID = "openrouter.speech-2.8-turbo"
	OpenRouterZonosTransformer     ID = "openrouter.zonos-v0.1-transformer"
	OpenRouterZonosHybrid          ID = "openrouter.zonos-v0.1-hybrid"
	OpenRouterOrpheus3B            ID = "openrouter.orpheus-3b-0.1-ft"
	OpenRouterCSM1B                ID = "openrouter.csm-1b"
	OpenRouterKokoro82M            ID = "openrouter.kokoro-82m"
)

// OpenRouterAudioModels maps OpenRouter text-to-speech model IDs to their
// configurations.
//
// Known-good defaults; any OpenRouter speech model id works even without an
// entry here.
//
// Source: https://openrouter.ai/api/v1/models?output_modalities=speech, whose
// prompt rate for speech models is quoted per input character and is scaled to
// CostPer1MChars here. Fetched: 2026-07-31.
//
// OpenRouter's /audio/speech defaults to pcm where OpenAI defaults to mp3, so
// DefaultFormat records pcm. Voice ids are per-model and per-upstream; there is
// no list-voices route, so consult the model's page.
var OpenRouterAudioModels = map[ID]AudioModel{
	OpenRouterMAIVoice2: {
		ID:                OpenRouterMAIVoice2,
		Name:              "OpenRouter – MAI-Voice-2",
		Provider:          ProviderOpenRouter,
		APIModel:          "microsoft/mai-voice-2",
		CostPer1MChars:    22.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterMAIVoice2Flash: {
		ID:                OpenRouterMAIVoice2Flash,
		Name:              "OpenRouter – MAI-Voice-2 Flash",
		Provider:          ProviderOpenRouter,
		APIModel:          "microsoft/mai-voice-2-flash",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterVoxtralMiniTTS: {
		ID:                OpenRouterVoxtralMiniTTS,
		Name:              "OpenRouter – Voxtral Mini TTS",
		Provider:          ProviderOpenRouter,
		APIModel:          "mistralai/voxtral-mini-tts-2603",
		CostPer1MChars:    16.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterGrokVoiceTTS1: {
		ID:                OpenRouterGrokVoiceTTS1,
		Name:              "OpenRouter – Grok Voice TTS 1.0",
		Provider:          ProviderOpenRouter,
		APIModel:          "x-ai/grok-voice-tts-1.0",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterAura2: {
		ID:                OpenRouterAura2,
		Name:              "OpenRouter – Deepgram Aura-2",
		Provider:          ProviderOpenRouter,
		APIModel:          "deepgram/aura-2",
		CostPer1MChars:    30.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterGemini31FlashTTS: {
		ID:                OpenRouterGemini31FlashTTS,
		Name:              "OpenRouter – Gemini 3.1 Flash TTS Preview",
		Provider:          ProviderOpenRouter,
		APIModel:          "google/gemini-3.1-flash-tts-preview",
		CostPer1MChars:    1.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterQwenAudio3TTSFlash: {
		ID:                OpenRouterQwenAudio3TTSFlash,
		Name:              "OpenRouter – Qwen-Audio-3.0-TTS Flash",
		Provider:          ProviderOpenRouter,
		APIModel:          "qwen/qwen-audio-3.0-tts-flash",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterQwenAudio3TTSPlus: {
		ID:                OpenRouterQwenAudio3TTSPlus,
		Name:              "OpenRouter – Qwen-Audio-3.0-TTS Plus",
		Provider:          ProviderOpenRouter,
		APIModel:          "qwen/qwen-audio-3.0-tts-plus",
		CostPer1MChars:    20.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterFishAudioS1: {
		ID:                OpenRouterFishAudioS1,
		Name:              "OpenRouter – Fish Audio S1",
		Provider:          ProviderOpenRouter,
		APIModel:          "fish-audio/s1",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterFishAudioS2Pro: {
		ID:                OpenRouterFishAudioS2Pro,
		Name:              "OpenRouter – Fish Audio S2 Pro",
		Provider:          ProviderOpenRouter,
		APIModel:          "fish-audio/s2-pro",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterFishAudioS21Pro: {
		ID:                OpenRouterFishAudioS21Pro,
		Name:              "OpenRouter – Fish Audio S2.1 Pro",
		Provider:          ProviderOpenRouter,
		APIModel:          "fish-audio/s2.1-pro",
		CostPer1MChars:    15.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterMiniMaxSpeech28HD: {
		ID:                OpenRouterMiniMaxSpeech28HD,
		Name:              "OpenRouter – MiniMax Speech 2.8 HD",
		Provider:          ProviderOpenRouter,
		APIModel:          "minimax/speech-2.8-hd",
		CostPer1MChars:    100.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterMiniMaxSpeech28Turbo: {
		ID:                OpenRouterMiniMaxSpeech28Turbo,
		Name:              "OpenRouter – MiniMax Speech 2.8 Turbo",
		Provider:          ProviderOpenRouter,
		APIModel:          "minimax/speech-2.8-turbo",
		CostPer1MChars:    60.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterZonosTransformer: {
		ID:                OpenRouterZonosTransformer,
		Name:              "OpenRouter – Zonos v0.1 Transformer",
		Provider:          ProviderOpenRouter,
		APIModel:          "zyphra/zonos-v0.1-transformer",
		CostPer1MChars:    7.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterZonosHybrid: {
		ID:                OpenRouterZonosHybrid,
		Name:              "OpenRouter – Zonos v0.1 Hybrid",
		Provider:          ProviderOpenRouter,
		APIModel:          "zyphra/zonos-v0.1-hybrid",
		CostPer1MChars:    7.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterOrpheus3B: {
		ID:                OpenRouterOrpheus3B,
		Name:              "OpenRouter – Orpheus 3B",
		Provider:          ProviderOpenRouter,
		APIModel:          "canopylabs/orpheus-3b-0.1-ft",
		CostPer1MChars:    7.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterCSM1B: {
		ID:                OpenRouterCSM1B,
		Name:              "OpenRouter – Sesame CSM 1B",
		Provider:          ProviderOpenRouter,
		APIModel:          "sesame/csm-1b",
		CostPer1MChars:    7.0,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
	OpenRouterKokoro82M: {
		ID:                OpenRouterKokoro82M,
		Name:              "OpenRouter – Kokoro 82M",
		Provider:          ProviderOpenRouter,
		APIModel:          "hexgrad/kokoro-82m",
		CostPer1MChars:    0.62,
		SupportedFormats:  []string{"mp3", "pcm"},
		DefaultFormat:     "pcm",
		SupportsStreaming: false,
	},
}

// OpenRouter speech-to-text model IDs.
const (
	OpenRouterWhisper1              ID = "openrouter.whisper-1"
	OpenRouterWhisperLargeV3        ID = "openrouter.whisper-large-v3"
	OpenRouterWhisperLargeV3Turbo   ID = "openrouter.whisper-large-v3-turbo"
	OpenRouterGPT4oTranscribe       ID = "openrouter.gpt-4o-transcribe"
	OpenRouterGPT4oMiniTranscribe   ID = "openrouter.gpt-4o-mini-transcribe"
	OpenRouterVoxtralMiniTranscribe ID = "openrouter.voxtral-mini-transcribe"
	OpenRouterFishAudioTranscribe1  ID = "openrouter.transcribe-1"
	OpenRouterGrokSTT1              ID = "openrouter.grok-stt-1.0"
	OpenRouterNova3                 ID = "openrouter.nova-3"
	OpenRouterMAITranscribe15       ID = "openrouter.mai-transcribe-1.5"
	OpenRouterParakeetTDT06BV3      ID = "openrouter.parakeet-tdt-0.6b-v3"
	OpenRouterQwen3ASRFlash         ID = "openrouter.qwen3-asr-flash-2026-02-10"
	OpenRouterChirp3                ID = "openrouter.chirp-3"
)

// OpenRouterTranscriptionModels maps OpenRouter speech-to-text model IDs to
// their configurations.
//
// Known-good defaults; any OpenRouter transcription model id works even without
// an entry here.
//
// Source: the OpenRouter models API filtered to transcription outputs, plus the
// speech-to-text guide. Fetched: 2026-07-31.
//
// Two OpenRouter-wide caveats are encoded here. verbose_json — and with it
// segments and word timestamps — is only accepted by the OpenAI-compatible
// upstreams (OpenAI, Groq, Together); the rest reject it with HTTP 400, so
// SupportsTimestamps is false for those. OpenRouter exposes no
// /audio/translations route at all, so SupportsTranslation is false for every
// entry regardless of what the upstream model itself can do.
//
// Rates mirror the upstream registries in this package where an entry exists.
// Where OpenRouter quotes a rate in a unit TranscriptionModel cannot express
// (per audio minute rather than per token) the cost fields are left zero rather
// than converted into a fabricated per-token figure.
var OpenRouterTranscriptionModels = map[ID]TranscriptionModel{
	OpenRouterWhisper1: {
		ID:                       OpenRouterWhisper1,
		Name:                     "OpenRouter – Whisper v2",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "openai/whisper-1",
		CostPer1MIn:              OpenAITranscriptionModels[Whisper1].CostPer1MIn,
		MaxFileSizeMB:            OpenAITranscriptionModels[Whisper1].MaxFileSizeMB,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	OpenRouterWhisperLargeV3: {
		ID:                       OpenRouterWhisperLargeV3,
		Name:                     "OpenRouter – Whisper Large v3",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "openai/whisper-large-v3",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	OpenRouterWhisperLargeV3Turbo: {
		ID:                       OpenRouterWhisperLargeV3Turbo,
		Name:                     "OpenRouter – Whisper Large v3 Turbo",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "openai/whisper-large-v3-turbo",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	OpenRouterGPT4oTranscribe: {
		ID:                       OpenRouterGPT4oTranscribe,
		Name:                     "OpenRouter – GPT-4o Transcribe",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "openai/gpt-4o-transcribe",
		CostPer1MIn:              2.5,
		CostPer1MOut:             10.0,
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterGPT4oMiniTranscribe: {
		ID:                       OpenRouterGPT4oMiniTranscribe,
		Name:                     "OpenRouter – GPT-4o Mini Transcribe",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "openai/gpt-4o-mini-transcribe",
		CostPer1MIn:              1.25,
		CostPer1MOut:             5.0,
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterVoxtralMiniTranscribe: {
		ID:                       OpenRouterVoxtralMiniTranscribe,
		Name:                     "OpenRouter – Voxtral Mini Transcribe",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "mistralai/voxtral-mini-transcribe",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterFishAudioTranscribe1: {
		ID:                       OpenRouterFishAudioTranscribe1,
		Name:                     "OpenRouter – Fish Audio Transcribe 1",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "fish-audio/transcribe-1",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterGrokSTT1: {
		ID:                       OpenRouterGrokSTT1,
		Name:                     "OpenRouter – Grok STT 1.0",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "x-ai/grok-stt-1.0",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterNova3: {
		ID:                       OpenRouterNova3,
		Name:                     "OpenRouter – Deepgram Nova-3",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "deepgram/nova-3",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterMAITranscribe15: {
		ID:                       OpenRouterMAITranscribe15,
		Name:                     "OpenRouter – MAI-Transcribe 1.5",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "microsoft/mai-transcribe-1.5",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterParakeetTDT06BV3: {
		ID:                       OpenRouterParakeetTDT06BV3,
		Name:                     "OpenRouter – Parakeet TDT 0.6B v3",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "nvidia/parakeet-tdt-0.6b-v3",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterQwen3ASRFlash: {
		ID:                       OpenRouterQwen3ASRFlash,
		Name:                     "OpenRouter – Qwen3 ASR Flash",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "qwen/qwen3-asr-flash-2026-02-10",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
	OpenRouterChirp3: {
		ID:                       OpenRouterChirp3,
		Name:                     "OpenRouter – Chirp 3",
		Provider:                 ProviderOpenRouter,
		APIModel:                 "google/chirp-3",
		MaxFileSizeMB:            25,
		SupportedFormats:         OpenAITranscriptionModels[Whisper1].SupportedFormats,
		SupportsTimestamps:       false,
		SupportsWordTimestamps:   false,
		SupportsTranslation:      false,
		SupportsStreaming:        false,
		SupportedResponseFormats: []string{"json"},
	},
}
