package model

const (
	ProviderOpenAI ModelProvider = "openai"

	GPT41           ModelID = "gpt-4.1"
	GPT41Mini       ModelID = "gpt-4.1-mini"
	GPT41Nano       ModelID = "gpt-4.1-nano"
	GPT45Preview    ModelID = "gpt-4.5-preview"
	GPT4o           ModelID = "gpt-4o"
	GPT4oMini       ModelID = "gpt-4o-mini"
	O1              ModelID = "o1"
	O1Pro           ModelID = "o1-pro"
	O1Mini          ModelID = "o1-mini"
	O3              ModelID = "o3"
	O3Mini          ModelID = "o3-mini"
	O4Mini          ModelID = "o4-mini"
	GPT5            ModelID = "gpt-5"
	GPT5Mini        ModelID = "gpt-5-mini"
	GPT5Nano        ModelID = "gpt-5-nano"
	GPT51           ModelID = "gpt-5.1"
	GPT51Mini       ModelID = "gpt-5.1-mini"
	GPT51Nano       ModelID = "gpt-5.1-nano"
	GPT51ChatLatest ModelID = "gpt-5.1-chat-latest"
	GPT5ChatLatest  ModelID = "gpt-5-chat-latest"
	GPT51Codex      ModelID = "gpt-5.1-codex"
	GPT5Codex       ModelID = "gpt-5-codex"
	GPT51CodexMini  ModelID = "gpt-5.1-codex-mini"
	GPT5Pro         ModelID = "gpt-5-pro"

	TextEmbedding3Large ModelID = "text-embedding-3-large"
	TextEmbedding3Small ModelID = "text-embedding-3-small"
	AdaEmbedding002     ModelID = "text-embedding-ada-002"

	DALLE2    ModelID = "dall-e-2"
	DALLE3    ModelID = "dall-e-3"
	GPTImage1 ModelID = "gpt-image-1"
)

var OpenAIModels = map[ModelID]Model{
	GPT41: {
		ID:                    GPT41,
		Name:                  "GPT 4.1",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4.1",
		CostPer1MIn:           2.00,
		CostPer1MInCached:     0.50,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          8.00,
		ContextWindow:         1_047_576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Mini: {
		ID:                    GPT41Mini,
		Name:                  "GPT 4.1 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4.1",
		CostPer1MIn:           0.40,
		CostPer1MInCached:     0.10,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          1.60,
		ContextWindow:         200_000,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Nano: {
		ID:                    GPT41Nano,
		Name:                  "GPT 4.1 nano",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4.1-nano",
		CostPer1MIn:           0.10,
		CostPer1MInCached:     0.025,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          0.40,
		ContextWindow:         1_047_576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT45Preview: {
		ID:                    GPT45Preview,
		Name:                  "GPT 4.5 preview",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4.5-preview",
		CostPer1MIn:           75.00,
		CostPer1MInCached:     37.50,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          150.00,
		ContextWindow:         128_000,
		DefaultMaxTokens:      15000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4o: {
		ID:                    GPT4o,
		Name:                  "GPT 4o",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4o",
		CostPer1MIn:           2.50,
		CostPer1MInCached:     1.25,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         128_000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4oMini: {
		ID:                    GPT4oMini,
		Name:                  "GPT 4o mini",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-4o-mini",
		CostPer1MIn:           0.15,
		CostPer1MInCached:     0.075,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          0.60,
		ContextWindow:         128_000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1: {
		ID:                    O1,
		Name:                  "O1",
		Provider:              ProviderOpenAI,
		APIModel:              "o1",
		CostPer1MIn:           15.00,
		CostPer1MInCached:     7.50,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          60.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1Pro: {
		ID:                    O1Pro,
		Name:                  "o1 pro",
		Provider:              ProviderOpenAI,
		APIModel:              "o1-pro",
		CostPer1MIn:           150.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          600.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1Mini: {
		ID:                    O1Mini,
		Name:                  "o1 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "o1-mini",
		CostPer1MIn:           1.10,
		CostPer1MInCached:     0.55,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          4.40,
		ContextWindow:         128_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3: {
		ID:                    O3,
		Name:                  "o3",
		Provider:              ProviderOpenAI,
		APIModel:              "o3",
		CostPer1MIn:           10.00,
		CostPer1MInCached:     2.50,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          40.00,
		ContextWindow:         200_000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3Mini: {
		ID:                    O3Mini,
		Name:                  "o3 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "o3-mini",
		CostPer1MIn:           1.10,
		CostPer1MInCached:     0.55,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          4.40,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   false,
		SupportsStructuredOut: true,
	},
	O4Mini: {
		ID:                    O4Mini,
		Name:                  "o4 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "o4-mini",
		CostPer1MIn:           1.10,
		CostPer1MInCached:     0.275,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          4.40,
		ContextWindow:         128_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5: {
		ID:                    GPT5,
		Name:                  "GPT-5",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Mini: {
		ID:                    GPT5Mini,
		Name:                  "GPT-5 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5-minI",
		CostPer1MIn:           0.25,
		CostPer1MInCached:     0.025,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          2.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Nano: {
		ID:                    GPT5Nano,
		Name:                  "GPT-5 nano",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5-nano",
		CostPer1MIn:           0.05,
		CostPer1MInCached:     0.005,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          0.40,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51: {
		ID:                    GPT51,
		Name:                  "GPT-5.1",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51Mini: {
		ID:                    GPT51Mini,
		Name:                  "GPT-5.1 mini",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1-mini",
		CostPer1MIn:           0.25,
		CostPer1MInCached:     0.025,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          2.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51Nano: {
		ID:                    GPT51Nano,
		Name:                  "GPT-5.1 nano",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1-nano",
		CostPer1MIn:           0.05,
		CostPer1MInCached:     0.005,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          0.40,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51ChatLatest: {
		ID:                    GPT51ChatLatest,
		Name:                  "GPT-5.1 chat latest",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1-chat-latest",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5ChatLatest: {
		ID:                    GPT5ChatLatest,
		Name:                  "GPT-5 chat latest",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5-chat-latest",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51Codex: {
		ID:                    GPT51Codex,
		Name:                  "GPT-5.1 codex",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1-codex",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Codex: {
		ID:                    GPT5Codex,
		Name:                  "GPT-5 codex",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5-codex",
		CostPer1MIn:           1.25,
		CostPer1MInCached:     0.125,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          10.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51CodexMini: {
		ID:                    GPT51CodexMini,
		Name:                  "GPT-5.1 codex mini",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5.1-codex-mini",
		CostPer1MIn:           0.25,
		CostPer1MInCached:     0.025,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          2.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Pro: {
		ID:                    GPT5Pro,
		Name:                  "GPT-5 pro",
		Provider:              ProviderOpenAI,
		APIModel:              "gpt-5-pro",
		CostPer1MIn:           15.00,
		CostPer1MInCached:     0.0,
		CostPer1MOutCached:    0.0,
		CostPer1MOut:          120.00,
		ContextWindow:         200_000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}

var OpenAIEmbeddingModels = map[ModelID]EmbeddingModel{
	TextEmbedding3Large: {
		ID:                  TextEmbedding3Large,
		Name:                "Text Embedding 3 Large",
		Provider:            ProviderOpenAI,
		APIModel:            "text-embedding-3-large",
		CostPer1MTokens:     0.13,
		MaxInputTokens:      8191,
		EmbeddingDims:       3072,
		SupportedDimensions: []int{256, 512, 1024, 1536, 2048, 3072},
		MaxBatchSize:        2048,
		MaxTokensPerBatch:   1000000,
	},
	TextEmbedding3Small: {
		ID:                  TextEmbedding3Small,
		Name:                "Text Embedding 3 Small",
		Provider:            ProviderOpenAI,
		APIModel:            "text-embedding-3-small",
		CostPer1MTokens:     0.02,
		MaxInputTokens:      8191,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{512, 1536},
		MaxBatchSize:        2048,
		MaxTokensPerBatch:   1000000,
	},
	AdaEmbedding002: {
		ID:                  AdaEmbedding002,
		Name:                "Ada Embedding 002",
		Provider:            ProviderOpenAI,
		APIModel:            "text-embedding-ada-002",
		CostPer1MTokens:     0.10,
		MaxInputTokens:      8191,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{1536},
		MaxBatchSize:        2048,
		MaxTokensPerBatch:   1000000,
	},
}

var OpenAIImageGenerationModels = map[ModelID]ImageGenerationModel{
	DALLE2: {
		ID:       DALLE2,
		Name:     "DALL-E 2",
		Provider: ProviderOpenAI,
		APIModel: "dall-e-2",
		Pricing: map[string]map[string]float64{
			"256x256": {
				"standard": 0.016,
			},
			"512x512": {
				"standard": 0.018,
			},
			"1024x1024": {
				"standard": 0.02,
			},
		},
		MaxPromptTokens:    1000,
		SupportedSizes:     []string{"256x256", "512x512", "1024x1024"},
		DefaultSize:        "1024x1024",
		SupportedQualities: []string{"standard"},
		DefaultQuality:     "standard",
	},
	DALLE3: {
		ID:       DALLE3,
		Name:     "DALL-E 3",
		Provider: ProviderOpenAI,
		APIModel: "dall-e-3",
		Pricing: map[string]map[string]float64{
			"1024x1024": {
				"standard": 0.04,
				"hd":       0.08,
			},
			"1024x1792": {
				"standard": 0.08,
				"hd":       0.12,
			},
			"1792x1024": {
				"standard": 0.08,
				"hd":       0.12,
			},
		},
		MaxPromptTokens:    4000,
		SupportedSizes:     []string{"1024x1024", "1024x1792", "1792x1024"},
		DefaultSize:        "1024x1024",
		SupportedQualities: []string{"standard", "hd"},
		DefaultQuality:     "standard",
	},
	GPTImage1: {
		ID:       GPTImage1,
		Name:     "GPT Image 1",
		Provider: ProviderOpenAI,
		APIModel: "gpt-image-1",
		Pricing: map[string]map[string]float64{
			"1024x1024": {
				"low":    0.011,
				"medium": 0.042,
				"high":   0.167,
			},
			"1024x1536": {
				"low":    0.016,
				"medium": 0.063,
				"high":   0.25,
			},
			"1536x1024": {
				"low":    0.016,
				"medium": 0.063,
				"high":   0.25,
			},
		},
		MaxPromptTokens:    4000,
		SupportedSizes:     []string{"1024x1024", "1024x1536", "1536x1024"},
		DefaultSize:        "1024x1024",
		SupportedQualities: []string{"low", "medium", "high"},
		DefaultQuality:     "medium",
	},
}
