// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package azure

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	GPT4OMiniTranscribe string = "gpt-4o-mini-transcribe"
	GPT4OTcrb           string = "gpt-4o-tcrb"
	GPT4OTranscribe     string = "gpt-4o-transcribe"
	GPTRealtimeWhisper  string = "gpt-realtime-whisper"
	GPT4OMnTrscb1215    string = "gpt4o-mn-trscb-1215"
	SpeechToTextWhisper string = "speech-to-text-whisper"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	GPT4OMiniTranscribe: {
		ID:                GPT4OMiniTranscribe,
		Name:              "gpt-4o-mini-transcribe",
		Provider:          "azure-speech",
		APIModel:          "gpt-4o-mini-transcribe",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      5,
		SupportsStreaming: true,
	},
	GPT4OTcrb: {
		ID:                GPT4OTcrb,
		Name:              "gpt-4o-transcribe",
		Provider:          "azure-speech",
		APIModel:          "gpt-4o-tcrb",
		Currency:          "USD",
		CostPer1MIn:       2.5,
		CostPer1MOut:      10,
		SupportsStreaming: true,
	},
	GPT4OTranscribe: {
		ID:                GPT4OTranscribe,
		Name:              "gpt-4o-transcribe",
		Provider:          "azure-speech",
		APIModel:          "gpt-4o-transcribe",
		Currency:          "USD",
		CostPer1MIn:       2.5,
		CostPer1MOut:      10,
		SupportsStreaming: true,
	},
	GPTRealtimeWhisper: {
		ID:           GPTRealtimeWhisper,
		Name:         "OpenAI gpt-realtime-whisper",
		Provider:     "azure-speech",
		APIModel:     "gpt-realtime-whisper",
		Currency:     "USD",
		CostPer1MOut: 0.017,
	},
	GPT4OMnTrscb1215: {
		ID:                GPT4OMnTrscb1215,
		Name:              "gpt-4o-mini-transcribe",
		Provider:          "azure-speech",
		APIModel:          "gpt4o-mn-trscb-1215",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      5,
		SupportsStreaming: true,
	},
	SpeechToTextWhisper: {
		ID:       SpeechToTextWhisper,
		Name:     "whisper",
		Provider: "azure-speech",
		APIModel: "speech-to-text-whisper",
		Currency: "USD",
	},
}
