// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package google

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	Chirp               string = "chirp"
	STTChirp2           string = "google-cloud-stt-chirp-2"
	STTChirp3           string = "google-cloud-stt-chirp-3"
	CommandAndSearch    string = "command_and_search"
	STTDefault          string = "google-cloud-stt-default"
	LatestLong          string = "latest_long"
	LatestShort         string = "latest_short"
	MedicalConversation string = "medical_conversation"
	MedicalDictation    string = "medical_dictation"
	PhoneCall           string = "phone_call"
	Telephony           string = "telephony"
	Video               string = "video"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	Chirp: {
		ID:          Chirp,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "chirp",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
	STTChirp2: {
		ID:            STTChirp2,
		Name:          "Google Cloud STT Chirp 2",
		Provider:      "google-cloud",
		APIModel:      "chirp_2",
		Currency:      "USD",
		CostPer1MIn:   0.016,
		MaxFileSizeMB: 480,
		SupportedFormats: []string{
			"flac",
			"linear16",
			"mulaw",
			"amr",
			"amr-wb",
			"ogg-opus",
			"speex",
			"webm-opus",
			"mp3",
		},
		SupportedResponseFormats: []string{"json"},
	},
	STTChirp3: {
		ID:            STTChirp3,
		Name:          "Google Cloud STT Chirp 3",
		Provider:      "google-cloud",
		APIModel:      "chirp_3",
		Currency:      "USD",
		CostPer1MIn:   0.016,
		MaxFileSizeMB: 480,
		SupportedFormats: []string{
			"flac",
			"linear16",
			"mulaw",
			"amr",
			"amr-wb",
			"ogg-opus",
			"speex",
			"webm-opus",
			"mp3",
		},
		SupportedResponseFormats: []string{"json"},
	},
	CommandAndSearch: {
		ID:          CommandAndSearch,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "command_and_search",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
	STTDefault: {
		ID:            STTDefault,
		Name:          "Google Cloud STT Default",
		Provider:      "google-cloud",
		APIModel:      "default",
		Currency:      "USD",
		CostPer1MIn:   0.003,
		MaxFileSizeMB: 480,
		SupportedFormats: []string{
			"flac",
			"linear16",
			"mulaw",
			"amr",
			"amr-wb",
			"ogg-opus",
			"speex",
			"webm-opus",
			"mp3",
		},
		SupportedResponseFormats: []string{"json"},
	},
	LatestLong: {
		ID:          LatestLong,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "latest_long",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
	LatestShort: {
		ID:          LatestShort,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "latest_short",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
	MedicalConversation: {
		ID:       MedicalConversation,
		Name:     "",
		Provider: "google-cloud",
		APIModel: "medical_conversation",
		Currency: "USD",
	},
	MedicalDictation: {
		ID:       MedicalDictation,
		Name:     "",
		Provider: "google-cloud",
		APIModel: "medical_dictation",
		Currency: "USD",
	},
	PhoneCall: {
		ID:          PhoneCall,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "phone_call",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
	Telephony: {
		ID:       Telephony,
		Name:     "",
		Provider: "google-cloud",
		APIModel: "telephony",
		Currency: "USD",
	},
	Video: {
		ID:          Video,
		Name:        "",
		Provider:    "google-cloud",
		APIModel:    "video",
		Currency:    "USD",
		CostPer1MIn: 0.003,
	},
}
