package openrouter

import (
	"github.com/joakimcarlsson/ai/llm"
)

// OpenRouter provider identifier and routed model IDs for this registry.
const (
	GPT41             string = "openrouter.gpt-4.1"
	GPT41Mini         string = "openrouter.gpt-4.1-mini"
	GPT41Nano         string = "openrouter.gpt-4.1-nano"
	GPT4o             string = "openrouter.gpt-4o"
	GPT4oMini         string = "openrouter.gpt-4o-mini"
	O1                string = "openrouter.o1"
	O1Pro             string = "openrouter.o1-pro"
	O3                string = "openrouter.o3"
	O3Pro             string = "openrouter.o3-pro"
	O3Mini            string = "openrouter.o3-mini"
	O4Mini            string = "openrouter.o4-mini"
	GPT52             string = "openrouter.gpt-5.2"
	GPT52Pro          string = "openrouter.gpt-5.2-pro"
	GPT52Instant      string = "openrouter.gpt-5.2-instant"
	Gemini3Pro        string = "openrouter.gemini-3-pro"
	Gemini31Pro       string = "openrouter.gemini-3.1-pro"
	Gemini25Flash     string = "openrouter.gemini-2.5-flash"
	Gemini25FlashLite string = "openrouter.gemini-2.5-flash-lite"
	Gemini25          string = "openrouter.gemini-2.5"
	Claude3Haiku      string = "openrouter.claude-3-haiku"
	Claude45Opus      string = "openrouter.claude-4.5-opus"
	Claude46Opus      string = "openrouter.claude-4.6-opus"
	Claude46Sonnet    string = "openrouter.claude-4.6-sonnet"
	Claude47Opus      string = "openrouter.claude-4.7-opus"
	Claude48Opus      string = "openrouter.claude-4.8-opus"
	Claude5Sonnet     string = "openrouter.claude-5-sonnet"
	GPT52Codex        string = "openrouter.gpt-5.2-codex"
	MistralLarge3     string = "openrouter.mistral-large-3"
	MistralMedium3    string = "openrouter.mistral-medium-3"
	Llama4Maverick    string = "openrouter.llama-4-maverick"
	Llama4Scout       string = "openrouter.llama-4-scout"
	Llama3170B        string = "openrouter.llama-3.1-70b"
	Llama318B         string = "openrouter.llama-3.1-8b"
	DeepSeekV32       string = "openrouter.deepseek-v3.2"
	DeepSeekV32Think  string = "openrouter.deepseek-v3.2-thinking"
	DeepSeekR1        string = "openrouter.deepseek-r1"
	DeepSeekR1Distill string = "openrouter.deepseek-r1-distill"
	Qwen3Max          string = "openrouter.qwen-3-max"
	Qwen3Coder480B    string = "openrouter.qwen-3-coder-480b"
	Qwen3CoderPlus    string = "openrouter.qwen-3-coder-plus"
	CommandRPlus      string = "openrouter.command-r-plus"
	CommandR          string = "openrouter.command-r"
	Sonar             string = "openrouter.sonar"
	SonarPro          string = "openrouter.sonar-pro"
	SonarReasoningPro string = "openrouter.sonar-reasoning-pro"
	SonarDeepResearch string = "openrouter.sonar-deep-research"
	GPTOss20b         string = "openrouter.gpt-oss-20b"
	GPTOss120b        string = "openrouter.gpt-oss-120b"
	Grok45            string = "openrouter.grok-4.5"
	Grok43            string = "openrouter.grok-4.3"
	Gemini35Flash     string = "openrouter.gemini-3.5-flash"
	Gemini36Flash     string = "openrouter.gemini-3.6-flash"
	Claude5Opus       string = "openrouter.claude-5-opus"
	Claude5Fable      string = "openrouter.claude-5-fable"
	GPT56Sol          string = "openrouter.gpt-5.6-sol"
	GPT56Terra        string = "openrouter.gpt-5.6-terra"
	GPT56Luna         string = "openrouter.gpt-5.6-luna"
)

// Models maps OpenRouter model IDs to their configurations.
//
// Pricing source: https://openrouter.ai/api/v1/models, for both slugs and
// rates. The rates are recorded literally here. OpenRouter passes the upstream
// provider's price through for most routed models, but the figure below is
// OpenRouter's own and is not derived from another catalog.
// Fetched: 2026-07-26.
var Models = map[string]llm.Model{
	GPT41: {
		ID:                    GPT41,
		Name:                  "OpenRouter – GPT 4.1",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-4.1",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsStructuredOut: true,
	},
	GPT41Mini: {
		ID:                    GPT41Mini,
		Name:                  "OpenRouter – GPT 4.1 mini",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-4.1-mini",
		CostPer1MIn:           0.4,
		CostPer1MOut:          1.6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsStructuredOut: true,
	},
	GPT41Nano: {
		ID:                    GPT41Nano,
		Name:                  "OpenRouter – GPT 4.1 nano",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-4.1-nano",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.025,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsStructuredOut: true,
	},
	GPT4o: {
		ID:                    GPT4o,
		Name:                  "OpenRouter – GPT 4o",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-4o",
		CostPer1MIn:           2.5,
		CostPer1MOut:          10,
		CostPer1MInCached:     1.25,
		ContextWindow:         128000,
		DefaultMaxTokens:      4096,
		SupportsStructuredOut: true,
	},
	GPT4oMini: {
		ID:                    GPT4oMini,
		Name:                  "OpenRouter – GPT 4o mini",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-4o-mini",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.075,
		ContextWindow:         128000,
		SupportsStructuredOut: true,
	},
	O1: {
		ID:                    O1,
		Name:                  "OpenRouter – O1",
		Provider:              "openrouter",
		APIModel:              "openai/o1",
		CostPer1MIn:           15,
		CostPer1MOut:          60,
		CostPer1MInCached:     7.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O1Pro: {
		ID:                    O1Pro,
		Name:                  "OpenRouter – o1 pro",
		Provider:              "openrouter",
		APIModel:              "openai/o1-pro",
		CostPer1MIn:           150,
		CostPer1MOut:          600,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O3: {
		ID:                    O3,
		Name:                  "OpenRouter – o3",
		Provider:              "openrouter",
		APIModel:              "openai/o3",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O3Mini: {
		ID:                    O3Mini,
		Name:                  "OpenRouter – o3 mini",
		Provider:              "openrouter",
		APIModel:              "openai/o3-mini-high",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.55,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O4Mini: {
		ID:                    O4Mini,
		Name:                  "OpenRouter – o4 mini",
		Provider:              "openrouter",
		APIModel:              "openai/o4-mini-high",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.275,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O3Pro: {
		ID:                    O3Pro,
		Name:                  "OpenRouter – o3 pro",
		Provider:              "openrouter",
		APIModel:              "openai/o3-pro",
		CostPer1MIn:           20,
		CostPer1MOut:          80,
		CostPer1MInCached:     5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPT52: {
		ID:                    GPT52,
		Name:                  "OpenRouter – GPT-5.2",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.2",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPT52Pro: {
		ID:                    GPT52Pro,
		Name:                  "OpenRouter – GPT-5.2 Pro",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.2-pro",
		CostPer1MIn:           21,
		CostPer1MOut:          168,
		CostPer1MInCached:     2.1,
		ContextWindow:         400000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPT52Instant: {
		ID:                    GPT52Instant,
		Name:                  "OpenRouter – GPT-5.2 Instant",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.2-chat-latest",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         128000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Gemini25Flash: {
		ID:                    Gemini25Flash,
		Name:                  "OpenRouter – Gemini 2.5 Flash",
		Provider:              "openrouter",
		APIModel:              "google/gemini-2.5-flash",
		CostPer1MIn:           0.3,
		CostPer1MOut:          2.5,
		CostPer1MInCached:     0.03,
		ContextWindow:         1000000,
		DefaultMaxTokens:      50000,
		SupportsStructuredOut: true,
	},
	Gemini25: {
		ID:                    Gemini25,
		Name:                  "OpenRouter – Gemini 2.5 Pro",
		Provider:              "openrouter",
		APIModel:              "google/gemini-2.5-pro",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         2000000,
		DefaultMaxTokens:      64000,
		SupportsStructuredOut: true,
	},
	Gemini3Pro: {
		ID:                    Gemini3Pro,
		Name:                  "OpenRouter – Gemini 3 Pro",
		Provider:              "openrouter",
		APIModel:              "google/gemini-3-pro",
		CostPer1MIn:           2,
		CostPer1MOut:          12,
		CostPer1MInCached:     0.2,
		ContextWindow:         1048576,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Gemini31Pro: {
		ID:                    Gemini31Pro,
		Name:                  "OpenRouter – Gemini 3.1 Pro",
		Provider:              "openrouter",
		APIModel:              "google/gemini-3.1-pro-preview",
		CostPer1MIn:           2,
		CostPer1MOut:          12,
		CostPer1MInCached:     0.2,
		ContextWindow:         1048576,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Gemini25FlashLite: {
		ID:                    Gemini25FlashLite,
		Name:                  "OpenRouter – Gemini 2.5 Flash Lite",
		Provider:              "openrouter",
		APIModel:              "google/gemini-2.5-flash-lite",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.01,
		ContextWindow:         1000000,
		DefaultMaxTokens:      50000,
		SupportsStructuredOut: true,
	},
	Claude3Haiku: {
		ID:                 Claude3Haiku,
		Name:               "OpenRouter – Claude 3 Haiku",
		Provider:           "openrouter",
		APIModel:           "anthropic/claude-3-haiku",
		CostPer1MIn:        0.25,
		CostPer1MOut:       1.25,
		CostPer1MInCached:  0.3,
		CostPer1MOutCached: 0.03,
		ContextWindow:      200000,
		DefaultMaxTokens:   4096,
	},
	Claude45Opus: {
		ID:                    Claude45Opus,
		Name:                  "OpenRouter – Claude 4.5 Opus",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-opus-4-5-20251101",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Claude46Opus: {
		ID:                    Claude46Opus,
		Name:                  "OpenRouter – Claude 4.6 Opus",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-opus-4-6-20260205",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Claude47Opus: {
		ID:                    Claude47Opus,
		Name:                  "OpenRouter – Claude 4.7 Opus",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-opus-4.7",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Claude48Opus: {
		ID:                    Claude48Opus,
		Name:                  "OpenRouter – Claude 4.8 Opus",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-opus-4.8",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Claude46Sonnet: {
		ID:                    Claude46Sonnet,
		Name:                  "OpenRouter – Claude 4.6 Sonnet",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-sonnet-4-6",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.3,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Claude5Sonnet: {
		ID:                    Claude5Sonnet,
		Name:                  "OpenRouter – Claude Sonnet 5",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-sonnet-5",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.3,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPT52Codex: {
		ID:                    GPT52Codex,
		Name:                  "OpenRouter – GPT-5.2 Codex",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.2-codex",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	MistralLarge3: {
		ID:                    MistralLarge3,
		Name:                  "OpenRouter – Mistral Large 3",
		Provider:              "openrouter",
		APIModel:              "mistralai/mistral-large-3-25-12",
		CostPer1MIn:           0.5,
		CostPer1MOut:          1.5,
		ContextWindow:         262144,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	MistralMedium3: {
		ID:                    MistralMedium3,
		Name:                  "OpenRouter – Mistral Medium 3.1",
		Provider:              "openrouter",
		APIModel:              "mistralai/mistral-medium-3-1-25-08",
		CostPer1MIn:           0.4,
		CostPer1MOut:          2,
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	Llama4Maverick: {
		ID:               Llama4Maverick,
		Name:             "OpenRouter – Llama 4 Maverick",
		Provider:         "openrouter",
		APIModel:         "meta-llama/llama-4-maverick",
		CostPer1MIn:      0.15,
		CostPer1MOut:     0.6,
		ContextWindow:    1048576,
		DefaultMaxTokens: 50000,
	},
	Llama4Scout: {
		ID:               Llama4Scout,
		Name:             "OpenRouter – Llama 4 Scout",
		Provider:         "openrouter",
		APIModel:         "meta-llama/llama-4-scout",
		CostPer1MIn:      0.08,
		CostPer1MOut:     0.3,
		ContextWindow:    327680,
		DefaultMaxTokens: 50000,
	},
	Llama3170B: {
		ID:               Llama3170B,
		Name:             "OpenRouter – Llama 3.1 70B",
		Provider:         "openrouter",
		APIModel:         "meta-llama/Meta-Llama-3.1-70B-Instruct",
		CostPer1MIn:      0.4,
		CostPer1MOut:     0.4,
		ContextWindow:    131072,
		DefaultMaxTokens: 4096,
	},
	Llama318B: {
		ID:               Llama318B,
		Name:             "OpenRouter – Llama 3.1 8B",
		Provider:         "openrouter",
		APIModel:         "meta-llama/Meta-Llama-3.1-8B-Instruct",
		CostPer1MIn:      0.02,
		CostPer1MOut:     0.03,
		ContextWindow:    131072,
		DefaultMaxTokens: 4096,
	},
	DeepSeekV32: {
		ID:                DeepSeekV32,
		Name:              "OpenRouter – DeepSeek V3.2",
		Provider:          "openrouter",
		APIModel:          "deepseek/deepseek-v3.2",
		CostPer1MIn:       0.28,
		CostPer1MOut:      0.42,
		CostPer1MInCached: 0.028,
		ContextWindow:     128000,
		DefaultMaxTokens:  8000,
	},
	DeepSeekV32Think: {
		ID:                DeepSeekV32Think,
		Name:              "OpenRouter – DeepSeek V3.2 Thinking",
		Provider:          "openrouter",
		APIModel:          "deepseek/deepseek-v3.2-thinking",
		CostPer1MIn:       0.28,
		CostPer1MOut:      0.42,
		CostPer1MInCached: 0.028,
		ContextWindow:     128000,
		DefaultMaxTokens:  64000,
		CanReason:         true,
	},
	DeepSeekR1: {
		ID:               DeepSeekR1,
		Name:             "OpenRouter – DeepSeek R1",
		Provider:         "openrouter",
		APIModel:         "deepseek/deepseek-r1",
		CostPer1MIn:      0.14,
		CostPer1MOut:     0.14,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	DeepSeekR1Distill: {
		ID:               DeepSeekR1Distill,
		Name:             "OpenRouter – DeepSeek R1 Distill",
		Provider:         "openrouter",
		APIModel:         "deepseek/deepseek-r1-distill-llama-70b",
		CostPer1MIn:      0.14,
		CostPer1MOut:     0.28,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	Qwen3Max: {
		ID:               Qwen3Max,
		Name:             "OpenRouter – Qwen 3 Max",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-3-max",
		CostPer1MIn:      1.2,
		CostPer1MOut:     6,
		ContextWindow:    256000,
		DefaultMaxTokens: 50000,
	},
	Qwen3Coder480B: {
		ID:               Qwen3Coder480B,
		Name:             "OpenRouter – Qwen 3 Coder 480B",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-3-coder-480b",
		CostPer1MIn:      1.5,
		CostPer1MOut:     7.5,
		ContextWindow:    256000,
		DefaultMaxTokens: 50000,
	},
	Qwen3CoderPlus: {
		ID:               Qwen3CoderPlus,
		Name:             "OpenRouter – Qwen 3 Coder Plus",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-3-coder-plus",
		CostPer1MIn:      1,
		CostPer1MOut:     5,
		ContextWindow:    1000000,
		DefaultMaxTokens: 50000,
	},
	CommandRPlus: {
		ID:               CommandRPlus,
		Name:             "OpenRouter – Command R+",
		Provider:         "openrouter",
		APIModel:         "cohere/command-r-plus",
		CostPer1MIn:      2.5,
		CostPer1MOut:     10,
		ContextWindow:    128000,
		DefaultMaxTokens: 4096,
	},
	CommandR: {
		ID:               CommandR,
		Name:             "OpenRouter – Command R",
		Provider:         "openrouter",
		APIModel:         "cohere/command-r",
		CostPer1MIn:      0.15,
		CostPer1MOut:     0.6,
		ContextWindow:    128000,
		DefaultMaxTokens: 4096,
	},
	Sonar: {
		ID:               Sonar,
		Name:             "OpenRouter – Sonar",
		Provider:         "openrouter",
		APIModel:         "perplexity/sonar",
		CostPer1MIn:      1,
		CostPer1MOut:     1,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
	},
	SonarPro: {
		ID:               SonarPro,
		Name:             "OpenRouter – Sonar Pro",
		Provider:         "openrouter",
		APIModel:         "perplexity/sonar-pro",
		CostPer1MIn:      3,
		CostPer1MOut:     15,
		ContextWindow:    200000,
		DefaultMaxTokens: 50000,
	},
	SonarReasoningPro: {
		ID:               SonarReasoningPro,
		Name:             "OpenRouter – Sonar Reasoning Pro",
		Provider:         "openrouter",
		APIModel:         "perplexity/sonar-reasoning-pro",
		CostPer1MIn:      2,
		CostPer1MOut:     8,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	SonarDeepResearch: {
		ID:               SonarDeepResearch,
		Name:             "OpenRouter – Sonar Deep Research",
		Provider:         "openrouter",
		APIModel:         "perplexity/sonar-deep-research",
		CostPer1MIn:      2,
		CostPer1MOut:     8,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	GPTOss20b: {
		ID:                    GPTOss20b,
		Name:                  "OpenRouter – GPT-OSS 20B",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-oss-20b",
		CostPer1MIn:           0.029,
		CostPer1MOut:          0.14,
		ContextWindow:         131072,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOss120b: {
		ID:                    GPTOss120b,
		Name:                  "OpenRouter – GPT-OSS 120B",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-oss-120b",
		CostPer1MIn:           0.036,
		CostPer1MOut:          0.18,
		ContextWindow:         131072,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Grok45: {
		ID:                    Grok45,
		Name:                  "OpenRouter – Grok 4.5",
		Provider:              "openrouter",
		APIModel:              "x-ai/grok-4.5",
		CostPer1MIn:           2,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.5,
		ContextWindow:         500000,
		DefaultMaxTokens:      32000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok43: {
		ID:                    Grok43,
		Name:                  "OpenRouter – Grok 4.3",
		Provider:              "openrouter",
		APIModel:              "x-ai/grok-4.3",
		CostPer1MIn:           1.25,
		CostPer1MOut:          2.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      32000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Gemini35Flash: {
		ID:                    Gemini35Flash,
		Name:                  "OpenRouter – Gemini 3.5 Flash",
		Provider:              "openrouter",
		APIModel:              "google/gemini-3.5-flash",
		CostPer1MIn:           1.5,
		CostPer1MOut:          9,
		CostPer1MInCached:     0.15,
		ContextWindow:         1048576,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Gemini36Flash: {
		ID:                    Gemini36Flash,
		Name:                  "OpenRouter – Gemini 3.6 Flash",
		Provider:              "openrouter",
		APIModel:              "google/gemini-3.6-flash",
		CostPer1MIn:           1.5,
		CostPer1MOut:          7.5,
		CostPer1MInCached:     0.15,
		ContextWindow:         1048576,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Opus: {
		ID:                    Claude5Opus,
		Name:                  "OpenRouter – Claude Opus 5",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-opus-5",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Fable: {
		ID:                    Claude5Fable,
		Name:                  "OpenRouter – Claude Fable 5",
		Provider:              "openrouter",
		APIModel:              "anthropic/claude-fable-5",
		CostPer1MIn:           10,
		CostPer1MOut:          50,
		CostPer1MInCached:     12.5,
		CostPer1MOutCached:    1,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Sol: {
		ID:                    GPT56Sol,
		Name:                  "OpenRouter – GPT-5.6 Sol",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.6-sol",
		CostPer1MIn:           5,
		CostPer1MOut:          30,
		CostPer1MInCached:     0.5,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Terra: {
		ID:                    GPT56Terra,
		Name:                  "OpenRouter – GPT-5.6 Terra",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.6-terra",
		CostPer1MIn:           2.5,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.25,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Luna: {
		ID:                    GPT56Luna,
		Name:                  "OpenRouter – GPT-5.6 Luna",
		Provider:              "openrouter",
		APIModel:              "openai/gpt-5.6-luna",
		CostPer1MIn:           1,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
