// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package cerebras

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Gemma431B  string = "cerebras.gemma-4-31b"
	GPTOss120B string = "cerebras.gpt-oss-120b"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Gemma431B: {
		ID:                    Gemma431B,
		Name:                  "Gemma 4 31B IT",
		Provider:              "cerebras",
		APIModel:              "gemma-4-31b",
		Currency:              "USD",
		CostPer1MIn:           0.99,
		CostPer1MOut:          1.49,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "Cerebras – GPT-OSS 120B",
		Provider:              "cerebras",
		APIModel:              "gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.35,
		CostPer1MOut:          0.75,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
