// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-12
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// cerebras provider.
//
// models.dev indexes providers rather than serving them, so models it
// stops listing are kept here and reported by the sync instead of
// being deleted. Display names are set when a model is first added and
// carried over from then on.

package cerebras

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Gemma431B  string = "cerebras.gemma-4-31b"
	GPTOss120B string = "cerebras.gpt-oss-120b"
	Llama31_8B string = "cerebras.llama3.1-8b"
	ZaiGLM47   string = "cerebras.zai-glm-4.7"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Gemma431B: {
		ID:                    Gemma431B,
		Name:                  "Gemma 4 31B IT",
		Provider:              "cerebras",
		APIModel:              "gemma-4-31b",
		Currency:              "USD",
		CostPer1MIn:           0.99,
		CostPer1MOut:          1.49,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "Cerebras – GPT-OSS 120B",
		Provider:              "cerebras",
		APIModel:              "gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.35,
		CostPer1MOut:          0.75,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Llama31_8B: {
		ID:                    Llama31_8B,
		Name:                  "Cerebras – Llama 3.1 8B",
		Provider:              "cerebras",
		APIModel:              "llama3.1-8b",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.1,
		ContextWindow:         32768,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	ZaiGLM47: {
		ID:                    ZaiGLM47,
		Name:                  "Z.AI GLM-4.7",
		Provider:              "cerebras",
		APIModel:              "zai-glm-4.7",
		Currency:              "USD",
		CostPer1MIn:           2.25,
		CostPer1MOut:          2.75,
		CostPer1MInCached:     2.25,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
