package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const fixture = `package demo

import (
	"github.com/joakimcarlsson/ai/llm"
)

const (
	GPT41 string = "demo.gpt-4.1"
)

var Models = map[string]llm.Model{
	GPT41: {
		ID:               GPT41,
		Name:             "Demo – GPT 4.1",
		Provider:         "demo",
		APIModel:         "openai/gpt-4.1",
		CostPer1MIn:      2,
		ContextWindow:    1047576,
		DefaultMaxTokens: 20000,
	},
}
`

func writeFixture(t *testing.T) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "models.go")
	if err := os.WriteFile(path, []byte(fixture), 0o600); err != nil {
		t.Fatalf("writing fixture: %v", err)
	}
	return path
}

func demoTarget() target {
	return target{
		source:     "demo",
		provider:   "demo",
		kind:       kindChat,
		path:       "demo/models.go",
		pkg:        "demo",
		importPath: "github.com/joakimcarlsson/ai/llm",
		typeExpr:   "llm.Model",
		idPrefix:   "demo.",
		order:      chatFields,
		defaults:   map[string]string{"Provider": `"demo"`},
	}
}

func TestReadCatalogKeysByAPIModel(t *testing.T) {
	cat, err := readCatalog(writeFixture(t))
	if err != nil {
		t.Fatalf("readCatalog: %v", err)
	}

	e, ok := cat.entries["openai/gpt-4.1"]
	if !ok {
		t.Fatalf("entry not found, got %v", cat.entries)
	}
	if e.constName != "GPT41" {
		t.Errorf("constName = %q, want GPT41", e.constName)
	}
	if e.constVal != "demo.gpt-4.1" {
		t.Errorf("constVal = %q, want demo.gpt-4.1", e.constVal)
	}
	if got := e.fields["ContextWindow"]; got != "1047576" {
		t.Errorf("ContextWindow = %q, want 1047576", got)
	}
}

func TestReadCatalogMissingFile(t *testing.T) {
	cat, err := readCatalog(filepath.Join(t.TempDir(), "models.go"))
	if err != nil {
		t.Fatalf("readCatalog: %v", err)
	}
	if len(cat.entries) != 0 {
		t.Errorf("entries = %d, want 0", len(cat.entries))
	}
}

func TestSyncTargetPreservesNamesAndUnknownFields(t *testing.T) {
	cat, err := readCatalog(writeFixture(t))
	if err != nil {
		t.Fatalf("readCatalog: %v", err)
	}

	fetched := []model{
		{
			apiModel: "openai/gpt-4.1",
			fields: map[string]string{
				"Name":        `"Demo – GPT-4.1"`,
				"Provider":    `"demo"`,
				"APIModel":    `"openai/gpt-4.1"`,
				"Currency":    `"USD"`,
				"CostPer1MIn": "3",
			},
		},
		{
			apiModel: "openai/gpt-5",
			fields: map[string]string{
				"Provider": `"demo"`,
				"APIModel": `"openai/gpt-5"`,
				"Currency": `"USD"`,
			},
			seed: map[string]string{"Name": `"Demo – GPT-5"`},
		},
	}

	src, res, err := syncTarget(demoTarget(), fetched, cat, "2026-01-01")
	if err != nil {
		t.Fatalf("syncTarget: %v", err)
	}

	if res.updated != 1 || len(res.added) != 1 || len(res.removed) != 0 {
		t.Fatalf(
			"updated=%d added=%v removed=%v",
			res.updated,
			res.added,
			res.removed,
		)
	}

	for _, want := range []string{
		"// Code generated by cmd/modelsync. DO NOT EDIT.",
		`GPT41 string = "demo.gpt-4.1"`,
		`GPT5  string = "demo.gpt-5"`,
		"CostPer1MIn:      3,",
		"DefaultMaxTokens: 20000,",
		`Currency:         "USD",`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q:\n%s", want, src)
		}
	}
}

func TestSyncTargetReportsRemovals(t *testing.T) {
	cat, err := readCatalog(writeFixture(t))
	if err != nil {
		t.Fatalf("readCatalog: %v", err)
	}

	fetched := []model{{
		apiModel: "openai/gpt-5",
		fields: map[string]string{
			"Name":     `"Demo – GPT-5"`,
			"Provider": `"demo"`,
			"APIModel": `"openai/gpt-5"`,
			"Currency": `"USD"`,
		},
	}}

	_, res, err := syncTarget(demoTarget(), fetched, cat, "2026-01-01")
	if err != nil {
		t.Fatalf("syncTarget: %v", err)
	}
	if len(res.removed) != 1 ||
		!strings.Contains(res.removed[0], "openai/gpt-4.1") {
		t.Errorf("removed = %v, want the stale gpt-4.1 entry", res.removed)
	}
}

func TestSyncTargetMatchesDatedSnapshots(t *testing.T) {
	path := filepath.Join(t.TempDir(), "models.go")
	dated := strings.ReplaceAll(
		fixture,
		`"openai/gpt-4.1"`,
		`"openai/gpt-4.1-20250101"`,
	)
	if err := os.WriteFile(path, []byte(dated), 0o600); err != nil {
		t.Fatalf("writing fixture: %v", err)
	}

	cat, err := readCatalog(path)
	if err != nil {
		t.Fatalf("readCatalog: %v", err)
	}

	fetched := []model{{
		apiModel: "openai/gpt-4.1",
		fields: map[string]string{
			"Name":     `"Demo – GPT-4.1"`,
			"Provider": `"demo"`,
			"APIModel": `"openai/gpt-4.1"`,
			"Currency": `"USD"`,
		},
	}}

	src, res, err := syncTarget(demoTarget(), fetched, cat, "2026-01-01")
	if err != nil {
		t.Fatalf("syncTarget: %v", err)
	}
	if res.updated != 1 || len(res.added) != 0 {
		t.Fatalf("updated=%d added=%v, want the dated entry updated in place",
			res.updated, res.added)
	}
	if !strings.Contains(src, `GPT41 string = "demo.gpt-4.1"`) {
		t.Errorf("constant not preserved:\n%s", src)
	}
	if !strings.Contains(src, "DefaultMaxTokens: 20000,") {
		t.Errorf("preserved field lost:\n%s", src)
	}
}

func TestCheckTargetsRejectsSharedPaths(t *testing.T) {
	err := checkTargets([]target{
		{source: "a", kind: kindChat, path: "llm/x/models.go"},
		{source: "b", kind: kindChat, path: "llm/x/models.go"},
	})
	if err == nil {
		t.Fatal("want an error when two entries write the same catalog")
	}
}

func TestRegisteredCatalogsAreUnique(t *testing.T) {
	if err := checkTargets(targets); err != nil {
		t.Fatal(err)
	}
}

func TestNamingDerivesUniqueIdentifiers(t *testing.T) {
	taken := map[string]bool{"O3Mini": true}
	if got := uniqueConstName("openai/o3-mini", taken); got != "OpenaiO3Mini" {
		t.Errorf("uniqueConstName = %q, want OpenaiO3Mini", got)
	}

	takenIDs := map[string]bool{"openrouter.o3-mini": true}
	got := uniqueID("openai/o3-mini", "openrouter.", false, takenIDs)
	if got != "openrouter.openai-o3-mini" {
		t.Errorf("uniqueID = %q, want openrouter.openai-o3-mini", got)
	}

	if got := catalogID(
		"anthropic/claude-opus-5:batch",
	); got != "claude-opus-5-batch" {
		t.Errorf("catalogID = %q, want claude-opus-5-batch", got)
	}
	if got := pascal("gpt-4.1-mini"); got != "GPT41Mini" {
		t.Errorf("pascal = %q, want GPT41Mini", got)
	}
}

func TestMegabytesReadsPublishedSizes(t *testing.T) {
	for in, want := range map[string]int64{
		"25MB":  25,
		"20 MB": 20,
		"2 GB":  2048,
		"":      0,
		"large": 0,
	} {
		if got := megabytes(in); got != want {
			t.Errorf("megabytes(%q) = %d, want %d", in, got, want)
		}
	}
}

func TestDedupeKeepsTheFirstListingOfAModelID(t *testing.T) {
	sourced := []apiModel{
		{ID: "one", Name: "First", Attrs: map[string]string{"api_id": "dup"}},
		{ID: "two", Name: "Second", Attrs: map[string]string{"api_id": "dup"}},
		{ID: "three", Name: "Other", Attrs: map[string]string{"api_id": "own"}},
	}

	fetched, duplicates := dedupe(demoTarget(), sourced)

	if duplicates != 1 {
		t.Errorf("duplicates = %d, want 1", duplicates)
	}
	if len(fetched) != 2 {
		t.Fatalf("fetched = %d models, want 2", len(fetched))
	}
	if fetched[0].seed["Name"] != `"First"` {
		t.Errorf("kept %q, want the first listing", fetched[0].seed["Name"])
	}
}
