package main

import (
	"fmt"
	"go/format"
	"strings"
)

// alwaysWrite are the fields written even when they hold a zero value, so an
// entry always states what it is and what currency it is priced in.
var alwaysWrite = map[string]bool{
	"ID":       true,
	"Name":     true,
	"Provider": true,
	"APIModel": true,
	"Currency": true,
}

// render assembles a complete models.go: the generated-file banner, the ID
// constants and the Models map, in API-model order for a stable diff.
func render(t target, entries []*entry, date string) (string, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by cmd/modelsync. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Source: %s\n", t.source)
	fmt.Fprintf(&b, "// Generated: %s\n", date)
	if len(t.doc) > 0 {
		fmt.Fprintf(&b, "//\n")
		for _, line := range t.doc {
			if line == "" {
				fmt.Fprintf(&b, "//\n")
				continue
			}
			fmt.Fprintf(&b, "// %s\n", line)
		}
	}
	fmt.Fprintf(&b, "\npackage %s\n\n", t.pkg)
	fmt.Fprintf(&b, "import (\n\t%q\n)\n\n", t.importPath)

	fmt.Fprintf(&b, "// Model IDs served by this catalog.\nconst (\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%s string = %q\n", e.constName, e.constVal)
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(
		&b,
		"// Models maps model IDs to their configurations.\nvar Models = map[string]%s{\n",
		t.typeExpr,
	)
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%s: {\n", e.constName)
		for _, field := range t.order {
			val, ok := e.fields[field]
			if !ok || val == "" {
				continue
			}
			if !alwaysWrite[field] && isZeroLiteral(val) {
				continue
			}
			fmt.Fprintf(&b, "\t\t%s: %s,\n", field, val)
		}
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting %s: %w", t.path, err)
	}
	return string(src), nil
}

func isZeroLiteral(val string) bool {
	switch strings.TrimSpace(val) {
	case "0", "0.0", "false", `""`, "nil":
		return true
	}
	return false
}
