// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package cohere

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	EmbedEnLightV3    string = "embed-english-light-v3.0"
	EmbedEnV3         string = "embed-english-v3.0"
	EmbedMultiLightV3 string = "embed-multilingual-light-v3.0"
	EmbedMultiV3      string = "embed-multilingual-v3.0"
	EmbedV4           string = "embed-v4.0"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	EmbedEnLightV3: {
		ID:                  EmbedEnLightV3,
		Name:                "Cohere Embed English Light v3.0",
		Provider:            "cohere",
		APIModel:            "embed-english-light-v3.0",
		Currency:            "USD",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      512,
		EmbeddingDims:       384,
		SupportedDimensions: []int{384},
		MaxBatchSize:        96,
	},
	EmbedEnV3: {
		ID:                  EmbedEnV3,
		Name:                "Cohere Embed English v3.0",
		Provider:            "cohere",
		APIModel:            "embed-english-v3.0",
		Currency:            "USD",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      512,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        96,
	},
	EmbedMultiLightV3: {
		ID:                  EmbedMultiLightV3,
		Name:                "Cohere Embed Multilingual Light v3.0",
		Provider:            "cohere",
		APIModel:            "embed-multilingual-light-v3.0",
		Currency:            "USD",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      512,
		EmbeddingDims:       384,
		SupportedDimensions: []int{384},
		MaxBatchSize:        96,
	},
	EmbedMultiV3: {
		ID:                  EmbedMultiV3,
		Name:                "Cohere Embed Multilingual v3.0",
		Provider:            "cohere",
		APIModel:            "embed-multilingual-v3.0",
		Currency:            "USD",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      512,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        96,
	},
	EmbedV4: {
		ID:                  EmbedV4,
		Name:                "Cohere Embed v4.0",
		Provider:            "cohere",
		APIModel:            "embed-v4.0",
		Currency:            "USD",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      128000,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{256, 512, 1024, 1536},
		MaxBatchSize:        96,
	},
}
