// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package assemblyai

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	MedicalV1                 string = "medical-v1"
	Universal2                string = "universal-2"
	Universal35Pro            string = "universal-3-5-pro"
	UniversalStreamingEnglish string = "universal-streaming-english"
	UniversalStreamingMulti   string = "universal-streaming-multilingual"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	MedicalV1: {
		ID:          MedicalV1,
		Name:        "Medical Mode",
		Provider:    "assemblyai",
		APIModel:    "medical-v1",
		Currency:    "USD",
		CostPer1MIn: 0.0025,
	},
	Universal2: {
		ID:            Universal2,
		Name:          "AssemblyAI Universal-2",
		Provider:      "assemblyai",
		APIModel:      "universal-2",
		Currency:      "USD",
		CostPer1MIn:   0.0025,
		MaxFileSizeMB: 5120,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
		},
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsDiarization:    true,
		SupportsTranslation:    true,
		SupportedResponseFormats: []string{
			"json",
			"text",
			"srt",
			"vtt",
		},
	},
	Universal35Pro: {
		ID:                     Universal35Pro,
		Name:                   "Universal-3.5 Pro",
		Provider:               "assemblyai",
		APIModel:               "universal-3-5-pro",
		Currency:               "USD",
		CostPer1MIn:            0.0035,
		MaxFileSizeMB:          5120,
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsDiarization:    true,
		SupportsTranslation:    true,
	},
	UniversalStreamingEnglish: {
		ID:                       UniversalStreamingEnglish,
		Name:                     "AssemblyAI Universal-Streaming English",
		Provider:                 "assemblyai",
		APIModel:                 "universal-streaming-english",
		Currency:                 "USD",
		CostPer1MIn:              0.0025,
		SupportedFormats:         []string{"pcm_s16le", "pcm_mulaw"},
		SupportsDiarization:      true,
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
	UniversalStreamingMulti: {
		ID:                       UniversalStreamingMulti,
		Name:                     "AssemblyAI Universal-Streaming Multilingual",
		Provider:                 "assemblyai",
		APIModel:                 "universal-streaming-multilingual",
		Currency:                 "USD",
		CostPer1MIn:              0.0025,
		SupportedFormats:         []string{"pcm_s16le", "pcm_mulaw"},
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
}
