// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MChars is per 1M characters, in the currency the provider
// bills in. Default format and latency are not published and are
// carried over from the previous catalog.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package azure

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	GPT4OMiniTTS       string = "gpt-4o-mini-tts"
	GPT4OMnTTS1215     string = "gpt4o-mn-tts-1215"
	SpeechTextToSpeech string = "speech-text-to-speech"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	GPT4OMiniTTS: {
		ID:                GPT4OMiniTTS,
		Name:              "gpt-4o-mini-tts",
		Provider:          "azure-speech",
		APIModel:          "gpt-4o-mini-tts",
		Currency:          "USD",
		SupportsStreaming: true,
	},
	GPT4OMnTTS1215: {
		ID:                GPT4OMnTTS1215,
		Name:              "gpt-4o-mini-tts",
		Provider:          "azure-speech",
		APIModel:          "gpt4o-mn-tts-1215",
		Currency:          "USD",
		SupportsStreaming: true,
	},
	SpeechTextToSpeech: {
		ID:       SpeechTextToSpeech,
		Name:     "tts",
		Provider: "azure-speech",
		APIModel: "speech-text-to-speech",
		Currency: "USD",
	},
}
