// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://openrouter.ai/api/v1/models?output_modalities=transcription
// Generated: 2026-08-12
//
// OpenRouter prices transcription per audio minute, so CostPer1MIn holds
// the USD per-minute rate rather than a per-token one.
//
// File size limits, timestamp, diarization and translation support are
// not part of the models response and are carried over from the previous
// catalog.

package openrouter

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	Nova3                 string = "openrouter.nova-3"
	FishAudioTranscribe1  string = "openrouter.transcribe-1"
	Chirp3                string = "openrouter.chirp-3"
	MAITranscribe15       string = "openrouter.mai-transcribe-1.5"
	VoxtralMiniTranscribe string = "openrouter.voxtral-mini-transcribe"
	ParakeetTDT06BV3      string = "openrouter.parakeet-tdt-0.6b-v3"
	GPT4oMiniTranscribe   string = "openrouter.gpt-4o-mini-transcribe"
	GPT4oTranscribe       string = "openrouter.gpt-4o-transcribe"
	GPTTranscribe         string = "openrouter.gpt-transcribe"
	Whisper1              string = "openrouter.whisper-1"
	WhisperLargeV3        string = "openrouter.whisper-large-v3"
	WhisperLargeV3Turbo   string = "openrouter.whisper-large-v3-turbo"
	Qwen3ASRFlash         string = "openrouter.qwen3-asr-flash-2026-02-10"
	GrokSTT1              string = "openrouter.grok-stt-1.0"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	Nova3: {
		ID:            Nova3,
		Name:          "OpenRouter – Nova-3",
		Provider:      "openrouter",
		APIModel:      "deepgram/nova-3",
		Currency:      "USD",
		CostPer1MIn:   0.0043,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	FishAudioTranscribe1: {
		ID:            FishAudioTranscribe1,
		Name:          "OpenRouter – Transcribe 1",
		Provider:      "openrouter",
		APIModel:      "fish-audio/transcribe-1",
		Currency:      "USD",
		CostPer1MIn:   0.0001,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	Chirp3: {
		ID:            Chirp3,
		Name:          "OpenRouter – Chirp 3",
		Provider:      "openrouter",
		APIModel:      "google/chirp-3",
		Currency:      "USD",
		CostPer1MIn:   0.016,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	MAITranscribe15: {
		ID:            MAITranscribe15,
		Name:          "OpenRouter – MAI-Transcribe 1.5",
		Provider:      "openrouter",
		APIModel:      "microsoft/mai-transcribe-1.5",
		Currency:      "USD",
		CostPer1MIn:   0.36,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	VoxtralMiniTranscribe: {
		ID:            VoxtralMiniTranscribe,
		Name:          "OpenRouter – Voxtral Mini Transcribe",
		Provider:      "openrouter",
		APIModel:      "mistralai/voxtral-mini-transcribe",
		Currency:      "USD",
		CostPer1MIn:   0.003,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	ParakeetTDT06BV3: {
		ID:            ParakeetTDT06BV3,
		Name:          "OpenRouter – Parakeet TDT 0.6B v3",
		Provider:      "openrouter",
		APIModel:      "nvidia/parakeet-tdt-0.6b-v3",
		Currency:      "USD",
		CostPer1MIn:   0.0015,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4oMiniTranscribe: {
		ID:            GPT4oMiniTranscribe,
		Name:          "OpenRouter – GPT-4o Mini Transcribe",
		Provider:      "openrouter",
		APIModel:      "openai/gpt-4o-mini-transcribe",
		Currency:      "USD",
		CostPer1MIn:   0.000001,
		CostPer1MOut:  0.000005,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4oTranscribe: {
		ID:            GPT4oTranscribe,
		Name:          "OpenRouter – GPT-4o Transcribe",
		Provider:      "openrouter",
		APIModel:      "openai/gpt-4o-transcribe",
		Currency:      "USD",
		CostPer1MIn:   0.000003,
		CostPer1MOut:  0.00001,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPTTranscribe: {
		ID:          GPTTranscribe,
		Name:        "OpenRouter – GPT Transcribe",
		Provider:    "openrouter",
		APIModel:    "openai/gpt-transcribe",
		Currency:    "USD",
		CostPer1MIn: 0.0045,
	},
	Whisper1: {
		ID:            Whisper1,
		Name:          "OpenRouter – Whisper 1",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-1",
		Currency:      "USD",
		CostPer1MIn:   0.006,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	WhisperLargeV3: {
		ID:            WhisperLargeV3,
		Name:          "OpenRouter – Whisper Large V3",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-large-v3",
		Currency:      "USD",
		CostPer1MIn:   0.0015,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	WhisperLargeV3Turbo: {
		ID:            WhisperLargeV3Turbo,
		Name:          "OpenRouter – Whisper Large V3 Turbo",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-large-v3-turbo",
		Currency:      "USD",
		CostPer1MIn:   0.04,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	Qwen3ASRFlash: {
		ID:            Qwen3ASRFlash,
		Name:          "OpenRouter – Qwen3 ASR Flash",
		Provider:      "openrouter",
		APIModel:      "qwen/qwen3-asr-flash-2026-02-10",
		Currency:      "USD",
		CostPer1MIn:   0.000035,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GrokSTT1: {
		ID:            GrokSTT1,
		Name:          "OpenRouter – Grok STT 1.0",
		Provider:      "openrouter",
		APIModel:      "x-ai/grok-stt-1.0",
		Currency:      "USD",
		CostPer1MIn:   0.1,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
}
