// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.
//
// OpenRouter routes to upstream providers and passes their rates
// through; the figures here are the ones it quotes.

package openrouter

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	Nova3                                 string = "openrouter.nova-3"
	FishAudioTranscribe1                  string = "openrouter.transcribe-1"
	Chirp3                                string = "openrouter.chirp-3"
	MAITranscribe15                       string = "openrouter.mai-transcribe-1.5"
	VoxtralMini3B2507                     string = "openrouter.voxtral-mini-3b-2507"
	VoxtralMiniTranscribe                 string = "openrouter.voxtral-mini-transcribe"
	VoxtralSmall24B2507STT                string = "openrouter.voxtral-small-24b-2507-stt"
	Nemotron35ASRStreamingMultilingual06B string = "openrouter.nemotron-3.5-asr-streaming-multilingual-0.6b"
	ParakeetTDT06BV3                      string = "openrouter.parakeet-tdt-0.6b-v3"
	GPT4oMiniTranscribe                   string = "openrouter.gpt-4o-mini-transcribe"
	GPT4oTranscribe                       string = "openrouter.gpt-4o-transcribe"
	GPTTranscribe                         string = "openrouter.gpt-transcribe"
	Whisper1                              string = "openrouter.whisper-1"
	WhisperLargeV3                        string = "openrouter.whisper-large-v3"
	WhisperLargeV3Turbo                   string = "openrouter.whisper-large-v3-turbo"
	Qwen3ASR06B                           string = "openrouter.qwen3-asr-0.6b"
	Qwen3ASR17B                           string = "openrouter.qwen3-asr-1.7b"
	Qwen3ASRFlash                         string = "openrouter.qwen3-asr-flash-2026-02-10"
	GrokSTT1                              string = "openrouter.grok-stt-1.0"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	Nova3: {
		ID:            Nova3,
		Name:          "OpenRouter – Nova-3",
		Provider:      "openrouter",
		APIModel:      "deepgram/nova-3",
		Currency:      "USD",
		CostPer1MIn:   4300,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	FishAudioTranscribe1: {
		ID:            FishAudioTranscribe1,
		Name:          "OpenRouter – Transcribe 1",
		Provider:      "openrouter",
		APIModel:      "fish-audio/transcribe-1",
		Currency:      "USD",
		CostPer1MIn:   100,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	Chirp3: {
		ID:            Chirp3,
		Name:          "OpenRouter – Chirp 3",
		Provider:      "openrouter",
		APIModel:      "google/chirp-3",
		Currency:      "USD",
		CostPer1MIn:   16000,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	MAITranscribe15: {
		ID:            MAITranscribe15,
		Name:          "OpenRouter – MAI-Transcribe 1.5",
		Provider:      "openrouter",
		APIModel:      "microsoft/mai-transcribe-1.5",
		Currency:      "USD",
		CostPer1MIn:   360000,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	VoxtralMini3B2507: {
		ID:          VoxtralMini3B2507,
		Name:        "OpenRouter – Voxtral Mini 3B 2507",
		Provider:    "openrouter",
		APIModel:    "mistralai/voxtral-mini-3b-2507",
		Currency:    "USD",
		CostPer1MIn: 16.6667,
	},
	VoxtralMiniTranscribe: {
		ID:            VoxtralMiniTranscribe,
		Name:          "OpenRouter – Voxtral Mini Transcribe",
		Provider:      "openrouter",
		APIModel:      "mistralai/voxtral-mini-transcribe",
		Currency:      "USD",
		CostPer1MIn:   3000,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	VoxtralSmall24B2507STT: {
		ID:          VoxtralSmall24B2507STT,
		Name:        "OpenRouter – Voxtral Small 24B 2507 STT",
		Provider:    "openrouter",
		APIModel:    "mistralai/voxtral-small-24b-2507-stt",
		Currency:    "USD",
		CostPer1MIn: 50,
	},
	Nemotron35ASRStreamingMultilingual06B: {
		ID:          Nemotron35ASRStreamingMultilingual06B,
		Name:        "OpenRouter – Nemotron 3.5 ASR Streaming Multilingual 0.6B",
		Provider:    "openrouter",
		APIModel:    "nvidia/nemotron-3.5-asr-streaming-multilingual-0.6b",
		Currency:    "USD",
		CostPer1MIn: 3.33,
	},
	ParakeetTDT06BV3: {
		ID:            ParakeetTDT06BV3,
		Name:          "OpenRouter – Parakeet TDT 0.6B v3",
		Provider:      "openrouter",
		APIModel:      "nvidia/parakeet-tdt-0.6b-v3",
		Currency:      "USD",
		CostPer1MIn:   1500,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4oMiniTranscribe: {
		ID:            GPT4oMiniTranscribe,
		Name:          "OpenRouter – GPT-4o Mini Transcribe",
		Provider:      "openrouter",
		APIModel:      "openai/gpt-4o-mini-transcribe",
		Currency:      "USD",
		CostPer1MIn:   1.25,
		CostPer1MOut:  5,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4oTranscribe: {
		ID:            GPT4oTranscribe,
		Name:          "OpenRouter – GPT-4o Transcribe",
		Provider:      "openrouter",
		APIModel:      "openai/gpt-4o-transcribe",
		Currency:      "USD",
		CostPer1MIn:   2.5,
		CostPer1MOut:  10,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPTTranscribe: {
		ID:          GPTTranscribe,
		Name:        "OpenRouter – GPT Transcribe",
		Provider:    "openrouter",
		APIModel:    "openai/gpt-transcribe",
		Currency:    "USD",
		CostPer1MIn: 4500,
	},
	Whisper1: {
		ID:            Whisper1,
		Name:          "OpenRouter – Whisper 1",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-1",
		Currency:      "USD",
		CostPer1MIn:   6000,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	WhisperLargeV3: {
		ID:            WhisperLargeV3,
		Name:          "OpenRouter – Whisper Large V3",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-large-v3",
		Currency:      "USD",
		CostPer1MIn:   7.5,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	WhisperLargeV3Turbo: {
		ID:            WhisperLargeV3Turbo,
		Name:          "OpenRouter – Whisper Large V3 Turbo",
		Provider:      "openrouter",
		APIModel:      "openai/whisper-large-v3-turbo",
		Currency:      "USD",
		CostPer1MIn:   3.33,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json", "verbose_json"},
	},
	Qwen3ASR06B: {
		ID:          Qwen3ASR06B,
		Name:        "OpenRouter – Qwen3 ASR 0.6B",
		Provider:    "openrouter",
		APIModel:    "qwen/qwen3-asr-0.6b",
		Currency:    "USD",
		CostPer1MIn: 3.33,
	},
	Qwen3ASR17B: {
		ID:          Qwen3ASR17B,
		Name:        "OpenRouter – Qwen3 ASR 1.7B",
		Provider:    "openrouter",
		APIModel:    "qwen/qwen3-asr-1.7b",
		Currency:    "USD",
		CostPer1MIn: 7.5,
	},
	Qwen3ASRFlash: {
		ID:            Qwen3ASRFlash,
		Name:          "OpenRouter – Qwen3 ASR Flash",
		Provider:      "openrouter",
		APIModel:      "qwen/qwen3-asr-flash-2026-02-10",
		Currency:      "USD",
		CostPer1MIn:   35,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GrokSTT1: {
		ID:            GrokSTT1,
		Name:          "OpenRouter – Grok STT 1.0",
		Provider:      "openrouter",
		APIModel:      "x-ai/grok-stt-1.0",
		Currency:      "USD",
		CostPer1MIn:   100000,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
}
