// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package mistral

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	CodestralEmbed string = "codestral-embed"
	Embed          string = "mistral-embed"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	CodestralEmbed: {
		ID:              CodestralEmbed,
		Name:            "Codestral Embed",
		Provider:        "mistral",
		APIModel:        "codestral-embed-2505",
		Currency:        "USD",
		CostPer1MTokens: 0.15,
		MaxInputTokens:  8000,
		EmbeddingDims:   1536,
		SupportedDimensions: []int{
			1536,
			1024,
			768,
			512,
			256,
		},
		MaxBatchSize: 512,
	},
	Embed: {
		ID:              Embed,
		Name:            "Mistral Embed",
		Provider:        "mistral",
		APIModel:        "mistral-embed-2312",
		Currency:        "USD",
		CostPer1MTokens: 0.1,
		MaxInputTokens:  8000,
		EmbeddingDims:   1024,
		MaxBatchSize:    512,
	},
}
