// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.
//
// Berget publishes no context window, so a model new to this catalog
// defaults to 131072 tokens.

package berget

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Qwen3827BFP8    string = "Qwen/Qwen3.8-27B-FP8"
	Gemma431B       string = "google/gemma-4-31B-it"
	Llama3370B      string = "meta-llama/Llama-3.3-70B-Instruct"
	MistralMedium35 string = "mistralai/Mistral-Medium-3.5-128B"
	MistralSmall32  string = "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
	KimiK26         string = "moonshotai/Kimi-K2.6"
	KimiK3          string = "moonshotai/Kimi-K3"
	GPTOSS120B      string = "openai/gpt-oss-120b"
	GLM47           string = "zai-org/GLM-4.7-FP8"
	GLM52           string = "zai-org/GLM-5.2"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Qwen3827BFP8: {
		ID:                    Qwen3827BFP8,
		Name:                  "Qwen3.8-27B-FP8",
		Provider:              "berget",
		APIModel:              "Qwen/Qwen3.8-27B-FP8",
		Currency:              "EUR",
		CostPer1MIn:           0.4,
		CostPer1MOut:          3,
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Gemma431B: {
		ID:                    Gemma431B,
		Name:                  "Gemma 4 31B",
		Provider:              "berget",
		APIModel:              "google/gemma-4-31B-it",
		Currency:              "EUR",
		CostPer1MIn:           0.25,
		CostPer1MOut:          0.5,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Llama3370B: {
		ID:                    Llama3370B,
		Name:                  "Llama 3.3 70B Instruct",
		Provider:              "berget",
		APIModel:              "meta-llama/Llama-3.3-70B-Instruct",
		Currency:              "EUR",
		CostPer1MIn:           0.9,
		CostPer1MOut:          0.9,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	MistralMedium35: {
		ID:                    MistralMedium35,
		Name:                  "Mistral Medium 3.5",
		Provider:              "berget",
		APIModel:              "mistralai/Mistral-Medium-3.5-128B",
		Currency:              "EUR",
		CostPer1MIn:           1.5,
		CostPer1MOut:          5,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralSmall32: {
		ID:                    MistralSmall32,
		Name:                  "Mistral Small 3.2 24B",
		Provider:              "berget",
		APIModel:              "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
		Currency:              "EUR",
		CostPer1MIn:           0.3,
		CostPer1MOut:          0.3,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	KimiK26: {
		ID:                    KimiK26,
		Name:                  "Kimi K2.6",
		Provider:              "berget",
		APIModel:              "moonshotai/Kimi-K2.6",
		Currency:              "EUR",
		CostPer1MIn:           0.75,
		CostPer1MOut:          3.5,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	KimiK3: {
		ID:                    KimiK3,
		Name:                  "Kimi-K3",
		Provider:              "berget",
		APIModel:              "moonshotai/Kimi-K3",
		Currency:              "EUR",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPTOSS120B: {
		ID:                    GPTOSS120B,
		Name:                  "GPT-OSS 120B",
		Provider:              "berget",
		APIModel:              "openai/gpt-oss-120b",
		Currency:              "EUR",
		CostPer1MIn:           0.2,
		CostPer1MOut:          0.75,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	GLM47: {
		ID:                    GLM47,
		Name:                  "GLM-4.7 FP8",
		Provider:              "berget",
		APIModel:              "zai-org/GLM-4.7-FP8",
		Currency:              "EUR",
		CostPer1MIn:           0.7,
		CostPer1MOut:          2.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GLM52: {
		ID:                    GLM52,
		Name:                  "GLM-5.2",
		Provider:              "berget",
		APIModel:              "zai-org/GLM-5.2",
		Currency:              "EUR",
		CostPer1MIn:           1.4,
		CostPer1MOut:          4.4,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
}
