package azure

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Azure OpenAI chat model IDs for this registry.
const (
	GPT41          string = "azure.gpt-4.1"
	GPT41Mini      string = "azure.gpt-4.1-mini"
	GPT41Nano      string = "azure.gpt-4.1-nano"
	GPT4o          string = "azure.gpt-4o"
	GPT4oMini      string = "azure.gpt-4o-mini"
	O1             string = "azure.o1"
	O1Mini         string = "azure.o1-mini"
	O3             string = "azure.o3"
	O3Mini         string = "azure.o3-mini"
	O3Pro          string = "azure.o3-pro"
	O4Mini         string = "azure.o4-mini"
	GPT5           string = "azure.gpt-5"
	GPT5Mini       string = "azure.gpt-5-mini"
	GPT5Nano       string = "azure.gpt-5-nano"
	GPT5Codex      string = "azure.gpt-5-codex"
	GPT5Pro        string = "azure.gpt-5-pro"
	GPT51          string = "azure.gpt-5.1"
	GPT51Codex     string = "azure.gpt-5.1-codex"
	GPT51CodexMini string = "azure.gpt-5.1-codex-mini"
	GPT51CodexMax  string = "azure.gpt-5.1-codex-max"
	GPT52          string = "azure.gpt-5.2"
	GPT52Codex     string = "azure.gpt-5.2-codex"
	GPT53Codex     string = "azure.gpt-5.3-codex"
	GPT54          string = "azure.gpt-5.4"
	GPT54Mini      string = "azure.gpt-5.4-mini"
	GPT54Nano      string = "azure.gpt-5.4-nano"
	GPT54Pro       string = "azure.gpt-5.4-pro"
	GPT55          string = "azure.gpt-5.5"
	GPT55Pro       string = "azure.gpt-5.5-pro"
	GPT56Sol       string = "azure.gpt-5.6-sol"
	GPT56Terra     string = "azure.gpt-5.6-terra"
	GPT56Luna      string = "azure.gpt-5.6-luna"
)

// Models maps Azure OpenAI model IDs to their configurations.
//
// APIModel here is a lookup key, not a request identifier. Azure Foundry
// routes on the deployment name the caller chose, which is arbitrary, so
// [llmazure.WithDeployment] is the only model selector and its value always
// becomes APIModel on the resolved model. These entries exist so a
// conventionally-named deployment inherits cost and context metadata, by
// exact match first and then longest-substring ("gpt-5.4-mini-prod" resolves
// to the gpt-5.4-mini rates). A deployment whose name matches nothing still
// works; it just carries no cost metadata.
//
// Pricing source: rates match the equivalent OpenAI models; the underlying
// model names are from
// https://learn.microsoft.com/azure/ai-foundry/openai/concepts/models.
// Fetched: 2026-07-26.
var Models = map[string]llm.Model{
	GPT41: {
		ID:                    GPT41,
		Name:                  "Azure OpenAI – GPT 4.1",
		Provider:              "azure",
		APIModel:              "gpt-4.1",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Mini: {
		ID:                    GPT41Mini,
		Name:                  "Azure OpenAI – GPT 4.1 mini",
		Provider:              "azure",
		APIModel:              "gpt-4.1-mini",
		CostPer1MIn:           0.4,
		CostPer1MOut:          1.6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Nano: {
		ID:                    GPT41Nano,
		Name:                  "Azure OpenAI – GPT 4.1 nano",
		Provider:              "azure",
		APIModel:              "gpt-4.1-nano",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.025,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4o: {
		ID:                    GPT4o,
		Name:                  "Azure OpenAI – GPT-4o",
		Provider:              "azure",
		APIModel:              "gpt-4o",
		CostPer1MIn:           2.5,
		CostPer1MOut:          10,
		CostPer1MInCached:     1.25,
		ContextWindow:         128000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4oMini: {
		ID:                    GPT4oMini,
		Name:                  "Azure OpenAI – GPT-4o mini",
		Provider:              "azure",
		APIModel:              "gpt-4o-mini",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.075,
		ContextWindow:         128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1: {
		ID:                    O1,
		Name:                  "Azure OpenAI – O1",
		Provider:              "azure",
		APIModel:              "o1",
		CostPer1MIn:           15,
		CostPer1MOut:          60,
		CostPer1MInCached:     7.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1Mini: {
		ID:                    O1Mini,
		Name:                  "Azure OpenAI – O1 mini",
		Provider:              "azure",
		APIModel:              "o1-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.55,
		ContextWindow:         128000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3: {
		ID:                    O3,
		Name:                  "Azure OpenAI – O3",
		Provider:              "azure",
		APIModel:              "o3",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3Mini: {
		ID:                    O3Mini,
		Name:                  "Azure OpenAI – O3 mini",
		Provider:              "azure",
		APIModel:              "o3-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.55,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O4Mini: {
		ID:                    O4Mini,
		Name:                  "Azure OpenAI – O4 mini",
		Provider:              "azure",
		APIModel:              "o4-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.275,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3Pro: {
		ID:                    O3Pro,
		Name:                  "Azure OpenAI – O3 pro",
		Provider:              "azure",
		APIModel:              "o3-pro",
		CostPer1MIn:           20,
		CostPer1MOut:          80,
		CostPer1MInCached:     5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5: {
		ID:                    GPT5,
		Name:                  "Azure OpenAI – GPT-5",
		Provider:              "azure",
		APIModel:              "gpt-5",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Mini: {
		ID:                    GPT5Mini,
		Name:                  "Azure OpenAI – GPT-5 mini",
		Provider:              "azure",
		APIModel:              "gpt-5-mini",
		CostPer1MIn:           0.25,
		CostPer1MOut:          2,
		CostPer1MInCached:     0.025,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Nano: {
		ID:                    GPT5Nano,
		Name:                  "Azure OpenAI – GPT-5 nano",
		Provider:              "azure",
		APIModel:              "gpt-5-nano",
		CostPer1MIn:           0.05,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.005,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Codex: {
		ID:                    GPT5Codex,
		Name:                  "Azure OpenAI – GPT-5 codex",
		Provider:              "azure",
		APIModel:              "gpt-5-codex",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Pro: {
		ID:                    GPT5Pro,
		Name:                  "Azure OpenAI – GPT-5 pro",
		Provider:              "azure",
		APIModel:              "gpt-5-pro",
		CostPer1MIn:           15,
		CostPer1MOut:          120,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51: {
		ID:                    GPT51,
		Name:                  "Azure OpenAI – GPT-5.1",
		Provider:              "azure",
		APIModel:              "gpt-5.1",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51Codex: {
		ID:                    GPT51Codex,
		Name:                  "Azure OpenAI – GPT-5.1 codex",
		Provider:              "azure",
		APIModel:              "gpt-5.1-codex",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51CodexMini: {
		ID:                    GPT51CodexMini,
		Name:                  "Azure OpenAI – GPT-5.1 codex mini",
		Provider:              "azure",
		APIModel:              "gpt-5.1-codex-mini",
		CostPer1MIn:           0.25,
		CostPer1MOut:          2,
		CostPer1MInCached:     0.025,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51CodexMax: {
		ID:                    GPT51CodexMax,
		Name:                  "Azure OpenAI – GPT-5.1 codex max",
		Provider:              "azure",
		APIModel:              "gpt-5.1-codex-max",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52: {
		ID:                    GPT52,
		Name:                  "Azure OpenAI – GPT-5.2",
		Provider:              "azure",
		APIModel:              "gpt-5.2",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52Codex: {
		ID:                    GPT52Codex,
		Name:                  "Azure OpenAI – GPT-5.2 codex",
		Provider:              "azure",
		APIModel:              "gpt-5.2-codex",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT53Codex: {
		ID:                    GPT53Codex,
		Name:                  "Azure OpenAI – GPT-5.3 codex",
		Provider:              "azure",
		APIModel:              "gpt-5.3-codex",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54: {
		ID:                    GPT54,
		Name:                  "Azure OpenAI – GPT-5.4",
		Provider:              "azure",
		APIModel:              "gpt-5.4",
		CostPer1MIn:           2.5,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.25,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Mini: {
		ID:                    GPT54Mini,
		Name:                  "Azure OpenAI – GPT-5.4 mini",
		Provider:              "azure",
		APIModel:              "gpt-5.4-mini",
		CostPer1MIn:           0.75,
		CostPer1MOut:          4.5,
		CostPer1MInCached:     0.075,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Nano: {
		ID:                    GPT54Nano,
		Name:                  "Azure OpenAI – GPT-5.4 nano",
		Provider:              "azure",
		APIModel:              "gpt-5.4-nano",
		CostPer1MIn:           0.2,
		CostPer1MOut:          1.25,
		CostPer1MInCached:     0.02,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Pro: {
		ID:                    GPT54Pro,
		Name:                  "Azure OpenAI – GPT-5.4 pro",
		Provider:              "azure",
		APIModel:              "gpt-5.4-pro",
		CostPer1MIn:           30,
		CostPer1MOut:          180,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT55: {
		ID:                    GPT55,
		Name:                  "Azure OpenAI – GPT-5.5",
		Provider:              "azure",
		APIModel:              "gpt-5.5",
		CostPer1MIn:           5,
		CostPer1MOut:          30,
		CostPer1MInCached:     0.5,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT55Pro: {
		ID:                    GPT55Pro,
		Name:                  "Azure OpenAI – GPT-5.5 pro",
		Provider:              "azure",
		APIModel:              "gpt-5.5-pro",
		CostPer1MIn:           30,
		CostPer1MOut:          180,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Sol: {
		ID:                    GPT56Sol,
		Name:                  "Azure OpenAI – GPT-5.6 Sol",
		Provider:              "azure",
		APIModel:              "gpt-5.6-sol",
		CostPer1MIn:           5,
		CostPer1MOut:          30,
		CostPer1MInCached:     0.5,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Terra: {
		ID:                    GPT56Terra,
		Name:                  "Azure OpenAI – GPT-5.6 Terra",
		Provider:              "azure",
		APIModel:              "gpt-5.6-terra",
		CostPer1MIn:           2.5,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.25,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Luna: {
		ID:                    GPT56Luna,
		Name:                  "Azure OpenAI – GPT-5.6 Luna",
		Provider:              "azure",
		APIModel:              "gpt-5.6-luna",
		CostPer1MIn:           1,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
