// Package fim provides a unified interface for Fill-in-the-Middle code completion
// using various AI providers.
//
// FIM (Fill-in-the-Middle) allows code completion by providing a prompt (code before
// the cursor) and an optional suffix (code after the cursor), with the model filling
// in the middle. This is particularly useful for code editors and IDE integrations.
//
// This package defines the [FIM] interface and the data types that flow through it.
// Concrete vendor implementations live in subpackages (fim/mistral, fim/deepseek);
// each subpackage exports its own NewFIM constructor that returns a tracing-wrapped
// client implementing the interface.
//
// Example usage:
//
//	import (
//		"github.com/joakimcarlsson/ai/fim"
//		"github.com/joakimcarlsson/ai/fim/mistral"
//	)
//
//	client := mistral.NewFIM(
//		mistral.WithAPIKey("your-api-key"),
//		mistral.WithModel(model.MistralModels[model.Codestral]),
//	)
//
//	resp, err := client.Complete(ctx, fim.Request{
//		Prompt: "def add(a, b):\n    ",
//		Suffix: "\n    return result",
//	})
package fim

import (
	"context"
	"time"

	"github.com/joakimcarlsson/ai/model"
	"github.com/joakimcarlsson/ai/tracing"
)

// FinishReason indicates why the model stopped generating tokens.
type FinishReason string

const (
	// FinishReasonStop indicates the model completed naturally or hit a stop sequence.
	FinishReasonStop FinishReason = "stop"
	// FinishReasonLength indicates the model hit the maximum token limit.
	FinishReasonLength FinishReason = "length"
	// FinishReasonUnknown indicates an unknown or unrecognized finish reason.
	FinishReasonUnknown FinishReason = "unknown"
)

// Usage tracks the token consumption for a FIM completion request.
type Usage struct {
	// InputTokens is the number of tokens in the prompt and suffix.
	InputTokens int64
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int64
}

// Request contains the parameters for a FIM completion request.
type Request struct {
	// Prompt is the code/text before the cursor position (required).
	Prompt string
	// Suffix is the code/text after the cursor position (optional).
	Suffix string
	// MaxTokens limits the number of tokens to generate.
	MaxTokens *int64
	// Temperature controls randomness (0.0 = deterministic, higher = more random).
	Temperature *float64
	// TopP controls nucleus sampling probability mass.
	TopP *float64
	// Stop contains sequences that will halt generation when encountered.
	Stop []string
	// RandomSeed enables deterministic generation when set.
	RandomSeed *int64
}

// Response contains the result of a FIM completion request.
type Response struct {
	// Content is the generated text that fills in between prompt and suffix.
	Content string
	// Usage tracks token consumption for this request.
	Usage Usage
	// FinishReason indicates why the model stopped generating.
	FinishReason FinishReason
}

// EventType identifies the type of streaming event.
type EventType string

const (
	// EventContentDelta indicates a partial content update during streaming.
	EventContentDelta EventType = "content_delta"
	// EventComplete indicates the streaming response has completed.
	EventComplete EventType = "complete"
	// EventError indicates an error occurred during streaming.
	EventError EventType = "error"
)

// Event represents a single event in a streaming FIM response.
type Event struct {
	// Type identifies the kind of event.
	Type EventType
	// Content contains partial text for content delta events.
	Content string
	// Response contains the final response for completion events.
	Response *Response
	// Error contains error information for error events.
	Error error
}

// FIM defines the interface for Fill-in-the-Middle code completion.
type FIM interface {
	// Complete sends a FIM request and returns the complete response.
	Complete(ctx context.Context, req Request) (*Response, error)
	// CompleteStream sends a FIM request and returns a channel of streaming events.
	CompleteStream(ctx context.Context, req Request) <-chan Event
	// Model returns the model configuration being used.
	Model() model.Model
}

// TracingAttrs are construction-time attributes vendor packages forward to the
// [WithTracing] wrapper so they appear on every span produced for the wrapped
// client. These come from constructor options that aren't exposed on the FIM
// interface (max tokens, temperature, top-p, etc.).
type TracingAttrs struct {
	MaxTokens   int64
	Temperature *float64
	TopP        *float64
}

// WithTracing wraps a FIM client so every call records OpenTelemetry spans and
// metrics. The attrs are recorded as construction-time span attributes.
func WithTracing(inner FIM, attrs TracingAttrs) FIM {
	return &tracingFIM{inner: inner, attrs: attrs}
}

type tracingFIM struct {
	inner FIM
	attrs TracingAttrs
}

func (t *tracingFIM) Model() model.Model {
	return t.inner.Model()
}

func (t *tracingFIM) spanAttrs() []tracing.Attr {
	var attrs []tracing.Attr
	if t.attrs.MaxTokens > 0 {
		attrs = append(attrs, tracing.AttrRequestMaxTokens.Int64(t.attrs.MaxTokens))
	}
	if t.attrs.Temperature != nil {
		attrs = append(attrs, tracing.AttrRequestTemperature.Float64(*t.attrs.Temperature))
	}
	if t.attrs.TopP != nil {
		attrs = append(attrs, tracing.AttrRequestTopP.Float64(*t.attrs.TopP))
	}
	return attrs
}

func (t *tracingFIM) Complete(ctx context.Context, req Request) (*Response, error) {
	m := t.inner.Model()
	start := time.Now()
	ctx, span := tracing.StartFIMSpan(
		ctx,
		m.APIModel,
		string(m.Provider),
		t.spanAttrs()...,
	)
	defer span.End()

	resp, err := t.inner.Complete(ctx, req)
	if err != nil {
		tracing.SetError(span, err)
		tracing.RecordMetrics(
			ctx,
			"fim_complete",
			m.APIModel,
			string(m.Provider),
			time.Since(start),
			0,
			0,
			err,
		)
		return nil, err
	}

	tracing.SetResponseAttrs(span,
		tracing.AttrUsageInputTokens.Int64(resp.Usage.InputTokens),
		tracing.AttrUsageOutputTokens.Int64(resp.Usage.OutputTokens),
		tracing.AttrResponseFinishReason.String(string(resp.FinishReason)),
	)
	tracing.RecordMetrics(
		ctx,
		"fim_complete",
		m.APIModel,
		string(m.Provider),
		time.Since(start),
		resp.Usage.InputTokens,
		resp.Usage.OutputTokens,
		nil,
	)
	return resp, nil
}

func (t *tracingFIM) CompleteStream(ctx context.Context, req Request) <-chan Event {
	m := t.inner.Model()
	start := time.Now()
	ctx, span := tracing.StartFIMSpan(
		ctx,
		m.APIModel,
		string(m.Provider),
		t.spanAttrs()...,
	)

	innerCh := t.inner.CompleteStream(ctx, req)
	outCh := make(chan Event)
	go func() {
		defer close(outCh)
		defer span.End()
		for evt := range innerCh {
			if evt.Type == EventComplete && evt.Response != nil {
				tracing.SetResponseAttrs(
					span,
					tracing.AttrUsageInputTokens.Int64(evt.Response.Usage.InputTokens),
					tracing.AttrUsageOutputTokens.Int64(evt.Response.Usage.OutputTokens),
					tracing.AttrResponseFinishReason.String(string(evt.Response.FinishReason)),
				)
				tracing.RecordMetrics(
					ctx,
					"fim_complete",
					m.APIModel,
					string(m.Provider),
					time.Since(start),
					evt.Response.Usage.InputTokens,
					evt.Response.Usage.OutputTokens,
					nil,
				)
			}
			if evt.Type == EventError && evt.Error != nil {
				tracing.SetError(span, evt.Error)
				tracing.RecordMetrics(
					ctx,
					"fim_complete",
					m.APIModel,
					string(m.Provider),
					time.Since(start),
					0,
					0,
					evt.Error,
				)
			}
			outCh <- evt
		}
	}()
	return outCh
}
