// Package fim provides a unified interface for Fill-in-the-Middle code completion
// using various AI providers.
//
// FIM (Fill-in-the-Middle) allows code completion by providing a prompt (code before
// the cursor) and an optional suffix (code after the cursor), with the model filling
// in the middle. This is particularly useful for code editors and IDE integrations.
//
// Supported providers include Mistral (Codestral) and DeepSeek.
//
// Example usage:
//
//	client, err := fim.NewFIM(model.ProviderMistral,
//		fim.WithAPIKey("your-api-key"),
//		fim.WithModel(model.MistralModels[model.Codestral]),
//	)
//	if err != nil {
//		log.Fatal(err)
//	}
//
//	resp, err := client.Complete(ctx, fim.FIMRequest{
//		Prompt: "def add(a, b):\n    ",
//		Suffix: "\n    return result",
//	})
//	if err != nil {
//		log.Fatal(err)
//	}
//
//	fmt.Println(resp.Content)
package fim

import (
	"context"
	"fmt"
	"time"

	"github.com/joakimcarlsson/ai/model"
)

// FinishReason indicates why the model stopped generating tokens.
type FinishReason string

const (
	// FinishReasonStop indicates the model completed naturally or hit a stop sequence.
	FinishReasonStop FinishReason = "stop"
	// FinishReasonLength indicates the model hit the maximum token limit.
	FinishReasonLength FinishReason = "length"
	// FinishReasonUnknown indicates an unknown or unrecognized finish reason.
	FinishReasonUnknown FinishReason = "unknown"
)

// FIMUsage tracks the token consumption for a FIM completion request.
type FIMUsage struct {
	// InputTokens is the number of tokens in the prompt and suffix.
	InputTokens int64
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int64
}

// FIMRequest contains the parameters for a FIM completion request.
type FIMRequest struct {
	// Prompt is the code/text before the cursor position (required).
	Prompt string
	// Suffix is the code/text after the cursor position (optional).
	Suffix string
	// MaxTokens limits the number of tokens to generate.
	MaxTokens *int64
	// Temperature controls randomness (0.0 = deterministic, higher = more random).
	Temperature *float64
	// TopP controls nucleus sampling probability mass.
	TopP *float64
	// Stop contains sequences that will halt generation when encountered.
	Stop []string
	// RandomSeed enables deterministic generation when set.
	RandomSeed *int64
}

// FIMResponse contains the result of a FIM completion request.
type FIMResponse struct {
	// Content is the generated text that fills in between prompt and suffix.
	Content string
	// Usage tracks token consumption for this request.
	Usage FIMUsage
	// FinishReason indicates why the model stopped generating.
	FinishReason FinishReason
}

// FIMEventType identifies the type of streaming event.
type FIMEventType string

const (
	// EventContentDelta indicates a partial content update during streaming.
	EventContentDelta FIMEventType = "content_delta"
	// EventComplete indicates the streaming response has completed.
	EventComplete FIMEventType = "complete"
	// EventError indicates an error occurred during streaming.
	EventError FIMEventType = "error"
)

// FIMEvent represents a single event in a streaming FIM response.
type FIMEvent struct {
	// Type identifies the kind of event.
	Type FIMEventType
	// Content contains partial text for content delta events.
	Content string
	// Response contains the final response for completion events.
	Response *FIMResponse
	// Error contains error information for error events.
	Error error
}

// FIM defines the interface for Fill-in-the-Middle code completion.
type FIM interface {
	// Complete sends a FIM request and returns the complete response.
	Complete(ctx context.Context, req FIMRequest) (*FIMResponse, error)
	// CompleteStream sends a FIM request and returns a channel of streaming events.
	CompleteStream(ctx context.Context, req FIMRequest) <-chan FIMEvent
	// Model returns the model configuration being used.
	Model() model.Model
}

type fimClientOptions struct {
	apiKey      string
	model       model.Model
	maxTokens   int64
	temperature *float64
	topP        *float64
	timeout     *time.Duration

	mistralOptions  []MistralOption
	deepseekOptions []DeepSeekOption
}

// FIMClientOption configures a FIM client.
type FIMClientOption func(*fimClientOptions)

type fimClient interface {
	complete(ctx context.Context, req FIMRequest) (*FIMResponse, error)
	stream(ctx context.Context, req FIMRequest) <-chan FIMEvent
}

type baseFIM[C fimClient] struct {
	options fimClientOptions
	client  C
}

// NewFIM creates a new FIM client for the specified provider.
// Supported providers are model.ProviderMistral and model.ProviderDeepSeek.
func NewFIM(
	provider model.ModelProvider,
	opts ...FIMClientOption,
) (FIM, error) {
	clientOptions := fimClientOptions{}
	for _, o := range opts {
		o(&clientOptions)
	}

	switch provider {
	case model.ProviderMistral:
		return &baseFIM[*mistralClient]{
			options: clientOptions,
			client:  newMistralClient(clientOptions),
		}, nil
	case model.ProviderDeepSeek:
		return &baseFIM[*deepseekClient]{
			options: clientOptions,
			client:  newDeepSeekClient(clientOptions),
		}, nil
	}

	return nil, fmt.Errorf("fim provider not supported: %s", provider)
}

func (f *baseFIM[C]) Complete(
	ctx context.Context,
	req FIMRequest,
) (*FIMResponse, error) {
	return f.client.complete(ctx, req)
}

func (f *baseFIM[C]) CompleteStream(
	ctx context.Context,
	req FIMRequest,
) <-chan FIMEvent {
	return f.client.stream(ctx, req)
}

func (f *baseFIM[C]) Model() model.Model {
	return f.options.model
}

// WithAPIKey sets the API key for authentication with the FIM provider.
func WithAPIKey(apiKey string) FIMClientOption {
	return func(options *fimClientOptions) {
		options.apiKey = apiKey
	}
}

// WithModel specifies which model to use for FIM completions.
func WithModel(m model.Model) FIMClientOption {
	return func(options *fimClientOptions) {
		options.model = m
	}
}

// WithMaxTokens sets the default maximum number of tokens to generate.
func WithMaxTokens(maxTokens int64) FIMClientOption {
	return func(options *fimClientOptions) {
		options.maxTokens = maxTokens
	}
}

// WithTemperature sets the default sampling temperature (0.0 to 1.0).
func WithTemperature(temperature float64) FIMClientOption {
	return func(options *fimClientOptions) {
		options.temperature = &temperature
	}
}

// WithTopP sets the default nucleus sampling probability.
func WithTopP(topP float64) FIMClientOption {
	return func(options *fimClientOptions) {
		options.topP = &topP
	}
}

// WithTimeout sets the maximum duration to wait for API responses.
func WithTimeout(timeout time.Duration) FIMClientOption {
	return func(options *fimClientOptions) {
		options.timeout = &timeout
	}
}

// WithMistralOptions applies Mistral-specific configuration options.
func WithMistralOptions(mistralOptions ...MistralOption) FIMClientOption {
	return func(options *fimClientOptions) {
		options.mistralOptions = mistralOptions
	}
}

// WithDeepSeekOptions applies DeepSeek-specific configuration options.
func WithDeepSeekOptions(deepseekOptions ...DeepSeekOption) FIMClientOption {
	return func(options *fimClientOptions) {
		options.deepseekOptions = deepseekOptions
	}
}
