// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package berget

import (
	"github.com/joakimcarlsson/ai/rerankers"
)

// Model IDs served by this catalog.
const (
	BGERerankerV2M3 string = "BAAI/bge-reranker-v2-m3"
)

// Models maps model IDs to their configurations.
var Models = map[string]rerankers.RerankerModel{
	BGERerankerV2M3: {
		ID:              BGERerankerV2M3,
		Name:            "BGE Reranker v2 m3",
		Provider:        "berget",
		APIModel:        "BAAI/bge-reranker-v2-m3",
		Currency:        "EUR",
		CostPer1MTokens: 0.1,
		MaxQueryTokens:  512,
		MaxTotalTokens:  8192,
	},
}
