// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://api.berget.ai/v1/models
// Generated: 2026-08-12
//
// Berget bills in EUR, so CostPer1MTokens is EUR, not USD.
//
// Display names and token limits are not part of the models response
// and are carried over from the previous catalog.

package berget

import (
	"github.com/joakimcarlsson/ai/rerankers"
)

// Model IDs served by this catalog.
const (
	BGERerankerV2M3 string = "BAAI/bge-reranker-v2-m3"
)

// Models maps model IDs to their configurations.
var Models = map[string]rerankers.RerankerModel{
	BGERerankerV2M3: {
		ID:              BGERerankerV2M3,
		Name:            "BGE Reranker v2 m3",
		Provider:        "berget",
		APIModel:        "BAAI/bge-reranker-v2-m3",
		Currency:        "EUR",
		CostPer1MTokens: 0.1,
		MaxQueryTokens:  512,
		MaxTotalTokens:  8192,
	},
}
