// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-12
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// deepseek provider.
//
// models.dev indexes providers rather than serving them, so models it
// stops listing are kept here and reported by the sync instead of
// being deleted. Display names are set when a model is first added and
// carried over from then on.

package deepseek

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	DeepseekChat     string = "deepseek-chat"
	R1               string = "deepseek-r1"
	R1Distill        string = "deepseek-r1-distill-llama-70b"
	DeepseekReasoner string = "deepseek-reasoner"
	V32              string = "deepseek-v3.2"
	V32Thinking      string = "deepseek-v3.2-thinking"
	V4Flash          string = "deepseek-v4-flash"
	V4Pro            string = "deepseek-v4-pro"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	DeepseekChat: {
		ID:                  DeepseekChat,
		Name:                "DeepSeek Chat",
		Provider:            "deepseek",
		APIModel:            "deepseek-chat",
		Currency:            "USD",
		CostPer1MIn:         0.14,
		CostPer1MOut:        0.28,
		CostPer1MInCached:   0.0028,
		ContextWindow:       1000000,
		DefaultMaxTokens:    384000,
		SupportsAttachments: true,
	},
	R1: {
		ID:               R1,
		Name:             "DeepSeek R1",
		Provider:         "deepseek",
		APIModel:         "deepseek-r1",
		Currency:         "USD",
		CostPer1MIn:      0.14,
		CostPer1MOut:     0.14,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	R1Distill: {
		ID:               R1Distill,
		Name:             "DeepSeek R1 Distill Llama 70B",
		Provider:         "deepseek",
		APIModel:         "deepseek-r1-distill-llama-70b",
		Currency:         "USD",
		CostPer1MIn:      0.14,
		CostPer1MOut:     0.28,
		ContextWindow:    128000,
		DefaultMaxTokens: 50000,
		CanReason:        true,
	},
	DeepseekReasoner: {
		ID:                  DeepseekReasoner,
		Name:                "DeepSeek Reasoner",
		Provider:            "deepseek",
		APIModel:            "deepseek-reasoner",
		Currency:            "USD",
		CostPer1MIn:         0.14,
		CostPer1MOut:        0.28,
		CostPer1MInCached:   0.0028,
		ContextWindow:       1000000,
		DefaultMaxTokens:    384000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	V32: {
		ID:                V32,
		Name:              "DeepSeek V3.2",
		Provider:          "deepseek",
		APIModel:          "deepseek-v3.2",
		Currency:          "USD",
		CostPer1MIn:       0.28,
		CostPer1MOut:      0.42,
		CostPer1MInCached: 0.028,
		ContextWindow:     128000,
		DefaultMaxTokens:  8000,
	},
	V32Thinking: {
		ID:                V32Thinking,
		Name:              "DeepSeek V3.2 Thinking",
		Provider:          "deepseek",
		APIModel:          "deepseek-v3.2-thinking",
		Currency:          "USD",
		CostPer1MIn:       0.28,
		CostPer1MOut:      0.42,
		CostPer1MInCached: 0.028,
		ContextWindow:     128000,
		DefaultMaxTokens:  64000,
		CanReason:         true,
	},
	V4Flash: {
		ID:                    V4Flash,
		Name:                  "DeepSeek V4 Flash",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-flash",
		Currency:              "USD",
		CostPer1MIn:           0.14,
		CostPer1MOut:          0.28,
		CostPer1MInCached:     0.0028,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	V4Pro: {
		ID:                    V4Pro,
		Name:                  "DeepSeek V4 Pro",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-pro",
		Currency:              "USD",
		CostPer1MIn:           0.435,
		CostPer1MOut:          0.87,
		CostPer1MInCached:     0.003625,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
