// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package deepseek

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	V4Flash string = "deepseek-v4-flash"
	V4Pro   string = "deepseek-v4-pro"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	V4Flash: {
		ID:                    V4Flash,
		Name:                  "DeepSeek V4 Flash",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-flash",
		Currency:              "USD",
		CostPer1MIn:           0.22,
		CostPer1MOut:          0.66,
		CostPer1MInCached:     0.007,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	V4Pro: {
		ID:                    V4Pro,
		Name:                  "DeepSeek V4 Pro",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-pro",
		Currency:              "USD",
		CostPer1MIn:           0.66,
		CostPer1MOut:          1.98,
		CostPer1MInCached:     0.022,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
