// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://api.berget.ai/v1/models
// Generated: 2026-08-12
//
// Berget bills in EUR, so CostPer1MTokens is EUR, not USD.
//
// Display names, input limits and embedding dimensions are not part of
// the models response and are carried over from the previous catalog.

package berget

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	E5Large         string = "intfloat/multilingual-e5-large"
	E5LargeInstruct string = "intfloat/multilingual-e5-large-instruct"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	E5Large: {
		ID:              E5Large,
		Name:            "Multilingual E5 Large",
		Provider:        "berget",
		APIModel:        "intfloat/multilingual-e5-large",
		Currency:        "EUR",
		CostPer1MTokens: 0.03,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
	},
	E5LargeInstruct: {
		ID:              E5LargeInstruct,
		Name:            "Multilingual E5 Large Instruct",
		Provider:        "berget",
		APIModel:        "intfloat/multilingual-e5-large-instruct",
		Currency:        "EUR",
		CostPer1MTokens: 0.03,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
	},
}
