// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package berget

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	E5Large         string = "intfloat/multilingual-e5-large"
	E5LargeInstruct string = "intfloat/multilingual-e5-large-instruct"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	E5Large: {
		ID:              E5Large,
		Name:            "Multilingual E5 Large",
		Provider:        "berget",
		APIModel:        "intfloat/multilingual-e5-large",
		Currency:        "EUR",
		CostPer1MTokens: 0.03,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
	},
	E5LargeInstruct: {
		ID:              E5LargeInstruct,
		Name:            "Multilingual E5 Large Instruct",
		Provider:        "berget",
		APIModel:        "intfloat/multilingual-e5-large-instruct",
		Currency:        "EUR",
		CostPer1MTokens: 0.03,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
	},
}
