// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MChars is per 1M characters, in the currency the provider
// bills in. Default format and latency are not published and are
// carried over from the previous catalog.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	MiniTTS string = "gpt-4o-mini-tts"
	TTS1    string = "tts-1"
	TTS1HD  string = "tts-1-hd"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	MiniTTS: {
		ID:             MiniTTS,
		Name:           "GPT-4o Mini TTS",
		Provider:       "openai",
		APIModel:       "gpt-4o-mini-tts",
		Currency:       "USD",
		CostPer1MChars: 12,
		MaxCharacters:  4096,
		SupportedFormats: []string{
			"aac",
			"flac",
			"mp3",
			"opus",
			"pcm",
			"wav",
		},
		DefaultFormat: "mp3",
	},
	TTS1: {
		ID:             TTS1,
		Name:           "OpenAI TTS-1",
		Provider:       "openai",
		APIModel:       "tts-1",
		Currency:       "USD",
		CostPer1MChars: 15,
		MaxCharacters:  4096,
		SupportedFormats: []string{
			"aac",
			"flac",
			"mp3",
			"opus",
			"pcm",
			"wav",
		},
		DefaultFormat: "mp3",
	},
	TTS1HD: {
		ID:             TTS1HD,
		Name:           "OpenAI TTS-1 HD",
		Provider:       "openai",
		APIModel:       "tts-1-hd",
		Currency:       "USD",
		CostPer1MChars: 30,
		MaxCharacters:  4096,
		SupportedFormats: []string{
			"aac",
			"flac",
			"mp3",
			"opus",
			"pcm",
			"wav",
		},
		DefaultFormat: "mp3",
	},
}
