package voyage

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Voyage provider identifier plus embedding and reranker model IDs for this registry.
const (
	Voyage35       string = "voyage-3.5"
	Voyage35Lite   string = "voyage-3.5-lite"
	Voyage3Large   string = "voyage-3-large"
	Code3          string = "voyage-code-3"
	Context3       string = "voyage-context-3"
	Context4       string = "voyage-context-4"
	Finance2       string = "voyage-finance-2"
	Law2           string = "voyage-law-2"
	Code2          string = "voyage-code-2"
	Voyage3        string = "voyage-3"
	Voyage3Lite    string = "voyage-3-lite"
	Multilingual2  string = "voyage-multilingual-2"
	Large2Instruct string = "voyage-large-2-instruct"
	Large2         string = "voyage-large-2"
	Voyage2        string = "voyage-2"
	Multi3         string = "voyage-multimodal-3"
	Lite02Instruct string = "voyage-lite-02-instruct"
	Voyage02       string = "voyage-02"
	Voyage01       string = "voyage-01"
	Lite01         string = "voyage-lite-01"
	Lite01Instruct string = "voyage-lite-01-instruct"
	Voyage4Large   string = "voyage-4-large"
	Voyage4        string = "voyage-4"
	Voyage4Lite    string = "voyage-4-lite"
	Voyage4Nano    string = "voyage-4-nano"
	Multi35        string = "voyage-multimodal-3.5"
)

// Models maps Voyage embedding model IDs to their configurations.
//
// Pricing source: https://docs.voyageai.com/docs/pricing.
// Fetched: 2026-07-26.
var Models = map[string]embeddings.EmbeddingModel{
	Voyage3Large: {
		ID:              Voyage3Large,
		Name:            "Voyage 3 Large",
		Provider:        "voyage",
		APIModel:        "voyage-3-large",
		CostPer1MTokens: 0.18,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   120000,
	},
	Voyage35: {
		ID:              Voyage35,
		Name:            "Voyage 3.5",
		Provider:        "voyage",
		APIModel:        "voyage-3.5",
		CostPer1MTokens: 0.06,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   320000,
	},
	Voyage35Lite: {
		ID:              Voyage35Lite,
		Name:            "Voyage 3.5 Lite",
		Provider:        "voyage",
		APIModel:        "voyage-3.5-lite",
		CostPer1MTokens: 0.02,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   1000000,
	},
	Code3: {
		ID:              Code3,
		Name:            "Voyage Code 3",
		Provider:        "voyage",
		APIModel:        "voyage-code-3",
		CostPer1MTokens: 0.18,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   120000,
	},
	Finance2: {
		ID:                Finance2,
		Name:              "Voyage Finance 2",
		Provider:          "voyage",
		APIModel:          "voyage-finance-2",
		CostPer1MTokens:   0.12,
		MaxInputTokens:    32000,
		EmbeddingDims:     1024,
		MaxBatchSize:      1000,
		MaxTokensPerBatch: 120000,
	},
	Law2: {
		ID:                  Law2,
		Name:                "Voyage Law 2",
		Provider:            "voyage",
		APIModel:            "voyage-law-2",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      16000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   120000,
	},
	Code2: {
		ID:                  Code2,
		Name:                "Voyage Code 2",
		Provider:            "voyage",
		APIModel:            "voyage-code-2",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      16000,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{1536},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   120000,
	},
	Context3: {
		ID:              Context3,
		Name:            "Voyage Context 3",
		Provider:        "voyage",
		APIModel:        "voyage-context-3",
		CostPer1MTokens: 0.18,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   120000,
	},
	Context4: {
		ID:              Context4,
		Name:            "Voyage Context 4",
		Provider:        "voyage",
		APIModel:        "voyage-context-4",
		CostPer1MTokens: 0.18,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   120000,
	},
	Voyage4Large: {
		ID:              Voyage4Large,
		Name:            "Voyage 4 Large",
		Provider:        "voyage",
		APIModel:        "voyage-4-large",
		CostPer1MTokens: 0.12,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   120000,
	},
	Voyage4: {
		ID:              Voyage4,
		Name:            "Voyage 4",
		Provider:        "voyage",
		APIModel:        "voyage-4",
		CostPer1MTokens: 0.06,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   320000,
	},
	Voyage4Lite: {
		ID:              Voyage4Lite,
		Name:            "Voyage 4 Lite",
		Provider:        "voyage",
		APIModel:        "voyage-4-lite",
		CostPer1MTokens: 0.02,
		MaxInputTokens:  32000,
		EmbeddingDims:   1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   1000000,
	},
	Voyage4Nano: {
		ID:             Voyage4Nano,
		Name:           "Voyage 4 Nano",
		Provider:       "voyage",
		APIModel:       "voyage-4-nano",
		MaxInputTokens: 32000,
		EmbeddingDims:  1024,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			2048,
		},
		MaxBatchSize:        1000,
		SupportsOutputDtype: true,
		MaxTokensPerBatch:   1000000,
	},
	Multi35: {
		ID:                  Multi35,
		Name:                "Voyage Multimodal 3.5",
		Provider:            "voyage",
		APIModel:            "voyage-multimodal-3.5",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      32000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Voyage3: {
		ID:                  Voyage3,
		Name:                "Voyage 3",
		Provider:            "voyage",
		APIModel:            "voyage-3",
		CostPer1MTokens:     0.06,
		MaxInputTokens:      32000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Voyage3Lite: {
		ID:                  Voyage3Lite,
		Name:                "Voyage 3 Lite",
		Provider:            "voyage",
		APIModel:            "voyage-3-lite",
		CostPer1MTokens:     0.02,
		MaxInputTokens:      32000,
		EmbeddingDims:       512,
		SupportedDimensions: []int{512},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Multilingual2: {
		ID:                  Multilingual2,
		Name:                "Voyage Multilingual 2",
		Provider:            "voyage",
		APIModel:            "voyage-multilingual-2",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      32000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Large2Instruct: {
		ID:                  Large2Instruct,
		Name:                "Voyage Large 2 Instruct",
		Provider:            "voyage",
		APIModel:            "voyage-large-2-instruct",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      16000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Large2: {
		ID:                  Large2,
		Name:                "Voyage Large 2",
		Provider:            "voyage",
		APIModel:            "voyage-large-2",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      16000,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{1536},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Voyage2: {
		ID:                  Voyage2,
		Name:                "Voyage 2",
		Provider:            "voyage",
		APIModel:            "voyage-2",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Multi3: {
		ID:                  Multi3,
		Name:                "Voyage Multimodal 3",
		Provider:            "voyage",
		APIModel:            "voyage-multimodal-3",
		CostPer1MTokens:     0.12,
		MaxInputTokens:      32000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Lite02Instruct: {
		ID:                  Lite02Instruct,
		Name:                "Voyage Lite 02 Instruct [Deprecated]",
		Provider:            "voyage",
		APIModel:            "voyage-lite-02-instruct",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Voyage02: {
		ID:                  Voyage02,
		Name:                "Voyage 02 [Deprecated]",
		Provider:            "voyage",
		APIModel:            "voyage-02",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Voyage01: {
		ID:                  Voyage01,
		Name:                "Voyage 01 [Deprecated]",
		Provider:            "voyage",
		APIModel:            "voyage-01",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Lite01: {
		ID:                  Lite01,
		Name:                "Voyage Lite 01 [Deprecated]",
		Provider:            "voyage",
		APIModel:            "voyage-lite-01",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
	Lite01Instruct: {
		ID:                  Lite01Instruct,
		Name:                "Voyage Lite 01 Instruct [Deprecated]",
		Provider:            "voyage",
		APIModel:            "voyage-lite-01-instruct",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      4000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{1024},
		MaxBatchSize:        1000,
		MaxTokensPerBatch:   320000,
	},
}
