// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package elevenlabs

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	ScribeV1         string = "scribe_v1"
	ScribeV2         string = "scribe_v2"
	ScribeV2Realtime string = "scribe_v2_realtime"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	ScribeV1: {
		ID:            ScribeV1,
		Name:          "ElevenLabs Scribe v1",
		Provider:      "elevenlabs",
		APIModel:      "scribe_v1",
		Currency:      "USD",
		CostPer1MIn:   0.0067,
		MaxFileSizeMB: 3000,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
			"aac",
			"aiff",
			"opus",
		},
		SupportedResponseFormats: []string{"json", "text", "srt"},
	},
	ScribeV2: {
		ID:            ScribeV2,
		Name:          "ElevenLabs Scribe v2",
		Provider:      "elevenlabs",
		APIModel:      "scribe_v2",
		Currency:      "USD",
		CostPer1MIn:   0.003667,
		MaxFileSizeMB: 3000,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
			"aac",
			"aiff",
			"opus",
			"pcm_8000",
			"pcm_16000",
			"pcm_22050",
			"pcm_24000",
			"pcm_44100",
			"pcm_48000",
			"ulaw_8000",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsDiarization:      true,
		SupportedResponseFormats: []string{"json", "text", "srt"},
	},
	ScribeV2Realtime: {
		ID:          ScribeV2Realtime,
		Name:        "ElevenLabs Scribe v2 Realtime",
		Provider:    "elevenlabs",
		APIModel:    "scribe_v2_realtime",
		Currency:    "USD",
		CostPer1MIn: 0.0065,
		SupportedFormats: []string{
			"pcm_8000",
			"pcm_16000",
			"pcm_22050",
			"pcm_24000",
			"pcm_44100",
			"pcm_48000",
			"ulaw_8000",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json", "text", "srt"},
	},
}
