// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package gemini

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	Embedding001            string = "gemini-embedding-001"
	Embedding2              string = "gemini-embedding-2"
	GeminiEmbedding2Preview string = "gemini-embedding-2-preview"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	Embedding001: {
		ID:                  Embedding001,
		Name:                "Gemini Embedding 001",
		Provider:            "gemini",
		APIModel:            "gemini-embedding-001",
		Currency:            "USD",
		CostPer1MTokens:     0.15,
		MaxInputTokens:      2048,
		EmbeddingDims:       3072,
		SupportedDimensions: []int{768, 1536, 3072},
		MaxBatchSize:        100,
	},
	Embedding2: {
		ID:                  Embedding2,
		Name:                "Gemini Embedding 2",
		Provider:            "gemini",
		APIModel:            "gemini-embedding-2",
		Currency:            "USD",
		CostPer1MTokens:     0.2,
		MaxInputTokens:      8192,
		EmbeddingDims:       768,
		SupportedDimensions: []int{768, 1536, 3072},
		MaxBatchSize:        100,
	},
	GeminiEmbedding2Preview: {
		ID:       GeminiEmbedding2Preview,
		Name:     "Gemini Embedding 2",
		Provider: "gemini",
		APIModel: "gemini-embedding-2-preview",
		Currency: "USD",
	},
}
