// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package gemini

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	Gemini25FlashImage        string = "gemini-2.5-flash-image"
	Gemini3ProImage2          string = "gemini-3-pro-image-2"
	Gemini31FlashImagePreview string = "gemini-3.1-flash-image-preview"
	Gemini31FlashLiteImage    string = "gemini-3.1-flash-lite-image"
	Imagen4Fast               string = "imagen-4.0-fast"
	Imagen40Generate          string = "imagen-4.0-generate"
	Imagen4                   string = "imagen-4.0"
	Imagen4Ultra              string = "imagen-4.0-ultra"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	Gemini25FlashImage: {
		ID:       Gemini25FlashImage,
		Name:     "Gemini 2.5 Flash Image",
		Provider: "gemini",
		APIModel: "gemini-2.5-flash-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.039,
			},
			"1:1": {
				"default": 0.039,
			},
			"3:4": {
				"default": 0.039,
			},
			"4:3": {
				"default": 0.039,
			},
			"9:16": {
				"default": 0.039,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"16:9",
			"1:1",
			"21:9",
			"2:3",
			"3:2",
			"3:4",
			"4:3",
			"4:5",
			"5:4",
			"9:16",
		},
		DefaultAspectRatio: "1:1",
	},
	Gemini3ProImage2: {
		ID:              Gemini3ProImage2,
		Name:            "Gemini 3 Pro Image (Nano Banana Pro)",
		Provider:        "gemini",
		APIModel:        "gemini-3-pro-image",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	Gemini31FlashImagePreview: {
		ID:       Gemini31FlashImagePreview,
		Name:     "Gemini 3.1 Flash Image Preview (Nano Banana 2)",
		Provider: "gemini",
		APIModel: "gemini-3.1-flash-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.067,
			},
			"1:1": {
				"default": 0.067,
			},
			"1:4": {
				"default": 0.067,
			},
			"1:8": {
				"default": 0.067,
			},
			"3:4": {
				"default": 0.067,
			},
			"4:1": {
				"default": 0.067,
			},
			"4:3": {
				"default": 0.067,
			},
			"8:1": {
				"default": 0.067,
			},
			"9:16": {
				"default": 0.067,
			},
		},
		MaxPromptTokens:    131072,
		SupportedSizes:     []string{"1K", "2K", "4K", "512px"},
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"16:9",
			"1:1",
			"1:4",
			"1:8",
			"21:9",
			"2:3",
			"3:2",
			"3:4",
			"4:1",
			"4:3",
			"4:5",
			"5:4",
			"8:1",
			"9:16",
		},
		DefaultAspectRatio: "1:1",
	},
	Gemini31FlashLiteImage: {
		ID:       Gemini31FlashLiteImage,
		Name:     "Gemini 3.1 Flash Lite Image (Nano Banana 2 Lite)",
		Provider: "gemini",
		APIModel: "gemini-3.1-flash-lite-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.0336,
			},
			"1:1": {
				"default": 0.0336,
			},
			"1:4": {
				"default": 0.0336,
			},
			"1:8": {
				"default": 0.0336,
			},
			"3:4": {
				"default": 0.0336,
			},
			"4:1": {
				"default": 0.0336,
			},
			"4:3": {
				"default": 0.0336,
			},
			"8:1": {
				"default": 0.0336,
			},
			"9:16": {
				"default": 0.0336,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"3:4",
			"4:3",
			"9:16",
			"16:9",
			"1:4",
			"4:1",
			"1:8",
			"8:1",
		},
		DefaultAspectRatio: "1:1",
	},
	Imagen4Fast: {
		ID:       Imagen4Fast,
		Name:     "Imagen 4 Fast [Deprecated]",
		Provider: "gemini",
		APIModel: "imagen-4.0-fast-generate-001",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.02,
			},
			"1:1": {
				"default": 0.02,
			},
			"3:4": {
				"default": 0.02,
			},
			"4:3": {
				"default": 0.02,
			},
			"9:16": {
				"default": 0.02,
			},
		},
		MaxPromptTokens:       480,
		SupportedQualities:    []string{"default"},
		DefaultQuality:        "default",
		SupportedAspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
		DefaultAspectRatio:    "1:1",
	},
	Imagen40Generate: {
		ID:       Imagen40Generate,
		Name:     "Imagen 4",
		Provider: "gemini",
		APIModel: "imagen-4.0-generate",
		Currency: "USD",
	},
	Imagen4: {
		ID:       Imagen4,
		Name:     "Imagen 4 [Deprecated]",
		Provider: "gemini",
		APIModel: "imagen-4.0-generate-001",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.04,
			},
			"1:1": {
				"default": 0.04,
			},
			"3:4": {
				"default": 0.04,
			},
			"4:3": {
				"default": 0.04,
			},
			"9:16": {
				"default": 0.04,
			},
		},
		MaxPromptTokens:       480,
		SupportedSizes:        []string{"1K", "2K"},
		SupportedQualities:    []string{"default"},
		DefaultQuality:        "default",
		SupportedAspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
		DefaultAspectRatio:    "1:1",
	},
	Imagen4Ultra: {
		ID:       Imagen4Ultra,
		Name:     "Imagen 4 Ultra [Deprecated]",
		Provider: "gemini",
		APIModel: "imagen-4.0-ultra-generate-001",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.06,
			},
			"1:1": {
				"default": 0.06,
			},
			"3:4": {
				"default": 0.06,
			},
			"4:3": {
				"default": 0.06,
			},
			"9:16": {
				"default": 0.06,
			},
		},
		MaxPromptTokens:       480,
		SupportedSizes:        []string{"1K", "2K"},
		SupportedQualities:    []string{"default"},
		DefaultQuality:        "default",
		SupportedAspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
		DefaultAspectRatio:    "1:1",
	},
}
