// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-12
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// groq provider.
//
// models.dev indexes providers rather than serving them, so models it
// stops listing are kept here and reported by the sync instead of
// being deleted. Display names are set when a model is first added and
// carried over from then on.

package groq

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Allam27B              string = "allam-2-7b"
	OrpheusArabicSaudi    string = "canopylabs/orpheus-arabic-saudi"
	OrpheusV1English      string = "canopylabs/orpheus-v1-english"
	Compound              string = "groq/compound"
	CompoundMini          string = "groq/compound-mini"
	Llama3_1_8BInstant    string = "llama-3.1-8b-instant"
	Llama3_3_70BVersatile string = "llama-3.3-70b-versatile"
	Llama4Scout           string = "meta-llama/llama-4-scout-17b-16e-instruct"
	LlamaPromptGuard222M  string = "meta-llama/llama-prompt-guard-2-22m"
	LlamaPromptGuard286M  string = "meta-llama/llama-prompt-guard-2-86m"
	KimiK2                string = "moonshotai/kimi-k2-instruct-0905"
	GPTOss120B            string = "openai/gpt-oss-120b"
	GPTOss20B             string = "openai/gpt-oss-20b"
	GPTOssSafeguard20B    string = "openai/gpt-oss-safeguard-20b"
	Qwen36_27BGroq        string = "qwen/qwen3.6-27b"
	WhisperLargeV3        string = "whisper-large-v3"
	WhisperLargeV3Turbo   string = "whisper-large-v3-turbo"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Allam27B: {
		ID:               Allam27B,
		Name:             "ALLaM-2-7b",
		Provider:         "groq",
		APIModel:         "allam-2-7b",
		Currency:         "USD",
		ContextWindow:    4096,
		DefaultMaxTokens: 4096,
	},
	OrpheusArabicSaudi: {
		ID:               OrpheusArabicSaudi,
		Name:             "Canopy Labs Orpheus Arabic Saudi",
		Provider:         "groq",
		APIModel:         "canopylabs/orpheus-arabic-saudi",
		Currency:         "USD",
		ContextWindow:    4000,
		DefaultMaxTokens: 50000,
	},
	OrpheusV1English: {
		ID:               OrpheusV1English,
		Name:             "Canopy Labs Orpheus V1 English",
		Provider:         "groq",
		APIModel:         "canopylabs/orpheus-v1-english",
		Currency:         "USD",
		ContextWindow:    4000,
		DefaultMaxTokens: 50000,
	},
	Compound: {
		ID:               Compound,
		Name:             "Compound",
		Provider:         "groq",
		APIModel:         "groq/compound",
		Currency:         "USD",
		ContextWindow:    131072,
		DefaultMaxTokens: 8192,
	},
	CompoundMini: {
		ID:               CompoundMini,
		Name:             "Compound Mini",
		Provider:         "groq",
		APIModel:         "groq/compound-mini",
		Currency:         "USD",
		ContextWindow:    131072,
		DefaultMaxTokens: 8192,
	},
	Llama3_1_8BInstant: {
		ID:               Llama3_1_8BInstant,
		Name:             "Llama3_1_8BInstant",
		Provider:         "groq",
		APIModel:         "llama-3.1-8b-instant",
		Currency:         "USD",
		CostPer1MIn:      0.05,
		CostPer1MOut:     0.08,
		ContextWindow:    131072,
		DefaultMaxTokens: 131072,
	},
	Llama3_3_70BVersatile: {
		ID:               Llama3_3_70BVersatile,
		Name:             "Llama3_3_70BVersatile",
		Provider:         "groq",
		APIModel:         "llama-3.3-70b-versatile",
		Currency:         "USD",
		CostPer1MIn:      0.59,
		CostPer1MOut:     0.79,
		ContextWindow:    131072,
		DefaultMaxTokens: 32768,
	},
	Llama4Scout: {
		ID:                    Llama4Scout,
		Name:                  "Llama4Scout",
		Provider:              "groq",
		APIModel:              "meta-llama/llama-4-scout-17b-16e-instruct",
		Currency:              "USD",
		CostPer1MIn:           0.11,
		CostPer1MOut:          0.34,
		ContextWindow:         128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	LlamaPromptGuard222M: {
		ID:               LlamaPromptGuard222M,
		Name:             "Llama Prompt Guard 2 22M",
		Provider:         "groq",
		APIModel:         "meta-llama/llama-prompt-guard-2-22m",
		Currency:         "USD",
		CostPer1MIn:      0.03,
		CostPer1MOut:     0.03,
		ContextWindow:    512,
		DefaultMaxTokens: 512,
	},
	LlamaPromptGuard286M: {
		ID:               LlamaPromptGuard286M,
		Name:             "Prompt Guard 2 86M",
		Provider:         "groq",
		APIModel:         "meta-llama/llama-prompt-guard-2-86m",
		Currency:         "USD",
		CostPer1MIn:      0.04,
		CostPer1MOut:     0.04,
		ContextWindow:    512,
		DefaultMaxTokens: 512,
	},
	KimiK2: {
		ID:               KimiK2,
		Name:             "Kimi K2",
		Provider:         "groq",
		APIModel:         "moonshotai/kimi-k2-instruct-0905",
		Currency:         "USD",
		CostPer1MIn:      1,
		CostPer1MOut:     3,
		ContextWindow:    262144,
		DefaultMaxTokens: 16384,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "GPT-OSS 120B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.075,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOss20B: {
		ID:                    GPTOss20B,
		Name:                  "GPT-OSS 20B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-20b",
		Currency:              "USD",
		CostPer1MIn:           0.075,
		CostPer1MOut:          0.3,
		CostPer1MInCached:     0.0375,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOssSafeguard20B: {
		ID:                    GPTOssSafeguard20B,
		Name:                  "GPT-OSS Safeguard 20B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-safeguard-20b",
		Currency:              "USD",
		CostPer1MIn:           0.075,
		CostPer1MOut:          0.3,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Qwen36_27BGroq: {
		ID:                    Qwen36_27BGroq,
		Name:                  "Qwen3.6 27B",
		Provider:              "groq",
		APIModel:              "qwen/qwen3.6-27b",
		Currency:              "USD",
		CostPer1MIn:           0.6,
		CostPer1MOut:          3,
		CostPer1MInCached:     0.3,
		ContextWindow:         131072,
		DefaultMaxTokens:      16384,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	WhisperLargeV3: {
		ID:       WhisperLargeV3,
		Name:     "Whisper",
		Provider: "groq",
		APIModel: "whisper-large-v3",
		Currency: "USD",
	},
	WhisperLargeV3Turbo: {
		ID:       WhisperLargeV3Turbo,
		Name:     "Whisper Large V3 Turbo",
		Provider: "groq",
		APIModel: "whisper-large-v3-turbo",
		Currency: "USD",
	},
}
