// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package groq

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Compound             string = "groq/compound"
	CompoundMini         string = "groq/compound-mini"
	LlamaPromptGuard222M string = "meta-llama/llama-prompt-guard-2-22m"
	LlamaPromptGuard286M string = "meta-llama/llama-prompt-guard-2-86m"
	MinimaxM27           string = "minimaxai/minimax-m2.7"
	GPTOss120B           string = "openai/gpt-oss-120b"
	GPTOss20B            string = "openai/gpt-oss-20b"
	GPTOssSafeguard20B   string = "openai/gpt-oss-safeguard-20b"
	Qwen36_27BGroq       string = "qwen/qwen3.6-27b"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Compound: {
		ID:                    Compound,
		Name:                  "Compound",
		Provider:              "groq",
		APIModel:              "groq/compound",
		Currency:              "USD",
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	CompoundMini: {
		ID:                    CompoundMini,
		Name:                  "Compound Mini",
		Provider:              "groq",
		APIModel:              "groq/compound-mini",
		Currency:              "USD",
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	LlamaPromptGuard222M: {
		ID:               LlamaPromptGuard222M,
		Name:             "Llama Prompt Guard 2 22M",
		Provider:         "groq",
		APIModel:         "meta-llama/llama-prompt-guard-2-22m",
		Currency:         "USD",
		CostPer1MIn:      0.03,
		CostPer1MOut:     0.03,
		ContextWindow:    512,
		DefaultMaxTokens: 512,
	},
	LlamaPromptGuard286M: {
		ID:                    LlamaPromptGuard286M,
		Name:                  "Prompt Guard 2 86M",
		Provider:              "groq",
		APIModel:              "meta-llama/llama-prompt-guard-2-86m",
		Currency:              "USD",
		CostPer1MIn:           0.04,
		CostPer1MOut:          0.04,
		ContextWindow:         512,
		DefaultMaxTokens:      512,
		SupportsStructuredOut: true,
	},
	MinimaxM27: {
		ID:                    MinimaxM27,
		Name:                  "MiniMax M2.7",
		Provider:              "groq",
		APIModel:              "minimaxai/minimax-m2.7",
		Currency:              "USD",
		ContextWindow:         196608,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "GPT-OSS 120B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.075,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOss20B: {
		ID:                    GPTOss20B,
		Name:                  "GPT-OSS 20B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-20b",
		Currency:              "USD",
		CostPer1MIn:           0.075,
		CostPer1MOut:          0.3,
		CostPer1MInCached:     0.037,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GPTOssSafeguard20B: {
		ID:                    GPTOssSafeguard20B,
		Name:                  "GPT-OSS Safeguard 20B",
		Provider:              "groq",
		APIModel:              "openai/gpt-oss-safeguard-20b",
		Currency:              "USD",
		CostPer1MIn:           0.075,
		CostPer1MOut:          0.3,
		CostPer1MInCached:     0.037,
		ContextWindow:         131072,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Qwen36_27BGroq: {
		ID:                    Qwen36_27BGroq,
		Name:                  "Qwen3.6 27B",
		Provider:              "groq",
		APIModel:              "qwen/qwen3.6-27b",
		Currency:              "USD",
		CostPer1MIn:           0.6,
		CostPer1MOut:          3,
		CostPer1MInCached:     0.3,
		ContextWindow:         131072,
		DefaultMaxTokens:      16384,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
