// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-09-05
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package azure

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	Flex            string = "azure.flex"
	FlexRef         string = "azure.flex-ref"
	Flux11Pro       string = "azure.flux-1.1-pro"
	Flux2Pro        string = "azure.flux-2-pro"
	Flux2ProInitial string = "azure.flux-2-pro-initial"
	Flux2ProRef     string = "azure.flux-2-pro-ref"
	Flux2Ref        string = "azure.flux-2-ref"
	GPTImage1       string = "azure.gpt-image-1"
	GPTImage2       string = "azure.gpt-image-2"
	GPTImg1Mini     string = "azure.gpt-img-1-mini"
	GPTImg15        string = "azure.gpt-img-1.5"
	ImageDallE2     string = "azure.image-dall-e-2"
	ImageDallE3     string = "azure.image-dall-e-3"
	KontextPro      string = "azure.kontext-pro"
	MaiCyber1Flash  string = "azure.mai-cyber-1-flash"
	MaiImage2       string = "azure.mai-image-2"
	MaiImage25      string = "azure.mai-image-2.5"
	MaiImage25Flash string = "azure.mai-image-2.5-flash"
	MaiImage25Pro   string = "azure.mai-image-2.5-pro"
	MaiImage2E      string = "azure.mai-image-2e"
	MaiThinking1    string = "azure.mai-thinking-1"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	Flex: {
		ID:              Flex,
		Name:            "FLUX.2-flex",
		Provider:        "azure",
		APIModel:        "flex",
		Currency:        "USD",
		MaxPromptTokens: 32768,
	},
	FlexRef: {
		ID:              FlexRef,
		Name:            "FLUX.2-flex",
		Provider:        "azure",
		APIModel:        "flex-ref",
		Currency:        "USD",
		MaxPromptTokens: 32768,
	},
	Flux11Pro: {
		ID:              Flux11Pro,
		Name:            "FLUX-1.1-pro",
		Provider:        "azure",
		APIModel:        "flux-1.1-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2Pro: {
		ID:              Flux2Pro,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2ProInitial: {
		ID:              Flux2ProInitial,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro-initial",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2ProRef: {
		ID:              Flux2ProRef,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro-ref",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2Ref: {
		ID:       Flux2Ref,
		Name:     "",
		Provider: "azure",
		APIModel: "flux-2-ref",
		Currency: "USD",
	},
	GPTImage1: {
		ID:       GPTImage1,
		Name:     "gpt-image-1",
		Provider: "azure",
		APIModel: "gpt-image-1",
		Currency: "USD",
	},
	GPTImage2: {
		ID:       GPTImage2,
		Name:     "gpt-image-2",
		Provider: "azure",
		APIModel: "gpt-image-2",
		Currency: "USD",
	},
	GPTImg1Mini: {
		ID:       GPTImg1Mini,
		Name:     "gpt-image-1-mini",
		Provider: "azure",
		APIModel: "gpt-img-1-mini",
		Currency: "USD",
	},
	GPTImg15: {
		ID:       GPTImg15,
		Name:     "gpt-image-1.5",
		Provider: "azure",
		APIModel: "gpt-img-1.5",
		Currency: "USD",
	},
	ImageDallE2: {
		ID:       ImageDallE2,
		Name:     "",
		Provider: "azure",
		APIModel: "image-dall-e-2",
		Currency: "USD",
	},
	ImageDallE3: {
		ID:       ImageDallE3,
		Name:     "dall-e-3",
		Provider: "azure",
		APIModel: "image-dall-e-3",
		Currency: "USD",
	},
	KontextPro: {
		ID:              KontextPro,
		Name:            "FLUX.1-Kontext-pro",
		Provider:        "azure",
		APIModel:        "kontext-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiCyber1Flash: {
		ID:       MaiCyber1Flash,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-cyber-1-flash",
		Currency: "USD",
	},
	MaiImage2: {
		ID:       MaiImage2,
		Name:     "MAI-Image-2",
		Provider: "azure",
		APIModel: "mai-image-2",
		Currency: "USD",
	},
	MaiImage25: {
		ID:              MaiImage25,
		Name:            "MAI-Image-2.5",
		Provider:        "azure",
		APIModel:        "mai-image-2.5",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiImage25Flash: {
		ID:              MaiImage25Flash,
		Name:            "MAI-Image-2.5-Flash",
		Provider:        "azure",
		APIModel:        "mai-image-2.5-flash",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiImage25Pro: {
		ID:              MaiImage25Pro,
		Name:            "MAI-Image-2.5-Pro",
		Provider:        "azure",
		APIModel:        "mai-image-2.5-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiImage2E: {
		ID:              MaiImage2E,
		Name:            "MAI-Image-2e",
		Provider:        "azure",
		APIModel:        "mai-image-2e",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiThinking1: {
		ID:              MaiThinking1,
		Name:            "MAI-Thinking-1",
		Provider:        "azure",
		APIModel:        "mai-thinking-1",
		Currency:        "USD",
		MaxPromptTokens: 256000,
	},
}
