// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package azure

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	Flex            string = "azure.flex"
	FlexRef         string = "azure.flex-ref"
	Flux11Pro       string = "azure.flux-1.1-pro"
	Flux2Pro        string = "azure.flux-2-pro"
	Flux2ProInitial string = "azure.flux-2-pro-initial"
	Flux2ProRef     string = "azure.flux-2-pro-ref"
	Flux2Ref        string = "azure.flux-2-ref"
	GPTImage1       string = "azure.gpt-image-1"
	GPTImage2       string = "azure.gpt-image-2"
	GPTImg1Mini     string = "azure.gpt-img-1-mini"
	GPTImg15        string = "azure.gpt-img-1.5"
	ImageDallE2     string = "azure.image-dall-e-2"
	ImageDallE3     string = "azure.image-dall-e-3"
	KontextPro      string = "azure.kontext-pro"
	MaiImage2       string = "azure.mai-image-2"
	MaiImage2E      string = "azure.mai-image-2e"
	MaiO            string = "azure.mai-o"
	MaiP            string = "azure.mai-p"
	MaiQ            string = "azure.mai-q"
	MaiR            string = "azure.mai-r"
	MaiS            string = "azure.mai-s"
	MaiT            string = "azure.mai-t"
	MaiU            string = "azure.mai-u"
	MaiV            string = "azure.mai-v"
	MaiW            string = "azure.mai-w"
	MaiX            string = "azure.mai-x"
	MaiY            string = "azure.mai-y"
	MaiZ            string = "azure.mai-z"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	Flex: {
		ID:              Flex,
		Name:            "FLUX.2-flex",
		Provider:        "azure",
		APIModel:        "flex",
		Currency:        "USD",
		MaxPromptTokens: 32768,
	},
	FlexRef: {
		ID:              FlexRef,
		Name:            "FLUX.2-flex",
		Provider:        "azure",
		APIModel:        "flex-ref",
		Currency:        "USD",
		MaxPromptTokens: 32768,
	},
	Flux11Pro: {
		ID:              Flux11Pro,
		Name:            "FLUX-1.1-pro",
		Provider:        "azure",
		APIModel:        "flux-1.1-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2Pro: {
		ID:              Flux2Pro,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2ProInitial: {
		ID:              Flux2ProInitial,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro-initial",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2ProRef: {
		ID:              Flux2ProRef,
		Name:            "FLUX.2-pro",
		Provider:        "azure",
		APIModel:        "flux-2-pro-ref",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	Flux2Ref: {
		ID:       Flux2Ref,
		Name:     "",
		Provider: "azure",
		APIModel: "flux-2-ref",
		Currency: "USD",
	},
	GPTImage1: {
		ID:       GPTImage1,
		Name:     "gpt-image-1",
		Provider: "azure",
		APIModel: "gpt-image-1",
		Currency: "USD",
	},
	GPTImage2: {
		ID:       GPTImage2,
		Name:     "gpt-image-2",
		Provider: "azure",
		APIModel: "gpt-image-2",
		Currency: "USD",
	},
	GPTImg1Mini: {
		ID:       GPTImg1Mini,
		Name:     "gpt-image-1-mini",
		Provider: "azure",
		APIModel: "gpt-img-1-mini",
		Currency: "USD",
	},
	GPTImg15: {
		ID:       GPTImg15,
		Name:     "gpt-image-1.5",
		Provider: "azure",
		APIModel: "gpt-img-1.5",
		Currency: "USD",
	},
	ImageDallE2: {
		ID:       ImageDallE2,
		Name:     "",
		Provider: "azure",
		APIModel: "image-dall-e-2",
		Currency: "USD",
	},
	ImageDallE3: {
		ID:       ImageDallE3,
		Name:     "dall-e-3",
		Provider: "azure",
		APIModel: "image-dall-e-3",
		Currency: "USD",
	},
	KontextPro: {
		ID:              KontextPro,
		Name:            "FLUX.1-Kontext-pro",
		Provider:        "azure",
		APIModel:        "kontext-pro",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiImage2: {
		ID:       MaiImage2,
		Name:     "MAI-Image-2",
		Provider: "azure",
		APIModel: "mai-image-2",
		Currency: "USD",
	},
	MaiImage2E: {
		ID:              MaiImage2E,
		Name:            "MAI-Image-2e",
		Provider:        "azure",
		APIModel:        "mai-image-2e",
		Currency:        "USD",
		MaxPromptTokens: 131072,
	},
	MaiO: {
		ID:       MaiO,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-o",
		Currency: "USD",
	},
	MaiP: {
		ID:       MaiP,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-p",
		Currency: "USD",
	},
	MaiQ: {
		ID:       MaiQ,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-q",
		Currency: "USD",
	},
	MaiR: {
		ID:       MaiR,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-r",
		Currency: "USD",
	},
	MaiS: {
		ID:       MaiS,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-s",
		Currency: "USD",
	},
	MaiT: {
		ID:       MaiT,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-t",
		Currency: "USD",
	},
	MaiU: {
		ID:       MaiU,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-u",
		Currency: "USD",
	},
	MaiV: {
		ID:       MaiV,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-v",
		Currency: "USD",
	},
	MaiW: {
		ID:       MaiW,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-w",
		Currency: "USD",
	},
	MaiX: {
		ID:       MaiX,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-x",
		Currency: "USD",
	},
	MaiY: {
		ID:       MaiY,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-y",
		Currency: "USD",
	},
	MaiZ: {
		ID:       MaiZ,
		Name:     "",
		Provider: "azure",
		APIModel: "mai-z",
		Currency: "USD",
	},
}
