// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	ChatgptImageLatest string = "chatgpt-image-latest"
	GPTImage1          string = "gpt-image-1"
	GPTImage1Mini      string = "gpt-image-1-mini"
	GPTImage15         string = "gpt-image-1.5"
	GPTImage2          string = "gpt-image-2"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	ChatgptImageLatest: {
		ID:       ChatgptImageLatest,
		Name:     "chatgpt-image-latest",
		Provider: "openai",
		APIModel: "chatgpt-image-latest",
		Currency: "USD",
	},
	GPTImage1: {
		ID:       GPTImage1,
		Name:     "GPT Image 1",
		Provider: "openai",
		APIModel: "gpt-image-1",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.011},
		},
	},
	GPTImage1Mini: {
		ID:       GPTImage1Mini,
		Name:     "gpt-image-1-mini",
		Provider: "openai",
		APIModel: "gpt-image-1-mini",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.005},
		},
	},
	GPTImage15: {
		ID:       GPTImage15,
		Name:     "GPT Image 1.5",
		Provider: "openai",
		APIModel: "gpt-image-1.5",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"1024x1024": {
				"high":   0.133,
				"low":    0.009,
				"medium": 0.034,
			},
			"1024x1536": {
				"high":   0.2,
				"low":    0.013,
				"medium": 0.05,
			},
			"1536x1024": {
				"high":   0.2,
				"low":    0.013,
				"medium": 0.05,
			},
		},
		MaxPromptTokens:    4000,
		SupportedSizes:     []string{"1024x1024", "1024x1536", "1536x1024"},
		DefaultSize:        "1024x1024",
		SupportedQualities: []string{"low", "medium", "high"},
		DefaultQuality:     "medium",
	},
	GPTImage2: {
		ID:       GPTImage2,
		Name:     "GPT Image 2",
		Provider: "openai",
		APIModel: "gpt-image-2",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"1024x1024": {
				"high":   0.211,
				"low":    0.006,
				"medium": 0.053,
			},
			"1024x1536": {
				"high":   0.165,
				"low":    0.005,
				"medium": 0.041,
			},
			"1536x1024": {
				"high":   0.165,
				"low":    0.005,
				"medium": 0.041,
			},
		},
		MaxPromptTokens: 4000,
		SupportedSizes: []string{
			"1024x1024",
			"1024x1536",
			"1536x1024",
			"2048x1152",
			"2048x2048",
			"2160x3840",
			"3840x2160",
		},
		DefaultSize:        "1024x1024",
		SupportedQualities: []string{"auto", "high", "low", "medium"},
		DefaultQuality:     "medium",
	},
}
