// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package mistral

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Codestral2508            string = "codestral-2508"
	Devstral2                string = "devstral-2"
	DevstralMedium2507       string = "devstral-medium-2507"
	DevstralSmall2507        string = "devstral-small-2507"
	LabsDevstralSmall2512    string = "labs-devstral-small-2512"
	LabsLeanstral15          string = "labs-leanstral-1-5"
	LabsMistralSmallCreative string = "labs-mistral-small-creative"
	MagistralMedium2509      string = "magistral-medium-2509"
	MagistralSmall2509       string = "magistral-small-2509"
	Ministral14B2512         string = "ministral-14b-2512"
	Ministral3B2410          string = "ministral-3b-2410"
	Ministral3B2512          string = "ministral-3b-2512"
	Ministral8B2410          string = "ministral-8b-2410"
	Ministral8B2512          string = "ministral-8b-2512"
	MistralLarge2411         string = "mistral-large-2411"
	Large3                   string = "mistral-large-3"
	Medium3                  string = "mistral-medium-3"
	Medium31                 string = "mistral-medium-3.1"
	MistralMedium35          string = "mistral-medium-3-5"
	Small32                  string = "mistral-small-3.2"
	Small4                   string = "mistral-small-4"
	OpenMistralNemo2407      string = "open-mistral-nemo-2407"
	Pixtral12B2409           string = "pixtral-12b-2409"
	PixtralLarge2411         string = "pixtral-large-2411"
	VoxtralMini2507          string = "voxtral-mini-2507"
	VoxtralSmall2507         string = "voxtral-small-2507"
	ZaiGLM52                 string = "zai-glm-5-2"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Codestral2508: {
		ID:                    Codestral2508,
		Name:                  "Codestral",
		Provider:              "mistral",
		APIModel:              "codestral-2508",
		Currency:              "USD",
		CostPer1MIn:           0.3,
		CostPer1MOut:          0.9,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	Devstral2: {
		ID:                    Devstral2,
		Name:                  "Devstral 2",
		Provider:              "mistral",
		APIModel:              "devstral-2512",
		Currency:              "USD",
		CostPer1MIn:           0.4,
		CostPer1MOut:          2,
		ContextWindow:         256000,
		DefaultMaxTokens:      262144,
		SupportsStructuredOut: true,
	},
	DevstralMedium2507: {
		ID:                    DevstralMedium2507,
		Name:                  "Devstral Medium",
		Provider:              "mistral",
		APIModel:              "devstral-medium-2507",
		Currency:              "USD",
		CostPer1MIn:           0.4,
		CostPer1MOut:          2,
		ContextWindow:         128000,
		DefaultMaxTokens:      128000,
		SupportsStructuredOut: true,
	},
	DevstralSmall2507: {
		ID:                    DevstralSmall2507,
		Name:                  "Devstral Small",
		Provider:              "mistral",
		APIModel:              "devstral-small-2507",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.3,
		ContextWindow:         128000,
		DefaultMaxTokens:      128000,
		SupportsStructuredOut: true,
	},
	LabsDevstralSmall2512: {
		ID:                    LabsDevstralSmall2512,
		Name:                  "Devstral Small 2",
		Provider:              "mistral",
		APIModel:              "labs-devstral-small-2512",
		Currency:              "USD",
		ContextWindow:         256000,
		DefaultMaxTokens:      256000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	LabsLeanstral15: {
		ID:                    LabsLeanstral15,
		Name:                  "Leanstral 1.5",
		Provider:              "mistral",
		APIModel:              "labs-leanstral-1-5",
		Currency:              "USD",
		ContextWindow:         256000,
		DefaultMaxTokens:      128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	LabsMistralSmallCreative: {
		ID:                    LabsMistralSmallCreative,
		Name:                  "Mistral Small Creative",
		Provider:              "mistral",
		APIModel:              "labs-mistral-small-creative",
		Currency:              "USD",
		ContextWindow:         32000,
		DefaultMaxTokens:      8000,
		SupportsStructuredOut: true,
	},
	MagistralMedium2509: {
		ID:                  MagistralMedium2509,
		Name:                "Magistral Medium 1.2",
		Provider:            "mistral",
		APIModel:            "magistral-medium-2509",
		Currency:            "USD",
		ContextWindow:       128000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	MagistralSmall2509: {
		ID:                  MagistralSmall2509,
		Name:                "Magistral Small 1.2",
		Provider:            "mistral",
		APIModel:            "magistral-small-2509",
		Currency:            "USD",
		ContextWindow:       128000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Ministral14B2512: {
		ID:                    Ministral14B2512,
		Name:                  "Ministral 3 14B",
		Provider:              "mistral",
		APIModel:              "ministral-14b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.2,
		CostPer1MOut:          0.2,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3B2410: {
		ID:                    Ministral3B2410,
		Name:                  "Ministral 3B",
		Provider:              "mistral",
		APIModel:              "ministral-3b-2410",
		Currency:              "USD",
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	Ministral3B2512: {
		ID:                    Ministral3B2512,
		Name:                  "Ministral 3 3B",
		Provider:              "mistral",
		APIModel:              "ministral-3b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.1,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral8B2410: {
		ID:                    Ministral8B2410,
		Name:                  "Ministral 8B",
		Provider:              "mistral",
		APIModel:              "ministral-8b-2410",
		Currency:              "USD",
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	Ministral8B2512: {
		ID:                    Ministral8B2512,
		Name:                  "Ministral 3 8B",
		Provider:              "mistral",
		APIModel:              "ministral-8b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.15,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralLarge2411: {
		ID:                    MistralLarge2411,
		Name:                  "Mistral Large 2.1",
		Provider:              "mistral",
		APIModel:              "mistral-large-2411",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          6,
		ContextWindow:         128000,
		DefaultMaxTokens:      16384,
		SupportsStructuredOut: true,
	},
	Large3: {
		ID:                    Large3,
		Name:                  "Mistral Large 3",
		Provider:              "mistral",
		APIModel:              "mistral-large-2512",
		Currency:              "USD",
		CostPer1MIn:           0.5,
		CostPer1MOut:          1.5,
		ContextWindow:         256000,
		DefaultMaxTokens:      262144,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Medium3: {
		ID:                    Medium3,
		Name:                  "Mistral Medium 3",
		Provider:              "mistral",
		APIModel:              "mistral-medium-2505",
		Currency:              "USD",
		CostPer1MIn:           0.4,
		CostPer1MOut:          2,
		ContextWindow:         128000,
		DefaultMaxTokens:      131072,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Medium31: {
		ID:                    Medium31,
		Name:                  "Mistral Medium 3.1",
		Provider:              "mistral",
		APIModel:              "mistral-medium-2508",
		Currency:              "USD",
		CostPer1MIn:           0.4,
		CostPer1MOut:          2,
		ContextWindow:         128000,
		DefaultMaxTokens:      262144,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralMedium35: {
		ID:                    MistralMedium35,
		Name:                  "Mistral Medium 3.5",
		Provider:              "mistral",
		APIModel:              "mistral-medium-3-5",
		Currency:              "USD",
		CostPer1MIn:           1.5,
		CostPer1MOut:          7.5,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Small32: {
		ID:                    Small32,
		Name:                  "Mistral Small 3.2",
		Provider:              "mistral",
		APIModel:              "mistral-small-2506",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.3,
		ContextWindow:         128000,
		DefaultMaxTokens:      16384,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Small4: {
		ID:                    Small4,
		Name:                  "Mistral Small 4",
		Provider:              "mistral",
		APIModel:              "mistral-small-2603",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		ContextWindow:         256000,
		DefaultMaxTokens:      256000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	OpenMistralNemo2407: {
		ID:                    OpenMistralNemo2407,
		Name:                  "Mistral Nemo 12B",
		Provider:              "mistral",
		APIModel:              "open-mistral-nemo-2407",
		Currency:              "USD",
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	Pixtral12B2409: {
		ID:                    Pixtral12B2409,
		Name:                  "Pixtral 12B",
		Provider:              "mistral",
		APIModel:              "pixtral-12b-2409",
		Currency:              "USD",
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	PixtralLarge2411: {
		ID:                    PixtralLarge2411,
		Name:                  "Pixtral Large",
		Provider:              "mistral",
		APIModel:              "pixtral-large-2411",
		Currency:              "USD",
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	VoxtralMini2507: {
		ID:                    VoxtralMini2507,
		Name:                  "Voxtral Mini",
		Provider:              "mistral",
		APIModel:              "voxtral-mini-2507",
		Currency:              "USD",
		ContextWindow:         32000,
		DefaultMaxTokens:      8000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	VoxtralSmall2507: {
		ID:                    VoxtralSmall2507,
		Name:                  "Voxtral Small",
		Provider:              "mistral",
		APIModel:              "voxtral-small-2507",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.4,
		ContextWindow:         32000,
		DefaultMaxTokens:      8000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	ZaiGLM52: {
		ID:                    ZaiGLM52,
		Name:                  "Z.ai GLM 5.2",
		Provider:              "mistral",
		APIModel:              "zai-glm-5-2",
		Currency:              "USD",
		CostPer1MIn:           1.4,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.14,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
