// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-12
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// mistral provider.
//
// models.dev indexes providers rather than serving them, so models it
// stops listing are kept here and reported by the sync instead of
// being deleted. Display names are set when a model is first added and
// carried over from then on.

package mistral

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Codestral             string = "codestral"
	CodestralLatest       string = "codestral-latest"
	Devstral2             string = "devstral-2"
	DevstralLatest        string = "devstral-latest"
	DevstralMedium2507    string = "devstral-medium-2507"
	DevstralMediumLatest  string = "devstral-medium-latest"
	DevstralSmall2505     string = "devstral-small-2505"
	DevstralSmall2507     string = "devstral-small-2507"
	LabsDevstralSmall2512 string = "labs-devstral-small-2512"
	MagistralMedium12     string = "magistral-medium-1.2"
	MagistralMediumLatest string = "magistral-medium-latest"
	MagistralSmall        string = "magistral-small"
	MagistralSmall12      string = "magistral-small-1.2"
	Ministral3_14B        string = "ministral-3-14b"
	Ministral3_3B         string = "ministral-3-3b"
	Ministral3BLatest     string = "ministral-3b-latest"
	Ministral3_8B         string = "ministral-3-8b"
	Ministral8BLatest     string = "ministral-8b-latest"
	Mistral7B             string = "mistral-7b"
	MistralEmbed          string = "mistral-embed"
	MistralLarge2411      string = "mistral-large-2411"
	Large3                string = "mistral-large-3"
	MistralLargeLatest    string = "mistral-large-latest"
	Medium3               string = "mistral-medium-3"
	Medium31              string = "mistral-medium-3.1"
	Medium35              string = "mistral-medium-3.5"
	MistralMediumLatest   string = "mistral-medium-latest"
	MistralNemo           string = "mistral-nemo-2"
	Small32               string = "mistral-small-3.2"
	Small4                string = "mistral-small-4"
	MistralSmallLatest    string = "mistral-small-latest"
	Mixtral8x7B           string = "mixtral-8x7b"
	OpenMistral7B         string = "open-mistral-7b"
	Nemo                  string = "mistral-nemo"
	OpenMixtral8X22B      string = "open-mixtral-8x22b"
	OpenMixtral8X7B       string = "open-mixtral-8x7b"
	Pixtral12B            string = "pixtral-12b"
	PixtralLargeLatest    string = "pixtral-large-latest"
	VoxtralMiniLatest     string = "voxtral-mini-latest"
	VoxtralMiniTTSLatest  string = "voxtral-mini-tts-latest"
	VoxtralSmallLatest    string = "voxtral-small-latest"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Codestral: {
		ID:                    Codestral,
		Name:                  "Codestral",
		Provider:              "mistral",
		APIModel:              "codestral-2508",
		Currency:              "USD",
		CostPer1MIn:           0.3,
		CostPer1MOut:          0.9,
		ContextWindow:         256000,
		DefaultMaxTokens:      8192,
		SupportsStructuredOut: true,
	},
	CodestralLatest: {
		ID:               CodestralLatest,
		Name:             "Codestral (latest)",
		Provider:         "mistral",
		APIModel:         "codestral-latest",
		Currency:         "USD",
		CostPer1MIn:      0.3,
		CostPer1MOut:     0.9,
		ContextWindow:    256000,
		DefaultMaxTokens: 4096,
	},
	Devstral2: {
		ID:               Devstral2,
		Name:             "Devstral 2",
		Provider:         "mistral",
		APIModel:         "devstral-2512",
		Currency:         "USD",
		CostPer1MIn:      0.4,
		CostPer1MOut:     2,
		ContextWindow:    262144,
		DefaultMaxTokens: 262144,
	},
	DevstralLatest: {
		ID:               DevstralLatest,
		Name:             "Devstral 2",
		Provider:         "mistral",
		APIModel:         "devstral-latest",
		Currency:         "USD",
		CostPer1MIn:      0.4,
		CostPer1MOut:     2,
		ContextWindow:    262144,
		DefaultMaxTokens: 262144,
	},
	DevstralMedium2507: {
		ID:               DevstralMedium2507,
		Name:             "Devstral Medium",
		Provider:         "mistral",
		APIModel:         "devstral-medium-2507",
		Currency:         "USD",
		CostPer1MIn:      0.4,
		CostPer1MOut:     2,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	DevstralMediumLatest: {
		ID:               DevstralMediumLatest,
		Name:             "Devstral 2 (latest)",
		Provider:         "mistral",
		APIModel:         "devstral-medium-latest",
		Currency:         "USD",
		CostPer1MIn:      0.4,
		CostPer1MOut:     2,
		ContextWindow:    262144,
		DefaultMaxTokens: 262144,
	},
	DevstralSmall2505: {
		ID:               DevstralSmall2505,
		Name:             "Devstral Small 2505",
		Provider:         "mistral",
		APIModel:         "devstral-small-2505",
		Currency:         "USD",
		CostPer1MIn:      0.1,
		CostPer1MOut:     0.3,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	DevstralSmall2507: {
		ID:               DevstralSmall2507,
		Name:             "Devstral Small",
		Provider:         "mistral",
		APIModel:         "devstral-small-2507",
		Currency:         "USD",
		CostPer1MIn:      0.1,
		CostPer1MOut:     0.3,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	LabsDevstralSmall2512: {
		ID:               LabsDevstralSmall2512,
		Name:             "Devstral Small 2",
		Provider:         "mistral",
		APIModel:         "labs-devstral-small-2512",
		Currency:         "USD",
		ContextWindow:    256000,
		DefaultMaxTokens: 256000,
	},
	MagistralMedium12: {
		ID:                    MagistralMedium12,
		Name:                  "Magistral Medium 1.2",
		Provider:              "mistral",
		APIModel:              "magistral-medium-2509",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          5,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MagistralMediumLatest: {
		ID:               MagistralMediumLatest,
		Name:             "Magistral Medium (latest)",
		Provider:         "mistral",
		APIModel:         "magistral-medium-latest",
		Currency:         "USD",
		CostPer1MIn:      2,
		CostPer1MOut:     5,
		ContextWindow:    128000,
		DefaultMaxTokens: 16384,
		CanReason:        true,
	},
	MagistralSmall: {
		ID:               MagistralSmall,
		Name:             "Magistral Small",
		Provider:         "mistral",
		APIModel:         "magistral-small",
		Currency:         "USD",
		CostPer1MIn:      0.5,
		CostPer1MOut:     1.5,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
		CanReason:        true,
	},
	MagistralSmall12: {
		ID:                    MagistralSmall12,
		Name:                  "Magistral Small 1.2",
		Provider:              "mistral",
		APIModel:              "magistral-small-2509",
		Currency:              "USD",
		CostPer1MIn:           0.5,
		CostPer1MOut:          1.5,
		ContextWindow:         128000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3_14B: {
		ID:                    Ministral3_14B,
		Name:                  "Ministral 3 14B",
		Provider:              "mistral",
		APIModel:              "ministral-14b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.2,
		CostPer1MOut:          0.2,
		ContextWindow:         262144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3_3B: {
		ID:                    Ministral3_3B,
		Name:                  "Ministral 3 3B",
		Provider:              "mistral",
		APIModel:              "ministral-3b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.1,
		ContextWindow:         131072,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral3BLatest: {
		ID:               Ministral3BLatest,
		Name:             "Ministral 3B (latest)",
		Provider:         "mistral",
		APIModel:         "ministral-3b-latest",
		Currency:         "USD",
		CostPer1MIn:      0.04,
		CostPer1MOut:     0.04,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	Ministral3_8B: {
		ID:                    Ministral3_8B,
		Name:                  "Ministral 3 8B",
		Provider:              "mistral",
		APIModel:              "ministral-8b-2512",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.15,
		ContextWindow:         262144,
		DefaultMaxTokens:      8192,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Ministral8BLatest: {
		ID:               Ministral8BLatest,
		Name:             "Ministral 8B (latest)",
		Provider:         "mistral",
		APIModel:         "ministral-8b-latest",
		Currency:         "USD",
		CostPer1MIn:      0.1,
		CostPer1MOut:     0.1,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	Mistral7B: {
		ID:               Mistral7B,
		Name:             "Mistral 7B Instruct",
		Provider:         "mistral",
		APIModel:         "mistral-7b-instruct-v0.3",
		Currency:         "USD",
		CostPer1MIn:      0.028,
		CostPer1MOut:     0.054,
		ContextWindow:    32768,
		DefaultMaxTokens: 4096,
	},
	MistralEmbed: {
		ID:               MistralEmbed,
		Name:             "Mistral Embed",
		Provider:         "mistral",
		APIModel:         "mistral-embed",
		Currency:         "USD",
		CostPer1MIn:      0.1,
		ContextWindow:    8000,
		DefaultMaxTokens: 3072,
	},
	MistralLarge2411: {
		ID:               MistralLarge2411,
		Name:             "Mistral Large 2.1",
		Provider:         "mistral",
		APIModel:         "mistral-large-2411",
		Currency:         "USD",
		CostPer1MIn:      2,
		CostPer1MOut:     6,
		ContextWindow:    131072,
		DefaultMaxTokens: 16384,
	},
	Large3: {
		ID:                  Large3,
		Name:                "Mistral Large 3",
		Provider:            "mistral",
		APIModel:            "mistral-large-2512",
		Currency:            "USD",
		CostPer1MIn:         0.5,
		CostPer1MOut:        1.5,
		ContextWindow:       262144,
		DefaultMaxTokens:    262144,
		SupportsAttachments: true,
	},
	MistralLargeLatest: {
		ID:                  MistralLargeLatest,
		Name:                "Mistral Large (latest)",
		Provider:            "mistral",
		APIModel:            "mistral-large-latest",
		Currency:            "USD",
		CostPer1MIn:         0.5,
		CostPer1MOut:        1.5,
		ContextWindow:       262144,
		DefaultMaxTokens:    262144,
		SupportsAttachments: true,
	},
	Medium3: {
		ID:                  Medium3,
		Name:                "Mistral Medium 3",
		Provider:            "mistral",
		APIModel:            "mistral-medium-2505",
		Currency:            "USD",
		CostPer1MIn:         0.4,
		CostPer1MOut:        2,
		ContextWindow:       131072,
		DefaultMaxTokens:    131072,
		SupportsAttachments: true,
	},
	Medium31: {
		ID:                  Medium31,
		Name:                "Mistral Medium 3.1",
		Provider:            "mistral",
		APIModel:            "mistral-medium-2508",
		Currency:            "USD",
		CostPer1MIn:         0.4,
		CostPer1MOut:        2,
		ContextWindow:       262144,
		DefaultMaxTokens:    262144,
		SupportsAttachments: true,
	},
	Medium35: {
		ID:                    Medium35,
		Name:                  "Mistral Medium 3.5",
		Provider:              "mistral",
		APIModel:              "mistral-medium-2604",
		Currency:              "USD",
		CostPer1MIn:           1.5,
		CostPer1MOut:          7.5,
		ContextWindow:         262144,
		DefaultMaxTokens:      262144,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralMediumLatest: {
		ID:                    MistralMediumLatest,
		Name:                  "Mistral Medium (latest)",
		Provider:              "mistral",
		APIModel:              "mistral-medium-latest",
		Currency:              "USD",
		CostPer1MIn:           1.5,
		CostPer1MOut:          7.5,
		ContextWindow:         262144,
		DefaultMaxTokens:      262144,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	MistralNemo: {
		ID:               MistralNemo,
		Name:             "Mistral Nemo",
		Provider:         "mistral",
		APIModel:         "mistral-nemo",
		Currency:         "USD",
		CostPer1MIn:      0.15,
		CostPer1MOut:     0.15,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	Small32: {
		ID:               Small32,
		Name:             "Mistral Small 3.2",
		Provider:         "mistral",
		APIModel:         "mistral-small-2506",
		Currency:         "USD",
		CostPer1MIn:      0.1,
		CostPer1MOut:     0.3,
		ContextWindow:    128000,
		DefaultMaxTokens: 16384,
	},
	Small4: {
		ID:                  Small4,
		Name:                "Mistral Small 4",
		Provider:            "mistral",
		APIModel:            "mistral-small-2603",
		Currency:            "USD",
		CostPer1MIn:         0.15,
		CostPer1MOut:        0.6,
		ContextWindow:       256000,
		DefaultMaxTokens:    256000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	MistralSmallLatest: {
		ID:                  MistralSmallLatest,
		Name:                "Mistral Small (latest)",
		Provider:            "mistral",
		APIModel:            "mistral-small-latest",
		Currency:            "USD",
		CostPer1MIn:         0.15,
		CostPer1MOut:        0.6,
		ContextWindow:       256000,
		DefaultMaxTokens:    256000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Mixtral8x7B: {
		ID:               Mixtral8x7B,
		Name:             "Mixtral 8x7B",
		Provider:         "mistral",
		APIModel:         "mixtral-8x7b-instruct-v0.1",
		Currency:         "USD",
		CostPer1MIn:      0.7,
		CostPer1MOut:     0.7,
		ContextWindow:    32000,
		DefaultMaxTokens: 4096,
	},
	OpenMistral7B: {
		ID:               OpenMistral7B,
		Name:             "Mistral 7B",
		Provider:         "mistral",
		APIModel:         "open-mistral-7b",
		Currency:         "USD",
		CostPer1MIn:      0.25,
		CostPer1MOut:     0.25,
		ContextWindow:    8000,
		DefaultMaxTokens: 8000,
	},
	Nemo: {
		ID:               Nemo,
		Name:             "Mistral Nemo",
		Provider:         "mistral",
		APIModel:         "open-mistral-nemo",
		Currency:         "USD",
		CostPer1MIn:      0.15,
		CostPer1MOut:     0.15,
		ContextWindow:    128000,
		DefaultMaxTokens: 128000,
	},
	OpenMixtral8X22B: {
		ID:               OpenMixtral8X22B,
		Name:             "Mixtral 8x22B",
		Provider:         "mistral",
		APIModel:         "open-mixtral-8x22b",
		Currency:         "USD",
		CostPer1MIn:      2,
		CostPer1MOut:     6,
		ContextWindow:    64000,
		DefaultMaxTokens: 64000,
	},
	OpenMixtral8X7B: {
		ID:               OpenMixtral8X7B,
		Name:             "Mixtral 8x7B",
		Provider:         "mistral",
		APIModel:         "open-mixtral-8x7b",
		Currency:         "USD",
		CostPer1MIn:      0.7,
		CostPer1MOut:     0.7,
		ContextWindow:    32000,
		DefaultMaxTokens: 32000,
	},
	Pixtral12B: {
		ID:                  Pixtral12B,
		Name:                "Pixtral 12B",
		Provider:            "mistral",
		APIModel:            "pixtral-12b",
		Currency:            "USD",
		CostPer1MIn:         0.15,
		CostPer1MOut:        0.15,
		ContextWindow:       128000,
		DefaultMaxTokens:    128000,
		SupportsAttachments: true,
	},
	PixtralLargeLatest: {
		ID:                  PixtralLargeLatest,
		Name:                "Pixtral Large (latest)",
		Provider:            "mistral",
		APIModel:            "pixtral-large-latest",
		Currency:            "USD",
		CostPer1MIn:         2,
		CostPer1MOut:        6,
		ContextWindow:       128000,
		DefaultMaxTokens:    128000,
		SupportsAttachments: true,
	},
	VoxtralMiniLatest: {
		ID:       VoxtralMiniLatest,
		Name:     "Voxtral Mini (latest)",
		Provider: "mistral",
		APIModel: "voxtral-mini-latest",
		Currency: "USD",
	},
	VoxtralMiniTTSLatest: {
		ID:       VoxtralMiniTTSLatest,
		Name:     "Voxtral Mini TTS (latest)",
		Provider: "mistral",
		APIModel: "voxtral-mini-tts-latest",
		Currency: "USD",
	},
	VoxtralSmallLatest: {
		ID:                  VoxtralSmallLatest,
		Name:                "Voxtral Small (latest)",
		Provider:            "mistral",
		APIModel:            "voxtral-small-latest",
		Currency:            "USD",
		CostPer1MIn:         0.1,
		CostPer1MOut:        0.3,
		ContextWindow:       32000,
		DefaultMaxTokens:    32000,
		SupportsAttachments: true,
	},
}
