// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package deepgram

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	Base                  string = "base"
	BaseConversationalai  string = "base-conversationalai"
	BaseFinance           string = "base-finance"
	BaseMeeting           string = "base-meeting"
	BasePhonecall         string = "base-phonecall"
	BaseVideo             string = "base-video"
	BaseVoicemail         string = "base-voicemail"
	Custom                string = "custom"
	Enhanced              string = "enhanced"
	EnhancedFinance       string = "enhanced-finance"
	EnhancedMeeting       string = "enhanced-meeting"
	EnhancedPhonecall     string = "enhanced-phonecall"
	FluxEnglish2          string = "flux-english"
	FluxEnglish           string = "flux-general-en"
	FluxMulti             string = "flux-general-multi"
	FluxMultilingual      string = "flux-multilingual"
	Nova                  string = "nova"
	Nova2                 string = "nova-2"
	Nova2Atc              string = "nova-2-atc"
	Nova2Automotive       string = "nova-2-automotive"
	Nova2Conversationalai string = "nova-2-conversationalai"
	Nova2Drivethru        string = "nova-2-drivethru"
	Nova2Finance          string = "nova-2-finance"
	Nova2Medical          string = "nova-2-medical"
	Nova2Meeting          string = "nova-2-meeting"
	Nova2Phonecall        string = "nova-2-phonecall"
	Nova2Video            string = "nova-2-video"
	Nova2Voicemail        string = "nova-2-voicemail"
	Nova3                 string = "nova-3"
	Nova3Medical          string = "nova-3-medical"
	Nova3Monolingual      string = "nova-3-monolingual"
	Nova3Multilingual     string = "nova-3-multilingual"
	NovaMedical           string = "nova-medical"
	NovaPhonecall         string = "nova-phonecall"
	WhisperBase           string = "whisper-base"
	WhisperLarge          string = "whisper-large"
	WhisperMedium         string = "whisper-medium"
	WhisperSmall          string = "whisper-small"
	WhisperTiny           string = "whisper-tiny"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	Base: {
		ID:                  Base,
		Name:                "base",
		Provider:            "deepgram",
		APIModel:            "base",
		Currency:            "USD",
		CostPer1MIn:         0.0145,
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BaseConversationalai: {
		ID:                  BaseConversationalai,
		Name:                "base-conversationalai",
		Provider:            "deepgram",
		APIModel:            "base-conversationalai",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BaseFinance: {
		ID:                  BaseFinance,
		Name:                "base-finance",
		Provider:            "deepgram",
		APIModel:            "base-finance",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BaseMeeting: {
		ID:                  BaseMeeting,
		Name:                "base-meeting",
		Provider:            "deepgram",
		APIModel:            "base-meeting",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BasePhonecall: {
		ID:                  BasePhonecall,
		Name:                "base-phonecall",
		Provider:            "deepgram",
		APIModel:            "base-phonecall",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BaseVideo: {
		ID:                  BaseVideo,
		Name:                "base-video",
		Provider:            "deepgram",
		APIModel:            "base-video",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	BaseVoicemail: {
		ID:                  BaseVoicemail,
		Name:                "base-voicemail",
		Provider:            "deepgram",
		APIModel:            "base-voicemail",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Custom: {
		ID:                  Custom,
		Name:                "Custom",
		Provider:            "deepgram",
		APIModel:            "custom",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Enhanced: {
		ID:                  Enhanced,
		Name:                "enhanced",
		Provider:            "deepgram",
		APIModel:            "enhanced",
		Currency:            "USD",
		CostPer1MIn:         0.0165,
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	EnhancedFinance: {
		ID:                  EnhancedFinance,
		Name:                "enhanced-finance",
		Provider:            "deepgram",
		APIModel:            "enhanced-finance",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	EnhancedMeeting: {
		ID:                  EnhancedMeeting,
		Name:                "enhanced-meeting",
		Provider:            "deepgram",
		APIModel:            "enhanced-meeting",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	EnhancedPhonecall: {
		ID:                  EnhancedPhonecall,
		Name:                "enhanced-phonecall",
		Provider:            "deepgram",
		APIModel:            "enhanced-phonecall",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	FluxEnglish2: {
		ID:                     FluxEnglish2,
		Name:                   "Flux English",
		Provider:               "deepgram",
		APIModel:               "flux-english",
		Currency:               "USD",
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsStreaming:      true,
	},
	FluxEnglish: {
		ID:            FluxEnglish,
		Name:          "Deepgram Flux English",
		Provider:      "deepgram",
		APIModel:      "flux-general-en",
		Currency:      "USD",
		CostPer1MIn:   0.0065,
		MaxFileSizeMB: 2000,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
	FluxMulti: {
		ID:            FluxMulti,
		Name:          "Deepgram Flux Multilingual",
		Provider:      "deepgram",
		APIModel:      "flux-general-multi",
		Currency:      "USD",
		CostPer1MIn:   0.0078,
		MaxFileSizeMB: 2000,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
		},
		SupportsTimestamps:       true,
		SupportsWordTimestamps:   true,
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
	FluxMultilingual: {
		ID:                     FluxMultilingual,
		Name:                   "Flux Multilingual",
		Provider:               "deepgram",
		APIModel:               "flux-multilingual",
		Currency:               "USD",
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsStreaming:      true,
	},
	Nova: {
		ID:                  Nova,
		Name:                "nova",
		Provider:            "deepgram",
		APIModel:            "nova",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2: {
		ID:            Nova2,
		Name:          "Deepgram Nova 2",
		Provider:      "deepgram",
		APIModel:      "nova-2",
		Currency:      "USD",
		CostPer1MIn:   0.005833,
		MaxFileSizeMB: 2048,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
		},
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
		SupportedResponseFormats: []string{
			"json",
			"text",
			"srt",
			"vtt",
		},
	},
	Nova2Atc: {
		ID:                  Nova2Atc,
		Name:                "nova-2-atc",
		Provider:            "deepgram",
		APIModel:            "nova-2-atc",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Automotive: {
		ID:                  Nova2Automotive,
		Name:                "nova-2-automotive",
		Provider:            "deepgram",
		APIModel:            "nova-2-automotive",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Conversationalai: {
		ID:                  Nova2Conversationalai,
		Name:                "nova-2-conversationalai",
		Provider:            "deepgram",
		APIModel:            "nova-2-conversationalai",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Drivethru: {
		ID:                  Nova2Drivethru,
		Name:                "nova-2-drivethru",
		Provider:            "deepgram",
		APIModel:            "nova-2-drivethru",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Finance: {
		ID:                  Nova2Finance,
		Name:                "nova-2-finance",
		Provider:            "deepgram",
		APIModel:            "nova-2-finance",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Medical: {
		ID:                  Nova2Medical,
		Name:                "nova-2-medical",
		Provider:            "deepgram",
		APIModel:            "nova-2-medical",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Meeting: {
		ID:                  Nova2Meeting,
		Name:                "nova-2-meeting",
		Provider:            "deepgram",
		APIModel:            "nova-2-meeting",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Phonecall: {
		ID:                  Nova2Phonecall,
		Name:                "nova-2-phonecall",
		Provider:            "deepgram",
		APIModel:            "nova-2-phonecall",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Video: {
		ID:                  Nova2Video,
		Name:                "nova-2-video",
		Provider:            "deepgram",
		APIModel:            "nova-2-video",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova2Voicemail: {
		ID:                  Nova2Voicemail,
		Name:                "nova-2-voicemail",
		Provider:            "deepgram",
		APIModel:            "nova-2-voicemail",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova3: {
		ID:            Nova3,
		Name:          "Deepgram Nova 3",
		Provider:      "deepgram",
		APIModel:      "nova-3",
		Currency:      "USD",
		CostPer1MIn:   0.0077,
		MaxFileSizeMB: 2048,
		SupportedFormats: []string{
			"mp3",
			"mp4",
			"wav",
			"flac",
			"ogg",
			"webm",
			"m4a",
		},
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
		SupportedResponseFormats: []string{
			"json",
			"text",
			"srt",
			"vtt",
		},
	},
	Nova3Medical: {
		ID:                  Nova3Medical,
		Name:                "nova-3-medical",
		Provider:            "deepgram",
		APIModel:            "nova-3-medical",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova3Monolingual: {
		ID:                  Nova3Monolingual,
		Name:                "Nova-3 Monolingual",
		Provider:            "deepgram",
		APIModel:            "nova-3-monolingual",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	Nova3Multilingual: {
		ID:                  Nova3Multilingual,
		Name:                "Nova-3 Multilingual",
		Provider:            "deepgram",
		APIModel:            "nova-3-multilingual",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	NovaMedical: {
		ID:                  NovaMedical,
		Name:                "nova-medical",
		Provider:            "deepgram",
		APIModel:            "nova-medical",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	NovaPhonecall: {
		ID:                  NovaPhonecall,
		Name:                "nova-phonecall",
		Provider:            "deepgram",
		APIModel:            "nova-phonecall",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
		SupportsStreaming:   true,
	},
	WhisperBase: {
		ID:                  WhisperBase,
		Name:                "whisper-base",
		Provider:            "deepgram",
		APIModel:            "whisper-base",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
	},
	WhisperLarge: {
		ID:                  WhisperLarge,
		Name:                "Whisper Large",
		Provider:            "deepgram",
		APIModel:            "whisper-large",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
	},
	WhisperMedium: {
		ID:                  WhisperMedium,
		Name:                "whisper-medium",
		Provider:            "deepgram",
		APIModel:            "whisper-medium",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
	},
	WhisperSmall: {
		ID:                  WhisperSmall,
		Name:                "whisper-small",
		Provider:            "deepgram",
		APIModel:            "whisper-small",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
	},
	WhisperTiny: {
		ID:                  WhisperTiny,
		Name:                "whisper-tiny",
		Provider:            "deepgram",
		APIModel:            "whisper-tiny",
		Currency:            "USD",
		MaxFileSizeMB:       2048,
		SupportsTimestamps:  true,
		SupportsDiarization: true,
	},
}
