package openai

import (
	"github.com/joakimcarlsson/ai/llm"
)

// OpenAI provider plus chat, embedding, and image model IDs for this registry.
const (
	GPT41              string = "gpt-4.1"
	GPT41Mini          string = "gpt-4.1-mini"
	GPT41Nano          string = "gpt-4.1-nano"
	GPT4o              string = "gpt-4o"
	GPT4oMini          string = "gpt-4o-mini"
	O1                 string = "o1"
	O1Pro              string = "o1-pro"
	O1Mini             string = "o1-mini"
	O3                 string = "o3"
	O3Pro              string = "o3-pro"
	O3Mini             string = "o3-mini"
	O4Mini             string = "o4-mini"
	GPT5               string = "gpt-5"
	GPT5Mini           string = "gpt-5-mini"
	GPT5Nano           string = "gpt-5-nano"
	GPT51              string = "gpt-5.1"
	GPT51ChatLatest    string = "gpt-5.1-chat-latest"
	GPT5ChatLatest     string = "gpt-5-chat-latest"
	GPT51Codex         string = "gpt-5.1-codex"
	GPT5Codex          string = "gpt-5-codex"
	GPT51CodexMini     string = "gpt-5.1-codex-mini"
	GPT5Pro            string = "gpt-5-pro"
	GPT52              string = "gpt-5.2"
	GPT52Pro           string = "gpt-5.2-pro"
	GPT52Instant       string = "gpt-5.2-chat-latest"
	GPT52Codex         string = "gpt-5.2-codex"
	GPT53Codex         string = "gpt-5.3-codex"
	GPT51CodexMax      string = "gpt-5.1-codex-max"
	GPT54              string = "gpt-5.4"
	GPT54Mini          string = "gpt-5.4-mini"
	GPT54Nano          string = "gpt-5.4-nano"
	GPT54Pro           string = "gpt-5.4-pro"
	GPT55              string = "gpt-5.5"
	GPT55Pro           string = "gpt-5.5-pro"
	GPT56Sol           string = "gpt-5.6-sol"
	GPT56Terra         string = "gpt-5.6-terra"
	GPT56Luna          string = "gpt-5.6-luna"
	GPT53ChatLatest    string = "gpt-5.3-chat-latest"
	O3DeepResearch     string = "o3-deep-research"
	O4MiniDeepResearch string = "o4-mini-deep-research"
)

// Models maps OpenAI chat model IDs to their configurations.
//
// Pricing source: https://developers.openai.com/api/docs/pricing.
// Fetched: 2026-07-26.
var Models = map[string]llm.Model{
	GPT41: {
		ID:                    GPT41,
		Name:                  "GPT 4.1",
		Provider:              "openai",
		APIModel:              "gpt-4.1",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Mini: {
		ID:                    GPT41Mini,
		Name:                  "GPT 4.1 mini",
		Provider:              "openai",
		APIModel:              "gpt-4.1-mini",
		CostPer1MIn:           0.4,
		CostPer1MOut:          1.6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT41Nano: {
		ID:                    GPT41Nano,
		Name:                  "GPT 4.1 nano",
		Provider:              "openai",
		APIModel:              "gpt-4.1-nano",
		CostPer1MIn:           0.1,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.025,
		ContextWindow:         1047576,
		DefaultMaxTokens:      20000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4o: {
		ID:                    GPT4o,
		Name:                  "GPT 4o",
		Provider:              "openai",
		APIModel:              "gpt-4o",
		CostPer1MIn:           2.5,
		CostPer1MOut:          10,
		CostPer1MInCached:     1.25,
		ContextWindow:         128000,
		DefaultMaxTokens:      4096,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT4oMini: {
		ID:                    GPT4oMini,
		Name:                  "GPT 4o mini",
		Provider:              "openai",
		APIModel:              "gpt-4o-mini",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.075,
		ContextWindow:         128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1: {
		ID:                    O1,
		Name:                  "O1",
		Provider:              "openai",
		APIModel:              "o1",
		CostPer1MIn:           15,
		CostPer1MOut:          60,
		CostPer1MInCached:     7.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1Pro: {
		ID:                    O1Pro,
		Name:                  "o1 pro",
		Provider:              "openai",
		APIModel:              "o1-pro",
		CostPer1MIn:           150,
		CostPer1MOut:          600,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O1Mini: {
		ID:                    O1Mini,
		Name:                  "o1 mini",
		Provider:              "openai",
		APIModel:              "o1-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.55,
		ContextWindow:         128000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3: {
		ID:                    O3,
		Name:                  "o3",
		Provider:              "openai",
		APIModel:              "o3",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3Mini: {
		ID:                    O3Mini,
		Name:                  "o3 mini",
		Provider:              "openai",
		APIModel:              "o3-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.55,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	O4Mini: {
		ID:                    O4Mini,
		Name:                  "o4 mini",
		Provider:              "openai",
		APIModel:              "o4-mini",
		CostPer1MIn:           1.1,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.275,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5: {
		ID:                    GPT5,
		Name:                  "GPT-5",
		Provider:              "openai",
		APIModel:              "gpt-5",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Mini: {
		ID:                    GPT5Mini,
		Name:                  "GPT-5 mini",
		Provider:              "openai",
		APIModel:              "gpt-5-mini",
		CostPer1MIn:           0.25,
		CostPer1MOut:          2,
		CostPer1MInCached:     0.025,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Nano: {
		ID:                    GPT5Nano,
		Name:                  "GPT-5 nano",
		Provider:              "openai",
		APIModel:              "gpt-5-nano",
		CostPer1MIn:           0.05,
		CostPer1MOut:          0.4,
		CostPer1MInCached:     0.005,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51: {
		ID:                    GPT51,
		Name:                  "GPT-5.1",
		Provider:              "openai",
		APIModel:              "gpt-5.1",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51ChatLatest: {
		ID:                    GPT51ChatLatest,
		Name:                  "GPT-5.1 chat latest",
		Provider:              "openai",
		APIModel:              "gpt-5.1-chat-latest",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         128000,
		DefaultMaxTokens:      16384,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5ChatLatest: {
		ID:                    GPT5ChatLatest,
		Name:                  "GPT-5 chat latest",
		Provider:              "openai",
		APIModel:              "gpt-5-chat-latest",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         128000,
		DefaultMaxTokens:      16384,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51Codex: {
		ID:                    GPT51Codex,
		Name:                  "GPT-5.1 codex",
		Provider:              "openai",
		APIModel:              "gpt-5.1-codex",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Codex: {
		ID:                    GPT5Codex,
		Name:                  "GPT-5 codex",
		Provider:              "openai",
		APIModel:              "gpt-5-codex",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51CodexMini: {
		ID:                    GPT51CodexMini,
		Name:                  "GPT-5.1 codex mini",
		Provider:              "openai",
		APIModel:              "gpt-5.1-codex-mini",
		CostPer1MIn:           0.25,
		CostPer1MOut:          2,
		CostPer1MInCached:     0.025,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT5Pro: {
		ID:                    GPT5Pro,
		Name:                  "GPT-5 pro",
		Provider:              "openai",
		APIModel:              "gpt-5-pro",
		CostPer1MIn:           15,
		CostPer1MOut:          120,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52: {
		ID:                    GPT52,
		Name:                  "GPT-5.2",
		Provider:              "openai",
		APIModel:              "gpt-5.2",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52Pro: {
		ID:                    GPT52Pro,
		Name:                  "GPT-5.2 Pro",
		Provider:              "openai",
		APIModel:              "gpt-5.2-pro",
		CostPer1MIn:           21,
		CostPer1MOut:          168,
		CostPer1MInCached:     2.1,
		ContextWindow:         400000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52Instant: {
		ID:                    GPT52Instant,
		Name:                  "GPT-5.2 Instant",
		Provider:              "openai",
		APIModel:              "gpt-5.2-chat-latest",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         128000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3Pro: {
		ID:                    O3Pro,
		Name:                  "o3 pro",
		Provider:              "openai",
		APIModel:              "o3-pro",
		CostPer1MIn:           20,
		CostPer1MOut:          80,
		CostPer1MInCached:     5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT52Codex: {
		ID:                    GPT52Codex,
		Name:                  "GPT-5.2 Codex",
		Provider:              "openai",
		APIModel:              "gpt-5.2-codex",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT53Codex: {
		ID:                    GPT53Codex,
		Name:                  "GPT-5.3 Codex",
		Provider:              "openai",
		APIModel:              "gpt-5.3-codex",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT51CodexMax: {
		ID:                    GPT51CodexMax,
		Name:                  "GPT-5.1 Codex Max",
		Provider:              "openai",
		APIModel:              "gpt-5.1-codex-max",
		CostPer1MIn:           1.25,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.125,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT55Pro: {
		ID:                    GPT55Pro,
		Name:                  "GPT-5.5 pro",
		Provider:              "openai",
		APIModel:              "gpt-5.5-pro",
		CostPer1MIn:           30,
		CostPer1MOut:          180,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54: {
		ID:                    GPT54,
		Name:                  "GPT-5.4",
		Provider:              "openai",
		APIModel:              "gpt-5.4",
		CostPer1MIn:           2.5,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.25,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Mini: {
		ID:                    GPT54Mini,
		Name:                  "GPT-5.4 mini",
		Provider:              "openai",
		APIModel:              "gpt-5.4-mini",
		CostPer1MIn:           0.75,
		CostPer1MOut:          4.5,
		CostPer1MInCached:     0.075,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Nano: {
		ID:                    GPT54Nano,
		Name:                  "GPT-5.4 nano",
		Provider:              "openai",
		APIModel:              "gpt-5.4-nano",
		CostPer1MIn:           0.2,
		CostPer1MOut:          1.25,
		CostPer1MInCached:     0.02,
		ContextWindow:         400000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT54Pro: {
		ID:                    GPT54Pro,
		Name:                  "GPT-5.4 pro",
		Provider:              "openai",
		APIModel:              "gpt-5.4-pro",
		CostPer1MIn:           30,
		CostPer1MOut:          180,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT55: {
		ID:                    GPT55,
		Name:                  "GPT-5.5",
		Provider:              "openai",
		APIModel:              "gpt-5.5",
		CostPer1MIn:           5,
		CostPer1MOut:          30,
		CostPer1MInCached:     0.5,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Sol: {
		ID:                    GPT56Sol,
		Name:                  "GPT-5.6 Sol",
		Provider:              "openai",
		APIModel:              "gpt-5.6-sol",
		CostPer1MIn:           5,
		CostPer1MOut:          30,
		CostPer1MInCached:     0.5,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Terra: {
		ID:                    GPT56Terra,
		Name:                  "GPT-5.6 Terra",
		Provider:              "openai",
		APIModel:              "gpt-5.6-terra",
		CostPer1MIn:           2.5,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.25,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT56Luna: {
		ID:                    GPT56Luna,
		Name:                  "GPT-5.6 Luna",
		Provider:              "openai",
		APIModel:              "gpt-5.6-luna",
		CostPer1MIn:           1,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.1,
		ContextWindow:         1050000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPT53ChatLatest: {
		ID:                    GPT53ChatLatest,
		Name:                  "GPT-5.3 chat latest",
		Provider:              "openai",
		APIModel:              "gpt-5.3-chat-latest",
		CostPer1MIn:           1.75,
		CostPer1MOut:          14,
		CostPer1MInCached:     0.175,
		ContextWindow:         128000,
		DefaultMaxTokens:      16384,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O3DeepResearch: {
		ID:                    O3DeepResearch,
		Name:                  "o3 deep research",
		Provider:              "openai",
		APIModel:              "o3-deep-research",
		CostPer1MIn:           10,
		CostPer1MOut:          40,
		CostPer1MInCached:     2.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      100000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	O4MiniDeepResearch: {
		ID:                    O4MiniDeepResearch,
		Name:                  "o4 mini deep research",
		Provider:              "openai",
		APIModel:              "o4-mini-deep-research",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		CostPer1MInCached:     0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
