// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.
//
// OpenRouter routes to upstream providers and passes their rates
// through; the figures here are the ones it quotes.

package openrouter

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	Flux2Flex                 string = "openrouter.flux.2-flex"
	Flux2Klein4B              string = "openrouter.flux.2-klein-4b"
	Flux2Max                  string = "openrouter.flux.2-max"
	Flux2Pro                  string = "openrouter.flux.2-pro"
	Seedream45                string = "openrouter.seedream-4.5"
	Seedream50Lite            string = "openrouter.seedream-5-0-lite"
	Seedream50Pro             string = "openrouter.seedream-5-0-pro"
	Gemini25FlashImage        string = "openrouter.gemini-2.5-flash-image"
	Gemini3ProImage           string = "openrouter.gemini-3-pro-image"
	Gemini3ProImagePreview    string = "openrouter.gemini-3-pro-image-preview"
	Gemini31FlashImage        string = "openrouter.gemini-3.1-flash-image"
	Gemini31FlashImagePreview string = "openrouter.gemini-3.1-flash-image-preview"
	Gemini31FlashLiteImage    string = "openrouter.gemini-3.1-flash-lite-image"
	Krea2Large                string = "openrouter.krea-2-large"
	Krea2Medium               string = "openrouter.krea-2-medium"
	Krea2MediumTurbo          string = "openrouter.krea-2-medium-turbo"
	MAIImage25                string = "openrouter.mai-image-2.5"
	MAIImage25Pro             string = "openrouter.mai-image-2.5-pro"
	GPT5Image                 string = "openrouter.gpt-5-image"
	GPT5ImageMini             string = "openrouter.gpt-5-image-mini"
	GPT54Image2               string = "openrouter.gpt-5.4-image-2"
	GPTImage1                 string = "openrouter.gpt-image-1"
	GPTImage1Mini             string = "openrouter.gpt-image-1-mini"
	GPTImage2                 string = "openrouter.gpt-image-2"
	Auto                      string = "openrouter.auto"
	AutoBeta                  string = "openrouter.auto-beta"
	QwenImage3                string = "openrouter.qwen-image-3"
	QwenImage3Pro             string = "openrouter.qwen-image-3-pro"
	RecraftV3                 string = "openrouter.recraft-v3"
	RecraftV4                 string = "openrouter.recraft-v4"
	RecraftV4Pro              string = "openrouter.recraft-v4-pro"
	RecraftV4ProVector        string = "openrouter.recraft-v4-pro-vector"
	RecraftV4Vector           string = "openrouter.recraft-v4-vector"
	RecraftV41                string = "openrouter.recraft-v4.1"
	RecraftV41Pro             string = "openrouter.recraft-v4.1-pro"
	RecraftV41ProVector       string = "openrouter.recraft-v4.1-pro-vector"
	RecraftV41Utility         string = "openrouter.recraft-v4.1-utility"
	RecraftV41UtilityPro      string = "openrouter.recraft-v4.1-utility-pro"
	RecraftV41Vector          string = "openrouter.recraft-v4.1-vector"
	RiverflowV2Fast           string = "openrouter.riverflow-v2-fast"
	RiverflowV2Pro            string = "openrouter.riverflow-v2-pro"
	RiverflowV25Fast          string = "openrouter.riverflow-v2.5-fast"
	RiverflowV25Pro           string = "openrouter.riverflow-v2.5-pro"
	GrokImagineImage20        string = "openrouter.grok-imagine-image-2.0"
	GrokImagineImageQuality   string = "openrouter.grok-imagine-image-quality"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	Flux2Flex: {
		ID:                 Flux2Flex,
		Name:               "OpenRouter – FLUX.2 Flex",
		Provider:           "openrouter",
		APIModel:           "black-forest-labs/flux.2-flex",
		Currency:           "USD",
		MaxPromptTokens:    67344,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Flux2Klein4B: {
		ID:                 Flux2Klein4B,
		Name:               "OpenRouter – FLUX.2 Klein 4B",
		Provider:           "openrouter",
		APIModel:           "black-forest-labs/flux.2-klein-4b",
		Currency:           "USD",
		MaxPromptTokens:    40960,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Flux2Max: {
		ID:                 Flux2Max,
		Name:               "OpenRouter – FLUX.2 Max",
		Provider:           "openrouter",
		APIModel:           "black-forest-labs/flux.2-max",
		Currency:           "USD",
		MaxPromptTokens:    46864,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Flux2Pro: {
		ID:                 Flux2Pro,
		Name:               "OpenRouter – FLUX.2 Pro",
		Provider:           "openrouter",
		APIModel:           "black-forest-labs/flux.2-pro",
		Currency:           "USD",
		MaxPromptTokens:    46864,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Seedream45: {
		ID:       Seedream45,
		Name:     "OpenRouter – Seedream 4.5",
		Provider: "openrouter",
		APIModel: "bytedance-seed/seedream-4.5",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.04,
			},
		},
		MaxPromptTokens:    4096,
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"1:2",
			"2:1",
			"2:3",
			"3:2",
			"3:4",
			"4:3",
			"4:5",
			"5:4",
			"9:16",
			"16:9",
			"9:19.5",
			"19.5:9",
			"9:20",
			"20:9",
			"9:21",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Seedream50Lite: {
		ID:       Seedream50Lite,
		Name:     "OpenRouter – Seedream 5.0 Lite",
		Provider: "openrouter",
		APIModel: "bytedance-seed/seedream-5-0-lite",
		Currency: "USD",
	},
	Seedream50Pro: {
		ID:       Seedream50Pro,
		Name:     "OpenRouter – Seedream 5.0 Pro",
		Provider: "openrouter",
		APIModel: "bytedance-seed/seedream-5-0-pro",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.003},
		},
	},
	Gemini25FlashImage: {
		ID:       Gemini25FlashImage,
		Name:     "OpenRouter – Nano Banana (Gemini 2.5 Flash Image)",
		Provider: "openrouter",
		APIModel: "google/gemini-2.5-flash-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.039,
			},
			"1:1": {
				"default": 0.039,
			},
			"3:4": {
				"default": 0.039,
			},
			"4:3": {
				"default": 0.039,
			},
			"9:16": {
				"default": 0.039,
			},
		},
		MaxPromptTokens:    32768,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"2:3",
			"3:2",
			"3:4",
			"4:3",
			"4:5",
			"5:4",
			"9:16",
			"16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
	},
	Gemini3ProImage: {
		ID:       Gemini3ProImage,
		Name:     "OpenRouter – Nano Banana Pro (Gemini 3 Pro Image)",
		Provider: "openrouter",
		APIModel: "google/gemini-3-pro-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.134,
			},
			"1:1": {
				"default": 0.134,
			},
			"3:4": {
				"default": 0.134,
			},
			"4:3": {
				"default": 0.134,
			},
			"9:16": {
				"default": 0.134,
			},
		},
		MaxPromptTokens:    131072,
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"2:3",
			"3:2",
			"3:4",
			"4:3",
			"4:5",
			"5:4",
			"9:16",
			"16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
	},
	Gemini3ProImagePreview: {
		ID:       Gemini3ProImagePreview,
		Name:     "OpenRouter – Nano Banana Pro (Gemini 3 Pro Image Preview)",
		Provider: "openrouter",
		APIModel: "google/gemini-3-pro-image-preview",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.000002},
		},
		MaxPromptTokens: 65536,
	},
	Gemini31FlashImage: {
		ID:       Gemini31FlashImage,
		Name:     "OpenRouter – Nano Banana 2 (Gemini 3.1 Flash Image)",
		Provider: "openrouter",
		APIModel: "google/gemini-3.1-flash-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.067,
			},
			"1:1": {
				"default": 0.067,
			},
			"1:4": {
				"default": 0.067,
			},
			"1:8": {
				"default": 0.067,
			},
			"3:4": {
				"default": 0.067,
			},
			"4:1": {
				"default": 0.067,
			},
			"4:3": {
				"default": 0.067,
			},
			"8:1": {
				"default": 0.067,
			},
			"9:16": {
				"default": 0.067,
			},
		},
		MaxPromptTokens: 131072,
		SupportedSizes: []string{
			"512",
			"1K",
			"2K",
			"4K",
		},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"1:4",
			"1:8",
			"2:3",
			"3:2",
			"3:4",
			"4:1",
			"4:3",
			"4:5",
			"5:4",
			"8:1",
			"9:16",
			"16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
	},
	Gemini31FlashImagePreview: {
		ID:              Gemini31FlashImagePreview,
		Name:            "OpenRouter – Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
		Provider:        "openrouter",
		APIModel:        "google/gemini-3.1-flash-image-preview",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	Gemini31FlashLiteImage: {
		ID:       Gemini31FlashLiteImage,
		Name:     "OpenRouter – Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
		Provider: "openrouter",
		APIModel: "google/gemini-3.1-flash-lite-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"16:9": {
				"default": 0.0336,
			},
			"1:1": {
				"default": 0.0336,
			},
			"1:4": {
				"default": 0.0336,
			},
			"1:8": {
				"default": 0.0336,
			},
			"3:4": {
				"default": 0.0336,
			},
			"4:1": {
				"default": 0.0336,
			},
			"4:3": {
				"default": 0.0336,
			},
			"8:1": {
				"default": 0.0336,
			},
			"9:16": {
				"default": 0.0336,
			},
		},
		MaxPromptTokens:    65536,
		SupportedSizes:     []string{"1K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"1:4",
			"1:8",
			"2:3",
			"3:2",
			"3:4",
			"4:1",
			"4:3",
			"4:5",
			"5:4",
			"8:1",
			"9:16",
			"16:9",
			"21:9",
		},
		DefaultAspectRatio: "1:1",
	},
	Krea2Large: {
		ID:              Krea2Large,
		Name:            "OpenRouter – Krea 2 Large",
		Provider:        "openrouter",
		APIModel:        "krea/krea-2-large",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	Krea2Medium: {
		ID:              Krea2Medium,
		Name:            "OpenRouter – Krea 2 Medium",
		Provider:        "openrouter",
		APIModel:        "krea/krea-2-medium",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	Krea2MediumTurbo: {
		ID:              Krea2MediumTurbo,
		Name:            "OpenRouter – Krea 2 Medium Turbo",
		Provider:        "openrouter",
		APIModel:        "krea/krea-2-medium-turbo",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	MAIImage25: {
		ID:                 MAIImage25,
		Name:               "OpenRouter – MAI-Image-2.5",
		Provider:           "openrouter",
		APIModel:           "microsoft/mai-image-2.5",
		Currency:           "USD",
		MaxPromptTokens:    4096,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	MAIImage25Pro: {
		ID:                 MAIImage25Pro,
		Name:               "OpenRouter – MAI-Image-2.5 Pro",
		Provider:           "openrouter",
		APIModel:           "microsoft/mai-image-2.5-pro",
		Currency:           "USD",
		MaxPromptTokens:    4096,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	GPT5Image: {
		ID:              GPT5Image,
		Name:            "OpenRouter – GPT-5 Image",
		Provider:        "openrouter",
		APIModel:        "openai/gpt-5-image",
		Currency:        "USD",
		MaxPromptTokens: 272000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
	},
	GPT5ImageMini: {
		ID:              GPT5ImageMini,
		Name:            "OpenRouter – GPT-5 Image Mini",
		Provider:        "openrouter",
		APIModel:        "openai/gpt-5-image-mini",
		Currency:        "USD",
		MaxPromptTokens: 272000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
	},
	GPT54Image2: {
		ID:              GPT54Image2,
		Name:            "OpenRouter – GPT-5.4 Image 2",
		Provider:        "openrouter",
		APIModel:        "openai/gpt-5.4-image-2",
		Currency:        "USD",
		MaxPromptTokens: 922000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
	},
	GPTImage1: {
		ID:              GPTImage1,
		Name:            "OpenRouter – GPT Image 1",
		Provider:        "openrouter",
		APIModel:        "openai/gpt-image-1",
		Currency:        "USD",
		MaxPromptTokens: 400000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
		SupportedAspectRatios: []string{
			"1:1",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	GPTImage1Mini: {
		ID:              GPTImage1Mini,
		Name:            "OpenRouter – GPT Image 1 Mini",
		Provider:        "openrouter",
		APIModel:        "openai/gpt-image-1-mini",
		Currency:        "USD",
		MaxPromptTokens: 400000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
		SupportedAspectRatios: []string{
			"1:1",
			"3:2",
			"2:3",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	GPTImage2: {
		ID:       GPTImage2,
		Name:     "OpenRouter – GPT Image 2",
		Provider: "openrouter",
		APIModel: "openai/gpt-image-2",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"1024x1024": {
				"high":   0.211,
				"low":    0.006,
				"medium": 0.053,
			},
			"1024x1536": {
				"high":   0.165,
				"low":    0.005,
				"medium": 0.041,
			},
			"1536x1024": {
				"high":   0.165,
				"low":    0.005,
				"medium": 0.041,
			},
		},
		MaxPromptTokens: 400000,
		SupportedQualities: []string{
			"auto",
			"low",
			"medium",
			"high",
		},
		DefaultQuality: "auto",
		SupportedAspectRatios: []string{
			"1:1",
			"3:2",
			"2:3",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	Auto: {
		ID:              Auto,
		Name:            "OpenRouter – Auto Router",
		Provider:        "openrouter",
		APIModel:        "openrouter/auto",
		Currency:        "USD",
		MaxPromptTokens: 2000000,
	},
	AutoBeta: {
		ID:              AutoBeta,
		Name:            "OpenRouter – Auto Router (Beta)",
		Provider:        "openrouter",
		APIModel:        "openrouter/auto-beta",
		Currency:        "USD",
		MaxPromptTokens: 2000000,
	},
	QwenImage3: {
		ID:       QwenImage3,
		Name:     "OpenRouter – Qwen Image 3",
		Provider: "openrouter",
		APIModel: "qwen/qwen-image-3",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.003},
		},
		MaxPromptTokens: 65536,
	},
	QwenImage3Pro: {
		ID:       QwenImage3Pro,
		Name:     "OpenRouter – Qwen Image 3 Pro",
		Provider: "openrouter",
		APIModel: "qwen/qwen-image-3-pro",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.003},
		},
		MaxPromptTokens: 65536,
	},
	RecraftV3: {
		ID:              RecraftV3,
		Name:            "OpenRouter – Recraft V3",
		Provider:        "openrouter",
		APIModel:        "recraft/recraft-v3",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	RecraftV4: {
		ID:       RecraftV4,
		Name:     "OpenRouter – Recraft V4",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.04,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RecraftV4Pro: {
		ID:              RecraftV4Pro,
		Name:            "OpenRouter – Recraft V4 Pro",
		Provider:        "openrouter",
		APIModel:        "recraft/recraft-v4-pro",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	RecraftV4ProVector: {
		ID:              RecraftV4ProVector,
		Name:            "OpenRouter – Recraft V4 Pro Vector",
		Provider:        "openrouter",
		APIModel:        "recraft/recraft-v4-pro-vector",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	RecraftV4Vector: {
		ID:       RecraftV4Vector,
		Name:     "OpenRouter – Recraft V4 Vector",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4-vector",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.08,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RecraftV41: {
		ID:       RecraftV41,
		Name:     "OpenRouter – Recraft V4.1",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4.1",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.035,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RecraftV41Pro: {
		ID:       RecraftV41Pro,
		Name:     "OpenRouter – Recraft V4.1 Pro",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4.1-pro",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.21,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RecraftV41ProVector: {
		ID:       RecraftV41ProVector,
		Name:     "OpenRouter – Recraft V4.1 Pro Vector",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4.1-pro-vector",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.3,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RecraftV41Utility: {
		ID:              RecraftV41Utility,
		Name:            "OpenRouter – Recraft V4.1 Utility",
		Provider:        "openrouter",
		APIModel:        "recraft/recraft-v4.1-utility",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	RecraftV41UtilityPro: {
		ID:              RecraftV41UtilityPro,
		Name:            "OpenRouter – Recraft V4.1 Utility Pro",
		Provider:        "openrouter",
		APIModel:        "recraft/recraft-v4.1-utility-pro",
		Currency:        "USD",
		MaxPromptTokens: 65536,
	},
	RecraftV41Vector: {
		ID:       RecraftV41Vector,
		Name:     "OpenRouter – Recraft V4.1 Vector",
		Provider: "openrouter",
		APIModel: "recraft/recraft-v4.1-vector",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.08,
			},
		},
		MaxPromptTokens:    65536,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"16:9",
			"9:16",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RiverflowV2Fast: {
		ID:              RiverflowV2Fast,
		Name:            "OpenRouter – Riverflow V2 Fast",
		Provider:        "openrouter",
		APIModel:        "sourceful/riverflow-v2-fast",
		Currency:        "USD",
		MaxPromptTokens: 8192,
	},
	RiverflowV2Pro: {
		ID:              RiverflowV2Pro,
		Name:            "OpenRouter – Riverflow V2 Pro",
		Provider:        "openrouter",
		APIModel:        "sourceful/riverflow-v2-pro",
		Currency:        "USD",
		MaxPromptTokens: 8192,
	},
	RiverflowV25Fast: {
		ID:                 RiverflowV25Fast,
		Name:               "OpenRouter – Riverflow V2.5 Fast",
		Provider:           "openrouter",
		APIModel:           "sourceful/riverflow-v2.5-fast",
		Currency:           "USD",
		MaxPromptTokens:    32768,
		SupportedSizes:     []string{"1K", "2K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	RiverflowV25Pro: {
		ID:                 RiverflowV25Pro,
		Name:               "OpenRouter – Riverflow V2.5 Pro",
		Provider:           "openrouter",
		APIModel:           "sourceful/riverflow-v2.5-pro",
		Currency:           "USD",
		MaxPromptTokens:    32768,
		SupportedSizes:     []string{"1K", "2K", "4K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"16:9",
			"9:16",
			"21:9",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	GrokImagineImage20: {
		ID:       GrokImagineImage20,
		Name:     "OpenRouter – Grok Imagine Image 2.0",
		Provider: "openrouter",
		APIModel: "x-ai/grok-imagine-image-2.0",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.01},
		},
		MaxPromptTokens: 65536,
	},
	GrokImagineImageQuality: {
		ID:                 GrokImagineImageQuality,
		Name:               "OpenRouter – Grok Imagine Image Quality",
		Provider:           "openrouter",
		APIModel:           "x-ai/grok-imagine-image-quality",
		Currency:           "USD",
		MaxPromptTokens:    65536,
		SupportedSizes:     []string{"1K", "2K"},
		DefaultSize:        "1K",
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"3:4",
			"4:3",
			"9:16",
			"16:9",
			"2:3",
			"3:2",
			"9:19.5",
			"19.5:9",
			"9:20",
			"20:9",
			"1:2",
			"2:1",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
}
