// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package perplexity

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	ClaudeFable5                string = "claude-fable-5"
	ClaudeHaiku45               string = "claude-haiku-4-5"
	ClaudeOpus45                string = "claude-opus-4-5"
	ClaudeOpus46                string = "claude-opus-4-6"
	ClaudeOpus47                string = "claude-opus-4-7"
	ClaudeOpus48                string = "claude-opus-4-8"
	ClaudeOpus5                 string = "claude-opus-5"
	ClaudeSonnet45              string = "claude-sonnet-4-5"
	ClaudeSonnet46              string = "claude-sonnet-4-6"
	ClaudeSonnet5               string = "claude-sonnet-5"
	Codellama70BInstruct        string = "codellama-70b-instruct"
	Gemini25Flash               string = "gemini-2.5-flash"
	Gemini3FlashPreview         string = "gemini-3-flash-preview"
	Gemini31FlashLite           string = "gemini-3.1-flash-lite"
	Gemini31FlashLitePreview    string = "gemini-3.1-flash-lite-preview"
	Gemini31ProPreview          string = "gemini-3.1-pro-preview"
	Gemini35Flash               string = "gemini-3.5-flash"
	Gemini35FlashLite           string = "gemini-3.5-flash-lite"
	Gemini36Flash               string = "gemini-3.6-flash"
	Gemini37Flash               string = "gemini-3.7-flash"
	Llama370BInstruct           string = "llama-3-70b-instruct"
	Llama38BInstruct            string = "llama-3-8b-instruct"
	Llama3SonarLarge32KChat     string = "llama-3-sonar-large-32k-chat"
	Llama3SonarLarge32KOnline   string = "llama-3-sonar-large-32k-online"
	Llama3SonarSmall32KChat     string = "llama-3-sonar-small-32k-chat"
	Llama3SonarSmall32KOnline   string = "llama-3-sonar-small-32k-online"
	Llama31SonarHuge128KOnline  string = "llama-3.1-sonar-huge-128k-online"
	Llama31SonarLarge128KOnline string = "llama-3.1-sonar-large-128k-online"
	Llama31SonarSmall128KOnline string = "llama-3.1-sonar-small-128k-online"
	Mistral7BInstruct           string = "mistral-7b-instruct"
	Mixtral8X22BInstruct        string = "mixtral-8x22b-instruct"
	Mixtral8X7BInstruct         string = "mixtral-8x7b-instruct"
	GPT5                        string = "gpt-5"
	GPT5Mini                    string = "gpt-5-mini"
	GPT51                       string = "gpt-5.1"
	GPT52                       string = "gpt-5.2"
	GPT54                       string = "gpt-5.4"
	GPT54Mini                   string = "gpt-5.4-mini"
	GPT54Nano                   string = "gpt-5.4-nano"
	GPT55                       string = "gpt-5.5"
	GPT56Luna                   string = "gpt-5.6-luna"
	GPT56Sol                    string = "gpt-5.6-sol"
	GPT56Terra                  string = "gpt-5.6-terra"
	DeepseekV4Flash0731         string = "deepseek-v4-flash-0731"
	GLM52                       string = "glm-5.2"
	KimiK27Code                 string = "kimi-k2.7-code"
	KimiK3                      string = "kimi-k3"
	Nemotron3Ultra550BA55B      string = "nemotron-3-ultra-550b-a55b"
	Nemotron35Lightning30BA3B   string = "nemotron-3.5-lightning-30b-a3b"
	PerplexitySonar             string = "perplexity-sonar"
	Pplx7BChat                  string = "pplx-7b-chat"
	Pplx7BOnline                string = "pplx-7b-online"
	Sonar                       string = "sonar"
	SonarDeepResearch           string = "sonar-deep-research"
	SonarPro                    string = "sonar-pro"
	SonarReasoning              string = "sonar-reasoning"
	SonarReasoningPro           string = "sonar-reasoning-pro"
	Grok420MultiAgent           string = "grok-4.20-multi-agent"
	Grok420NonReasoning         string = "grok-4.20-non-reasoning"
	Grok420Reasoning            string = "grok-4.20-reasoning"
	Grok43                      string = "grok-4.3"
	Grok45                      string = "grok-4.5"
	Grok46                      string = "grok-4.6"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	ClaudeFable5: {
		ID:                ClaudeFable5,
		Name:              "anthropic/claude-fable-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-fable-5",
		Currency:          "USD",
		CostPer1MIn:       10,
		CostPer1MOut:      50,
		CostPer1MInCached: 1,
	},
	ClaudeHaiku45: {
		ID:                ClaudeHaiku45,
		Name:              "anthropic/claude-haiku-4-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-haiku-4-5",
		Currency:          "USD",
		CostPer1MIn:       1,
		CostPer1MOut:      5,
		CostPer1MInCached: 0.1,
	},
	ClaudeOpus45: {
		ID:                ClaudeOpus45,
		Name:              "anthropic/claude-opus-4-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-opus-4-5",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      25,
		CostPer1MInCached: 0.5,
	},
	ClaudeOpus46: {
		ID:                ClaudeOpus46,
		Name:              "anthropic/claude-opus-4-6",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-opus-4-6",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      25,
		CostPer1MInCached: 0.5,
	},
	ClaudeOpus47: {
		ID:                ClaudeOpus47,
		Name:              "anthropic/claude-opus-4-7",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-opus-4-7",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      25,
		CostPer1MInCached: 0.5,
	},
	ClaudeOpus48: {
		ID:                ClaudeOpus48,
		Name:              "anthropic/claude-opus-4-8",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-opus-4-8",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      25,
		CostPer1MInCached: 0.5,
	},
	ClaudeOpus5: {
		ID:                ClaudeOpus5,
		Name:              "anthropic/claude-opus-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-opus-5",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      25,
		CostPer1MInCached: 0.5,
	},
	ClaudeSonnet45: {
		ID:                ClaudeSonnet45,
		Name:              "anthropic/claude-sonnet-4-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-sonnet-4-5",
		Currency:          "USD",
		CostPer1MIn:       3,
		CostPer1MOut:      15,
		CostPer1MInCached: 0.3,
	},
	ClaudeSonnet46: {
		ID:                ClaudeSonnet46,
		Name:              "anthropic/claude-sonnet-4-6",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-sonnet-4-6",
		Currency:          "USD",
		CostPer1MIn:       3,
		CostPer1MOut:      15,
		CostPer1MInCached: 0.3,
	},
	ClaudeSonnet5: {
		ID:                ClaudeSonnet5,
		Name:              "anthropic/claude-sonnet-5",
		Provider:          "perplexity",
		APIModel:          "anthropic/claude-sonnet-5",
		Currency:          "USD",
		CostPer1MIn:       2,
		CostPer1MOut:      10,
		CostPer1MInCached: 0.2,
	},
	Codellama70BInstruct: {
		ID:       Codellama70BInstruct,
		Name:     "codellama-70b-instruct",
		Provider: "perplexity",
		APIModel: "codellama-70b-instruct",
		Currency: "USD",
	},
	Gemini25Flash: {
		ID:       Gemini25Flash,
		Name:     "google/gemini-2.5-flash",
		Provider: "perplexity",
		APIModel: "google/gemini-2.5-flash",
		Currency: "USD",
	},
	Gemini3FlashPreview: {
		ID:           Gemini3FlashPreview,
		Name:         "google/gemini-3-flash-preview",
		Provider:     "perplexity",
		APIModel:     "google/gemini-3-flash-preview",
		Currency:     "USD",
		CostPer1MIn:  0.5,
		CostPer1MOut: 3,
	},
	Gemini31FlashLite: {
		ID:           Gemini31FlashLite,
		Name:         "google/gemini-3.1-flash-lite",
		Provider:     "perplexity",
		APIModel:     "google/gemini-3.1-flash-lite",
		Currency:     "USD",
		CostPer1MIn:  0.25,
		CostPer1MOut: 1.5,
	},
	Gemini31FlashLitePreview: {
		ID:       Gemini31FlashLitePreview,
		Name:     "google/gemini-3.1-flash-lite-preview",
		Provider: "perplexity",
		APIModel: "google/gemini-3.1-flash-lite-preview",
		Currency: "USD",
	},
	Gemini31ProPreview: {
		ID:           Gemini31ProPreview,
		Name:         "google/gemini-3.1-pro-preview",
		Provider:     "perplexity",
		APIModel:     "google/gemini-3.1-pro-preview",
		Currency:     "USD",
		CostPer1MIn:  2,
		CostPer1MOut: 12,
	},
	Gemini35Flash: {
		ID:                Gemini35Flash,
		Name:              "google/gemini-3.5-flash",
		Provider:          "perplexity",
		APIModel:          "google/gemini-3.5-flash",
		Currency:          "USD",
		CostPer1MIn:       1.5,
		CostPer1MOut:      9,
		CostPer1MInCached: 0.15,
	},
	Gemini35FlashLite: {
		ID:                Gemini35FlashLite,
		Name:              "google/gemini-3.5-flash-lite",
		Provider:          "perplexity",
		APIModel:          "google/gemini-3.5-flash-lite",
		Currency:          "USD",
		CostPer1MIn:       0.3,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.03,
	},
	Gemini36Flash: {
		ID:                Gemini36Flash,
		Name:              "google/gemini-3.6-flash",
		Provider:          "perplexity",
		APIModel:          "google/gemini-3.6-flash",
		Currency:          "USD",
		CostPer1MIn:       1.5,
		CostPer1MOut:      7.5,
		CostPer1MInCached: 0.15,
	},
	Gemini37Flash: {
		ID:                Gemini37Flash,
		Name:              "google/gemini-3.7-flash",
		Provider:          "perplexity",
		APIModel:          "google/gemini-3.7-flash",
		Currency:          "USD",
		CostPer1MIn:       0.375,
		CostPer1MOut:      1.875,
		CostPer1MInCached: 0.0375,
	},
	Llama370BInstruct: {
		ID:       Llama370BInstruct,
		Name:     "llama-3-70b-instruct",
		Provider: "perplexity",
		APIModel: "llama-3-70b-instruct",
		Currency: "USD",
	},
	Llama38BInstruct: {
		ID:       Llama38BInstruct,
		Name:     "llama-3-8b-instruct",
		Provider: "perplexity",
		APIModel: "llama-3-8b-instruct",
		Currency: "USD",
	},
	Llama3SonarLarge32KChat: {
		ID:       Llama3SonarLarge32KChat,
		Name:     "llama-3-sonar-large-32k-chat",
		Provider: "perplexity",
		APIModel: "llama-3-sonar-large-32k-chat",
		Currency: "USD",
	},
	Llama3SonarLarge32KOnline: {
		ID:       Llama3SonarLarge32KOnline,
		Name:     "llama-3-sonar-large-32k-online",
		Provider: "perplexity",
		APIModel: "llama-3-sonar-large-32k-online",
		Currency: "USD",
	},
	Llama3SonarSmall32KChat: {
		ID:       Llama3SonarSmall32KChat,
		Name:     "llama-3-sonar-small-32k-chat",
		Provider: "perplexity",
		APIModel: "llama-3-sonar-small-32k-chat",
		Currency: "USD",
	},
	Llama3SonarSmall32KOnline: {
		ID:       Llama3SonarSmall32KOnline,
		Name:     "llama-3-sonar-small-32k-online",
		Provider: "perplexity",
		APIModel: "llama-3-sonar-small-32k-online",
		Currency: "USD",
	},
	Llama31SonarHuge128KOnline: {
		ID:       Llama31SonarHuge128KOnline,
		Name:     "llama-3.1-sonar-huge-128k-online",
		Provider: "perplexity",
		APIModel: "llama-3.1-sonar-huge-128k-online",
		Currency: "USD",
	},
	Llama31SonarLarge128KOnline: {
		ID:       Llama31SonarLarge128KOnline,
		Name:     "llama-3.1-sonar-large-128k-online",
		Provider: "perplexity",
		APIModel: "llama-3.1-sonar-large-128k-online",
		Currency: "USD",
	},
	Llama31SonarSmall128KOnline: {
		ID:       Llama31SonarSmall128KOnline,
		Name:     "llama-3.1-sonar-small-128k-online",
		Provider: "perplexity",
		APIModel: "llama-3.1-sonar-small-128k-online",
		Currency: "USD",
	},
	Mistral7BInstruct: {
		ID:       Mistral7BInstruct,
		Name:     "mistral-7b-instruct",
		Provider: "perplexity",
		APIModel: "mistral-7b-instruct",
		Currency: "USD",
	},
	Mixtral8X22BInstruct: {
		ID:       Mixtral8X22BInstruct,
		Name:     "mixtral-8x22b-instruct",
		Provider: "perplexity",
		APIModel: "mixtral-8x22b-instruct",
		Currency: "USD",
	},
	Mixtral8X7BInstruct: {
		ID:       Mixtral8X7BInstruct,
		Name:     "mixtral-8x7b-instruct",
		Provider: "perplexity",
		APIModel: "mixtral-8x7b-instruct",
		Currency: "USD",
	},
	GPT5: {
		ID:                GPT5,
		Name:              "openai/gpt-5",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      10,
		CostPer1MInCached: 0.125,
	},
	GPT5Mini: {
		ID:                GPT5Mini,
		Name:              "openai/gpt-5-mini",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5-mini",
		Currency:          "USD",
		CostPer1MIn:       0.25,
		CostPer1MOut:      2,
		CostPer1MInCached: 0.025,
	},
	GPT51: {
		ID:                GPT51,
		Name:              "openai/gpt-5.1",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.1",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      10,
		CostPer1MInCached: 0.125,
	},
	GPT52: {
		ID:                GPT52,
		Name:              "openai/gpt-5.2",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.2",
		Currency:          "USD",
		CostPer1MIn:       1.75,
		CostPer1MOut:      14,
		CostPer1MInCached: 0.175,
	},
	GPT54: {
		ID:                GPT54,
		Name:              "openai/gpt-5.4",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.4",
		Currency:          "USD",
		CostPer1MIn:       2.5,
		CostPer1MOut:      15,
		CostPer1MInCached: 0.25,
	},
	GPT54Mini: {
		ID:                GPT54Mini,
		Name:              "openai/gpt-5.4-mini",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.4-mini",
		Currency:          "USD",
		CostPer1MIn:       0.75,
		CostPer1MOut:      4.5,
		CostPer1MInCached: 0.075,
	},
	GPT54Nano: {
		ID:                GPT54Nano,
		Name:              "openai/gpt-5.4-nano",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.4-nano",
		Currency:          "USD",
		CostPer1MIn:       0.2,
		CostPer1MOut:      1.25,
		CostPer1MInCached: 0.02,
	},
	GPT55: {
		ID:                GPT55,
		Name:              "openai/gpt-5.5",
		Provider:          "perplexity",
		APIModel:          "openai/gpt-5.5",
		Currency:          "USD",
		CostPer1MIn:       5,
		CostPer1MOut:      30,
		CostPer1MInCached: 0.5,
	},
	GPT56Luna: {
		ID:           GPT56Luna,
		Name:         "openai/gpt-5.6-luna",
		Provider:     "perplexity",
		APIModel:     "openai/gpt-5.6-luna",
		Currency:     "USD",
		CostPer1MIn:  0.2,
		CostPer1MOut: 1.2,
	},
	GPT56Sol: {
		ID:           GPT56Sol,
		Name:         "openai/gpt-5.6-sol",
		Provider:     "perplexity",
		APIModel:     "openai/gpt-5.6-sol",
		Currency:     "USD",
		CostPer1MIn:  5,
		CostPer1MOut: 30,
	},
	GPT56Terra: {
		ID:           GPT56Terra,
		Name:         "openai/gpt-5.6-terra",
		Provider:     "perplexity",
		APIModel:     "openai/gpt-5.6-terra",
		Currency:     "USD",
		CostPer1MIn:  2,
		CostPer1MOut: 12,
	},
	DeepseekV4Flash0731: {
		ID:                DeepseekV4Flash0731,
		Name:              "perplexity/deepseek-v4-flash-0731",
		Provider:          "perplexity",
		APIModel:          "perplexity/deepseek-v4-flash-0731",
		Currency:          "USD",
		CostPer1MIn:       0.13,
		CostPer1MOut:      0.26,
		CostPer1MInCached: 0.028,
		ContextWindow:     1000000,
		DefaultMaxTokens:  8192,
		CanReason:         true,
	},
	GLM52: {
		ID:                GLM52,
		Name:              "perplexity/glm-5.2",
		Provider:          "perplexity",
		APIModel:          "perplexity/glm-5.2",
		Currency:          "USD",
		CostPer1MIn:       1.4,
		CostPer1MOut:      4.4,
		CostPer1MInCached: 0.14,
		CanReason:         true,
	},
	KimiK27Code: {
		ID:                KimiK27Code,
		Name:              "perplexity/kimi-k2.7-code",
		Provider:          "perplexity",
		APIModel:          "perplexity/kimi-k2.7-code",
		Currency:          "USD",
		CostPer1MIn:       0.95,
		CostPer1MOut:      4,
		CostPer1MInCached: 0.19,
	},
	KimiK3: {
		ID:                KimiK3,
		Name:              "perplexity/kimi-k3",
		Provider:          "perplexity",
		APIModel:          "perplexity/kimi-k3",
		Currency:          "USD",
		CostPer1MIn:       3,
		CostPer1MOut:      15,
		CostPer1MInCached: 0.3,
		CanReason:         true,
	},
	Nemotron3Ultra550BA55B: {
		ID:                Nemotron3Ultra550BA55B,
		Name:              "perplexity/nemotron-3-ultra-550b-a55b",
		Provider:          "perplexity",
		APIModel:          "perplexity/nemotron-3-ultra-550b-a55b",
		Currency:          "USD",
		CostPer1MIn:       0.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.25,
	},
	Nemotron35Lightning30BA3B: {
		ID:                Nemotron35Lightning30BA3B,
		Name:              "perplexity/nemotron-3.5-lightning-30b-a3b",
		Provider:          "perplexity",
		APIModel:          "perplexity/nemotron-3.5-lightning-30b-a3b",
		Currency:          "USD",
		CostPer1MIn:       0.0115,
		CostPer1MOut:      0.17,
		CostPer1MInCached: 0.00115,
	},
	PerplexitySonar: {
		ID:                PerplexitySonar,
		Name:              "perplexity/sonar",
		Provider:          "perplexity",
		APIModel:          "perplexity/sonar",
		Currency:          "USD",
		CostPer1MIn:       0.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.0625,
	},
	Pplx7BChat: {
		ID:       Pplx7BChat,
		Name:     "pplx-7b-chat",
		Provider: "perplexity",
		APIModel: "pplx-7b-chat",
		Currency: "USD",
	},
	Pplx7BOnline: {
		ID:       Pplx7BOnline,
		Name:     "pplx-7b-online",
		Provider: "perplexity",
		APIModel: "pplx-7b-online",
		Currency: "USD",
	},
	Sonar: {
		ID:                    Sonar,
		Name:                  "Sonar",
		Provider:              "perplexity",
		APIModel:              "sonar",
		Currency:              "USD",
		CostPer1MIn:           1,
		CostPer1MOut:          1,
		ContextWindow:         128000,
		DefaultMaxTokens:      128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	SonarDeepResearch: {
		ID:                    SonarDeepResearch,
		Name:                  "Sonar Deep Research",
		Provider:              "perplexity",
		APIModel:              "sonar-deep-research",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		ContextWindow:         128000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	SonarPro: {
		ID:                    SonarPro,
		Name:                  "Sonar Pro",
		Provider:              "perplexity",
		APIModel:              "sonar-pro",
		Currency:              "USD",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		ContextWindow:         200000,
		DefaultMaxTokens:      128000,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	SonarReasoning: {
		ID:       SonarReasoning,
		Name:     "sonar-reasoning",
		Provider: "perplexity",
		APIModel: "sonar-reasoning",
		Currency: "USD",
	},
	SonarReasoningPro: {
		ID:                    SonarReasoningPro,
		Name:                  "Sonar Reasoning Pro",
		Provider:              "perplexity",
		APIModel:              "sonar-reasoning-pro",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          8,
		ContextWindow:         128000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Grok420MultiAgent: {
		ID:                Grok420MultiAgent,
		Name:              "xai/grok-4.20-multi-agent",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.20-multi-agent",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.2,
	},
	Grok420NonReasoning: {
		ID:                Grok420NonReasoning,
		Name:              "xai/grok-4.20-non-reasoning",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.20-non-reasoning",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.2,
	},
	Grok420Reasoning: {
		ID:                Grok420Reasoning,
		Name:              "xai/grok-4.20-reasoning",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.20-reasoning",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.2,
	},
	Grok43: {
		ID:                Grok43,
		Name:              "xai/grok-4.3",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.3",
		Currency:          "USD",
		CostPer1MIn:       1.25,
		CostPer1MOut:      2.5,
		CostPer1MInCached: 0.2,
	},
	Grok45: {
		ID:                Grok45,
		Name:              "xai/grok-4.5",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.5",
		Currency:          "USD",
		CostPer1MIn:       2,
		CostPer1MOut:      6,
		CostPer1MInCached: 0.3,
	},
	Grok46: {
		ID:                Grok46,
		Name:              "xai/grok-4.6",
		Provider:          "perplexity",
		APIModel:          "xai/grok-4.6",
		Currency:          "USD",
		CostPer1MIn:       2,
		CostPer1MOut:      6,
		CostPer1MInCached: 0.5,
	},
}
