// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package anthropic

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Claude5Fable   string = "claude-5-fable"
	Claude45Haiku  string = "claude-4.5-haiku"
	ClaudeMythos5  string = "claude-mythos-5"
	Claude45Opus   string = "claude-4.5-opus"
	Claude46Opus   string = "claude-4.6-opus"
	Claude47Opus   string = "claude-4.7-opus"
	Claude48Opus   string = "claude-4.8-opus"
	Claude5Opus    string = "claude-5-opus"
	Claude45Sonnet string = "claude-4.5-sonnet"
	Claude46Sonnet string = "claude-4.6-sonnet"
	Claude5Sonnet  string = "claude-5-sonnet"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Claude5Fable: {
		ID:                    Claude5Fable,
		Name:                  "Claude Fable 5",
		Provider:              "anthropic",
		APIModel:              "claude-fable-5",
		Currency:              "USD",
		CostPer1MIn:           10,
		CostPer1MOut:          50,
		CostPer1MInCached:     1,
		CostPer1MOutCached:    12.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Haiku: {
		ID:                    Claude45Haiku,
		Name:                  "Claude 4.5 Haiku",
		Provider:              "anthropic",
		APIModel:              "claude-haiku-4-5-20251001",
		Currency:              "USD",
		CostPer1MIn:           1,
		CostPer1MOut:          5,
		CostPer1MInCached:     0.1,
		CostPer1MOutCached:    1.25,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	ClaudeMythos5: {
		ID:                    ClaudeMythos5,
		Name:                  "Claude Mythos 5",
		Provider:              "anthropic",
		APIModel:              "claude-mythos-5",
		Currency:              "USD",
		CostPer1MIn:           10,
		CostPer1MOut:          50,
		CostPer1MInCached:     1,
		CostPer1MOutCached:    12.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Opus: {
		ID:                    Claude45Opus,
		Name:                  "Claude 4.5 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-5-20251101",
		Currency:              "USD",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     0.5,
		CostPer1MOutCached:    6.25,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Opus: {
		ID:                    Claude46Opus,
		Name:                  "Claude 4.6 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-6",
		Currency:              "USD",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     0.5,
		CostPer1MOutCached:    6.25,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude47Opus: {
		ID:                    Claude47Opus,
		Name:                  "Claude 4.7 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-7",
		Currency:              "USD",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     0.5,
		CostPer1MOutCached:    6.25,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude48Opus: {
		ID:                    Claude48Opus,
		Name:                  "Claude 4.8 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-8",
		Currency:              "USD",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     0.5,
		CostPer1MOutCached:    6.25,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Opus: {
		ID:                    Claude5Opus,
		Name:                  "Claude Opus 5",
		Provider:              "anthropic",
		APIModel:              "claude-opus-5",
		Currency:              "USD",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     0.5,
		CostPer1MOutCached:    6.25,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Sonnet: {
		ID:                    Claude45Sonnet,
		Name:                  "Claude 4.5 Sonnet",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-4-5-20250929",
		Currency:              "USD",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.3,
		CostPer1MOutCached:    3.75,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Sonnet: {
		ID:                    Claude46Sonnet,
		Name:                  "Claude 4.6 Sonnet",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-4-6",
		Currency:              "USD",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.3,
		CostPer1MOutCached:    3.75,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Sonnet: {
		ID:                    Claude5Sonnet,
		Name:                  "Claude Sonnet 5",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-5",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          10,
		CostPer1MInCached:     0.2,
		CostPer1MOutCached:    2.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
