package anthropic

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Anthropic provider identifier and Claude model IDs for this registry.
const (
	Claude3Haiku   string = "claude-3-haiku"
	Claude4Opus    string = "claude-4-opus"
	Claude41Opus   string = "claude-4.1-opus"
	Claude4Sonnet  string = "claude-4-sonnet"
	Claude45Sonnet string = "claude-4.5-sonnet"
	Claude45Opus   string = "claude-4.5-opus"
	Claude45Haiku  string = "claude-4.5-haiku"
	Claude46Opus   string = "claude-4.6-opus"
	Claude46Sonnet string = "claude-4.6-sonnet"
	Claude47Opus   string = "claude-4.7-opus"
	Claude48Opus   string = "claude-4.8-opus"
	Claude5Opus    string = "claude-5-opus"
	Claude5Sonnet  string = "claude-5-sonnet"
	Claude5Fable   string = "claude-5-fable"
	Claude5Mythos  string = "claude-5-mythos"
)

// Models maps Anthropic model IDs to their configurations.
//
// Pricing source:
// https://platform.claude.com/docs/en/about-claude/models/overview.
// Fetched: 2026-07-26.
var Models = map[string]llm.Model{
	Claude3Haiku: {
		ID:                  Claude3Haiku,
		Name:                "Claude 3 Haiku",
		Provider:            "anthropic",
		APIModel:            "claude-3-haiku-20240307",
		CostPer1MIn:         0.25,
		CostPer1MOut:        1.25,
		CostPer1MInCached:   0.3,
		CostPer1MOutCached:  0.03,
		ContextWindow:       200000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
	Claude4Sonnet: {
		ID:                  Claude4Sonnet,
		Name:                "Claude 4 Sonnet",
		Provider:            "anthropic",
		APIModel:            "claude-sonnet-4-20250514",
		CostPer1MIn:         3,
		CostPer1MOut:        15,
		CostPer1MInCached:   3.75,
		CostPer1MOutCached:  0.3,
		ContextWindow:       200000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Claude4Opus: {
		ID:                  Claude4Opus,
		Name:                "Claude 4 Opus",
		Provider:            "anthropic",
		APIModel:            "claude-opus-4-20250514",
		CostPer1MIn:         15,
		CostPer1MOut:        75,
		CostPer1MInCached:   18.75,
		CostPer1MOutCached:  1.5,
		ContextWindow:       200000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Claude41Opus: {
		ID:                  Claude41Opus,
		Name:                "Claude 4.1 Opus",
		Provider:            "anthropic",
		APIModel:            "claude-opus-4-1",
		CostPer1MIn:         15,
		CostPer1MOut:        75,
		CostPer1MInCached:   18.75,
		CostPer1MOutCached:  1.5,
		ContextWindow:       200000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
	Claude45Sonnet: {
		ID:                    Claude45Sonnet,
		Name:                  "Claude 4.5 Sonnet",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-4-5-20250929",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.3,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Opus: {
		ID:                    Claude45Opus,
		Name:                  "Claude 4.5 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-5-20251101",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude45Haiku: {
		ID:                    Claude45Haiku,
		Name:                  "Claude 4.5 Haiku",
		Provider:              "anthropic",
		APIModel:              "claude-haiku-4-5-20251001",
		CostPer1MIn:           1,
		CostPer1MOut:          5,
		CostPer1MInCached:     1.25,
		CostPer1MOutCached:    0.1,
		ContextWindow:         200000,
		DefaultMaxTokens:      50000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Opus: {
		ID:                    Claude46Opus,
		Name:                  "Claude 4.6 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-6-20260205",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude46Sonnet: {
		ID:                    Claude46Sonnet,
		Name:                  "Claude 4.6 Sonnet",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-4-6",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.3,
		ContextWindow:         200000,
		DefaultMaxTokens:      64000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude47Opus: {
		ID:                    Claude47Opus,
		Name:                  "Claude 4.7 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-7",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude48Opus: {
		ID:                    Claude48Opus,
		Name:                  "Claude 4.8 Opus",
		Provider:              "anthropic",
		APIModel:              "claude-opus-4-8",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Opus: {
		ID:                    Claude5Opus,
		Name:                  "Claude Opus 5",
		Provider:              "anthropic",
		APIModel:              "claude-opus-5",
		CostPer1MIn:           5,
		CostPer1MOut:          25,
		CostPer1MInCached:     6.25,
		CostPer1MOutCached:    0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Sonnet: {
		ID:                    Claude5Sonnet,
		Name:                  "Claude Sonnet 5",
		Provider:              "anthropic",
		APIModel:              "claude-sonnet-5",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     3.75,
		CostPer1MOutCached:    0.3,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Fable: {
		ID:                    Claude5Fable,
		Name:                  "Claude Fable 5",
		Provider:              "anthropic",
		APIModel:              "claude-fable-5",
		CostPer1MIn:           10,
		CostPer1MOut:          50,
		CostPer1MInCached:     12.5,
		CostPer1MOutCached:    1,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Claude5Mythos: {
		ID:                    Claude5Mythos,
		Name:                  "Claude Mythos 5",
		Provider:              "anthropic",
		APIModel:              "claude-mythos-5",
		CostPer1MIn:           10,
		CostPer1MOut:          50,
		CostPer1MInCached:     12.5,
		CostPer1MOutCached:    1,
		ContextWindow:         1000000,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
