// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-09-05
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package together

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	MiniMaxM3           string = "together.MiniMaxAI/MiniMax-M3"
	TernaryBonsai27B    string = "together.Prism-ML/Ternary-Bonsai-27B"
	Qwen35_9B           string = "together.Qwen/Qwen3.5-9B"
	Qwen36Plus          string = "together.Qwen/Qwen3.6-Plus"
	Qwen37Max           string = "together.Qwen/Qwen3.7-Max"
	Qwen37Plus          string = "together.Qwen/Qwen3.7-Plus"
	Qwen3824TA95B       string = "together.Qwen/Qwen3.8-2.4T-A95B"
	Qwen38Flash         string = "together.Qwen/Qwen3.8-Flash"
	DeepSeekV4Flash0731 string = "together.deepseek-ai/DeepSeek-V4-Flash-0731"
	DeepSeekV4Pro0813   string = "together.deepseek-ai/DeepSeek-V4-Pro-0813"
	Llama33_70B         string = "together.meta-llama/Llama-3.3-70B-Instruct-Turbo"
	MuseGlimmer30B      string = "together.meta-models/Muse-Glimmer-30B"
	KimiK3              string = "together.moonshotai/Kimi-K3"
	GPTOss120B          string = "together.openai/gpt-oss-120b"
	Inkling             string = "together.thinkingmachines/Inkling"
	GLM52               string = "together.zai-org/GLM-5.2"
	GLM53               string = "together.zai-org/GLM-5.3"
	GLM53Flash          string = "together.zai-org/GLM-5.3-Flash"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	MiniMaxM3: {
		ID:                    MiniMaxM3,
		Name:                  "Together – MiniMax M3",
		Provider:              "together",
		APIModel:              "MiniMaxAI/MiniMax-M3",
		Currency:              "USD",
		CostPer1MIn:           0.3,
		CostPer1MOut:          1.2,
		CostPer1MInCached:     0.06,
		ContextWindow:         524288,
		DefaultMaxTokens:      250000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	TernaryBonsai27B: {
		ID:                    TernaryBonsai27B,
		Name:                  "Ternary Bonsai 27B",
		Provider:              "together",
		APIModel:              "Prism-ML/Ternary-Bonsai-27B",
		Currency:              "USD",
		ContextWindow:         262144,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Qwen35_9B: {
		ID:                    Qwen35_9B,
		Name:                  "Together – Qwen 3.5 9B",
		Provider:              "together",
		APIModel:              "Qwen/Qwen3.5-9B",
		Currency:              "USD",
		CostPer1MIn:           0.17,
		CostPer1MOut:          0.25,
		ContextWindow:         262144,
		DefaultMaxTokens:      65536,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Qwen36Plus: {
		ID:                    Qwen36Plus,
		Name:                  "Qwen3.6 Plus",
		Provider:              "together",
		APIModel:              "Qwen/Qwen3.6-Plus",
		Currency:              "USD",
		CostPer1MIn:           0.5,
		CostPer1MOut:          3,
		ContextWindow:         1000000,
		DefaultMaxTokens:      500000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Qwen37Max: {
		ID:                    Qwen37Max,
		Name:                  "Together – Qwen 3.7 Max",
		Provider:              "together",
		APIModel:              "Qwen/Qwen3.7-Max",
		Currency:              "USD",
		CostPer1MIn:           2.5,
		CostPer1MOut:          7.5,
		CostPer1MInCached:     0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      500000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Qwen37Plus: {
		ID:                    Qwen37Plus,
		Name:                  "Qwen3.7 Plus",
		Provider:              "together",
		APIModel:              "Qwen/Qwen3.7-Plus",
		Currency:              "USD",
		CostPer1MIn:           0.32,
		CostPer1MOut:          1.28,
		ContextWindow:         1000000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Qwen3824TA95B: {
		ID:                    Qwen3824TA95B,
		Name:                  "Qwen3.8-2.4T-A95B",
		Provider:              "together",
		APIModel:              "Qwen/Qwen3.8-2.4T-A95B",
		Currency:              "USD",
		CostPer1MIn:           2,
		CostPer1MOut:          6,
		CostPer1MInCached:     0.5,
		ContextWindow:         1000000,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	Qwen38Flash: {
		ID:                  Qwen38Flash,
		Name:                "Qwen3.8 Flash",
		Provider:            "together",
		APIModel:            "Qwen/Qwen3.8-Flash",
		Currency:            "USD",
		CostPer1MIn:         0.15,
		CostPer1MOut:        0.47,
		ContextWindow:       1000000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	DeepSeekV4Flash0731: {
		ID:                    DeepSeekV4Flash0731,
		Name:                  "DeepSeek V4 Flash 0731",
		Provider:              "together",
		APIModel:              "deepseek-ai/DeepSeek-V4-Flash-0731",
		Currency:              "USD",
		CostPer1MIn:           0.14,
		CostPer1MOut:          0.28,
		CostPer1MInCached:     0.03,
		ContextWindow:         1048576,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	DeepSeekV4Pro0813: {
		ID:                    DeepSeekV4Pro0813,
		Name:                  "DeepSeek V4 Pro 0813",
		Provider:              "together",
		APIModel:              "deepseek-ai/DeepSeek-V4-Pro-0813",
		Currency:              "USD",
		CostPer1MIn:           1.32,
		CostPer1MOut:          3.96,
		CostPer1MInCached:     0.13,
		ContextWindow:         1048576,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Llama33_70B: {
		ID:                    Llama33_70B,
		Name:                  "Together – Llama 3.3 70B Instruct Turbo",
		Provider:              "together",
		APIModel:              "meta-llama/Llama-3.3-70B-Instruct-Turbo",
		Currency:              "USD",
		CostPer1MIn:           1.04,
		CostPer1MOut:          1.04,
		ContextWindow:         131072,
		DefaultMaxTokens:      131072,
		SupportsStructuredOut: true,
	},
	MuseGlimmer30B: {
		ID:                  MuseGlimmer30B,
		Name:                "Muse Glimmer 30B",
		Provider:            "together",
		APIModel:            "meta-models/Muse-Glimmer-30B",
		Currency:            "USD",
		CostPer1MIn:         0.35,
		CostPer1MOut:        1.5,
		CostPer1MInCached:   0.04,
		ContextWindow:       131072,
		DefaultMaxTokens:    8192,
		SupportsAttachments: true,
	},
	KimiK3: {
		ID:                    KimiK3,
		Name:                  "Kimi K3",
		Provider:              "together",
		APIModel:              "moonshotai/Kimi-K3",
		Currency:              "USD",
		CostPer1MIn:           3,
		CostPer1MOut:          15,
		CostPer1MInCached:     0.3,
		ContextWindow:         1048576,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "Together – GPT-OSS 120B",
		Provider:              "together",
		APIModel:              "openai/gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		ContextWindow:         131072,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	Inkling: {
		ID:                    Inkling,
		Name:                  "Inkling",
		Provider:              "together",
		APIModel:              "thinkingmachines/Inkling",
		Currency:              "USD",
		CostPer1MIn:           1,
		CostPer1MOut:          4.05,
		CostPer1MInCached:     0.17,
		ContextWindow:         524288,
		DefaultMaxTokens:      131072,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GLM52: {
		ID:                    GLM52,
		Name:                  "Together – GLM 5.2",
		Provider:              "together",
		APIModel:              "zai-org/GLM-5.2",
		Currency:              "USD",
		CostPer1MIn:           1.4,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.26,
		ContextWindow:         1048575,
		DefaultMaxTokens:      128000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GLM53: {
		ID:                    GLM53,
		Name:                  "GLM-5.3",
		Provider:              "together",
		APIModel:              "zai-org/GLM-5.3",
		Currency:              "USD",
		CostPer1MIn:           1.4,
		CostPer1MOut:          4.4,
		CostPer1MInCached:     0.26,
		ContextWindow:         1048575,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	GLM53Flash: {
		ID:                    GLM53Flash,
		Name:                  "GLM-5.3 Flash",
		Provider:              "together",
		APIModel:              "zai-org/GLM-5.3-Flash",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.5,
		CostPer1MInCached:     0.03,
		ContextWindow:         1048575,
		DefaultMaxTokens:      8192,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
