// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package cohere

import (
	"github.com/joakimcarlsson/ai/rerankers"
)

// Model IDs served by this catalog.
const (
	RerankEnV3    string = "rerank-english-v3.0"
	RerankMultiV3 string = "rerank-multilingual-v3.0"
	Rerank35      string = "rerank-v3.5"
	Rerank4Fast   string = "rerank-v4.0-fast"
	Rerank4Pro    string = "rerank-v4.0-pro"
)

// Models maps model IDs to their configurations.
var Models = map[string]rerankers.RerankerModel{
	RerankEnV3: {
		ID:              RerankEnV3,
		Name:            "Cohere Rerank English v3.0",
		Provider:        "cohere",
		APIModel:        "rerank-english-v3.0",
		Currency:        "USD",
		CostPer1MTokens: 2,
		MaxQueryTokens:  2048,
		MaxTotalTokens:  4000,
	},
	RerankMultiV3: {
		ID:              RerankMultiV3,
		Name:            "Cohere Rerank Multilingual v3.0",
		Provider:        "cohere",
		APIModel:        "rerank-multilingual-v3.0",
		Currency:        "USD",
		CostPer1MTokens: 2,
		MaxQueryTokens:  2048,
		MaxTotalTokens:  4000,
	},
	Rerank35: {
		ID:              Rerank35,
		Name:            "Cohere Rerank v3.5",
		Provider:        "cohere",
		APIModel:        "rerank-v3.5",
		Currency:        "USD",
		CostPer1MTokens: 2,
		MaxQueryTokens:  2048,
		MaxTotalTokens:  4000,
	},
	Rerank4Fast: {
		ID:              Rerank4Fast,
		Name:            "Cohere Rerank v4.0 Fast",
		Provider:        "cohere",
		APIModel:        "rerank-v4.0-fast",
		Currency:        "USD",
		CostPer1MTokens: 2,
		MaxQueryTokens:  4096,
		MaxTotalTokens:  32000,
	},
	Rerank4Pro: {
		ID:              Rerank4Pro,
		Name:            "Cohere Rerank v4.0 Pro",
		Provider:        "cohere",
		APIModel:        "rerank-v4.0-pro",
		Currency:        "USD",
		CostPer1MTokens: 2.5,
		MaxQueryTokens:  4096,
		MaxTotalTokens:  32000,
	},
}
