// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	TextEmbedding3Large string = "text-embedding-3-large"
	TextEmbedding3Small string = "text-embedding-3-small"
	AdaEmbedding002     string = "text-embedding-ada-002"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	TextEmbedding3Large: {
		ID:              TextEmbedding3Large,
		Name:            "Text Embedding 3 Large",
		Provider:        "openai",
		APIModel:        "text-embedding-3-large",
		Currency:        "USD",
		CostPer1MTokens: 0.13,
		MaxInputTokens:  8192,
		EmbeddingDims:   3072,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			1536,
			2048,
			3072,
		},
		MaxBatchSize:      2048,
		MaxTokensPerBatch: 1000000,
	},
	TextEmbedding3Small: {
		ID:                  TextEmbedding3Small,
		Name:                "Text Embedding 3 Small",
		Provider:            "openai",
		APIModel:            "text-embedding-3-small",
		Currency:            "USD",
		CostPer1MTokens:     0.02,
		MaxInputTokens:      8192,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{512, 1536},
		MaxBatchSize:        2048,
		MaxTokensPerBatch:   1000000,
	},
	AdaEmbedding002: {
		ID:                  AdaEmbedding002,
		Name:                "Ada Embedding 002",
		Provider:            "openai",
		APIModel:            "text-embedding-ada-002",
		Currency:            "USD",
		CostPer1MTokens:     0.1,
		MaxInputTokens:      8192,
		EmbeddingDims:       1536,
		SupportedDimensions: []int{1536},
		MaxBatchSize:        2048,
		MaxTokensPerBatch:   1000000,
	},
}
