// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package bedrock

import (
	"github.com/joakimcarlsson/ai/embeddings"
)

// Model IDs served by this catalog.
const (
	AmazonNova2MultimodalEmbeddingsV10 string = "amazon.nova-2-multimodal-embeddings-v1-0"
	AmazonTitanEmbedG1Text02           string = "amazon.titan-embed-g1-text-02"
	TitanEmbedImageG1                  string = "amazon.titan-embed-image-v1"
	AmazonTitanEmbedTextV1             string = "amazon.titan-embed-text-v1"
	TitanEmbedV2                       string = "amazon.titan-embed-text-v2:0"
	CohereEmbedEn                      string = "cohere.embed-english-v3"
	CohereEmbedMulti                   string = "cohere.embed-multilingual-v3"
	CohereEmbedV4                      string = "cohere.embed-v4:0"
	TitanEmbeddingsG1Image             string = "titan-embeddings-g1-image"
	Titanembeddingsv2TextInput         string = "titanembeddingsv2-text-input"
	TwelvelabsMarengoEmbed27V10        string = "twelvelabs.marengo-embed-2-7-v1-0"
	TwelvelabsMarengoEmbed30V10        string = "twelvelabs.marengo-embed-3-0-v1-0"
)

// Models maps model IDs to their configurations.
var Models = map[string]embeddings.EmbeddingModel{
	AmazonNova2MultimodalEmbeddingsV10: {
		ID:       AmazonNova2MultimodalEmbeddingsV10,
		Name:     "Amazon Nova Multimodal Embeddings",
		Provider: "bedrock",
		APIModel: "amazon.nova-2-multimodal-embeddings-v1:0",
		Currency: "USD",
	},
	AmazonTitanEmbedG1Text02: {
		ID:             AmazonTitanEmbedG1Text02,
		Name:           "Titan Embeddings G1 - Text v2",
		Provider:       "bedrock",
		APIModel:       "amazon.titan-embed-g1-text-02",
		Currency:       "USD",
		MaxInputTokens: 8000,
	},
	TitanEmbedImageG1: {
		ID:                  TitanEmbedImageG1,
		Name:                "Amazon Titan Multimodal Embeddings G1",
		Provider:            "bedrock",
		APIModel:            "amazon.titan-embed-image-v1",
		Currency:            "USD",
		CostPer1MTokens:     0.8,
		MaxInputTokens:      256,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{256, 384, 1024},
		MaxBatchSize:        1,
	},
	AmazonTitanEmbedTextV1: {
		ID:             AmazonTitanEmbedTextV1,
		Name:           "Titan Embeddings G1 Text",
		Provider:       "bedrock",
		APIModel:       "amazon.titan-embed-text-v1",
		Currency:       "USD",
		MaxInputTokens: 8000,
	},
	TitanEmbedV2: {
		ID:                  TitanEmbedV2,
		Name:                "Amazon Titan Embed Text v2",
		Provider:            "bedrock",
		APIModel:            "amazon.titan-embed-text-v2:0",
		Currency:            "USD",
		CostPer1MTokens:     0.02,
		MaxInputTokens:      8000,
		EmbeddingDims:       1024,
		SupportedDimensions: []int{256, 512, 1024},
		MaxBatchSize:        1,
	},
	CohereEmbedEn: {
		ID:              CohereEmbedEn,
		Name:            "Cohere Embed English v3 (Bedrock)",
		Provider:        "bedrock",
		APIModel:        "cohere.embed-english-v3",
		Currency:        "USD",
		CostPer1MTokens: 0.1,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
		MaxBatchSize:    96,
	},
	CohereEmbedMulti: {
		ID:              CohereEmbedMulti,
		Name:            "Cohere Embed Multilingual v3 (Bedrock)",
		Provider:        "bedrock",
		APIModel:        "cohere.embed-multilingual-v3",
		Currency:        "USD",
		CostPer1MTokens: 0.1,
		MaxInputTokens:  512,
		EmbeddingDims:   1024,
		MaxBatchSize:    96,
	},
	CohereEmbedV4: {
		ID:              CohereEmbedV4,
		Name:            "Cohere Embed v4 (Bedrock)",
		Provider:        "bedrock",
		APIModel:        "cohere.embed-v4:0",
		Currency:        "USD",
		CostPer1MTokens: 0.12,
		MaxInputTokens:  128000,
		EmbeddingDims:   1536,
		SupportedDimensions: []int{
			256,
			512,
			1024,
			1536,
		},
		MaxBatchSize: 96,
	},
	TitanEmbeddingsG1Image: {
		ID:       TitanEmbeddingsG1Image,
		Name:     "Titan Embeddings G1 Image",
		Provider: "bedrock",
		APIModel: "titan-embeddings-g1-image",
		Currency: "USD",
	},
	Titanembeddingsv2TextInput: {
		ID:       Titanembeddingsv2TextInput,
		Name:     "TitanEmbeddingsV2-Text-input",
		Provider: "bedrock",
		APIModel: "titanembeddingsv2-text-input",
		Currency: "USD",
	},
	TwelvelabsMarengoEmbed27V10: {
		ID:       TwelvelabsMarengoEmbed27V10,
		Name:     "Marengo Embed v2.7",
		Provider: "bedrock",
		APIModel: "twelvelabs.marengo-embed-2-7-v1:0",
		Currency: "USD",
	},
	TwelvelabsMarengoEmbed30V10: {
		ID:       TwelvelabsMarengoEmbed30V10,
		Name:     "Marengo Embed 3.0",
		Provider: "bedrock",
		APIModel: "twelvelabs.marengo-embed-3-0-v1:0",
		Currency: "USD",
	},
}
