// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://api.berget.ai/v1/models
// Generated: 2026-08-12
//
// Berget bills transcription in EUR per audio second; CostPer1MIn holds
// the per-minute equivalent, matching the AssemblyAI convention in this
// repository.
//
// Display names, audio formats and timestamp support are not part of
// the models response and are carried over from the previous catalog.

package berget

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	KBWhisperLarge       string = "KBLab/kb-whisper-large"
	NBWhisperLarge       string = "NbAiLab/nb-whisper-large"
	FasterWhisperLargeV3 string = "Systran/faster-whisper-large-v3"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	KBWhisperLarge: {
		ID:           KBWhisperLarge,
		Name:         "KB Whisper Large (Swedish)",
		Provider:     "berget",
		APIModel:     "KBLab/kb-whisper-large",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:  true,
		SupportsTranslation: true,
	},
	NBWhisperLarge: {
		ID:           NBWhisperLarge,
		Name:         "NB Whisper Large (Norwegian)",
		Provider:     "berget",
		APIModel:     "NbAiLab/nb-whisper-large",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:  true,
		SupportsTranslation: true,
	},
	FasterWhisperLargeV3: {
		ID:           FasterWhisperLargeV3,
		Name:         "Faster Whisper Large v3",
		Provider:     "berget",
		APIModel:     "Systran/faster-whisper-large-v3",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:  true,
		SupportsTranslation: true,
	},
}
