// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package berget

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	KBWhisperLarge       string = "KBLab/kb-whisper-large"
	NBWhisperLarge       string = "NbAiLab/nb-whisper-large"
	FasterWhisperLargeV3 string = "Systran/faster-whisper-large-v3"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	KBWhisperLarge: {
		ID:           KBWhisperLarge,
		Name:         "KB Whisper Large (Swedish)",
		Provider:     "berget",
		APIModel:     "KBLab/kb-whisper-large",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"m4a",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"wav",
			"webm",
		},
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsDiarization:    true,
		SupportsStreaming:      true,
		SupportedResponseFormats: []string{
			"aud",
			"diarized_json",
			"json",
			"srt",
			"text",
			"verbose_json",
			"vtt",
			"vtt_json",
		},
	},
	NBWhisperLarge: {
		ID:           NBWhisperLarge,
		Name:         "NB Whisper Large (Norwegian)",
		Provider:     "berget",
		APIModel:     "NbAiLab/nb-whisper-large",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"m4a",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"wav",
			"webm",
		},
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsDiarization:    true,
		SupportsStreaming:      true,
		SupportedResponseFormats: []string{
			"aud",
			"diarized_json",
			"json",
			"srt",
			"text",
			"verbose_json",
			"vtt",
			"vtt_json",
		},
	},
	FasterWhisperLargeV3: {
		ID:           FasterWhisperLargeV3,
		Name:         "Faster Whisper Large v3",
		Provider:     "berget",
		APIModel:     "Systran/faster-whisper-large-v3",
		Currency:     "EUR",
		CostPer1MIn:  0.00198,
		CostPer1MOut: 0.00198,
		SupportedFormats: []string{
			"m4a",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"wav",
			"webm",
		},
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsDiarization:    true,
		SupportsStreaming:      true,
		SupportedResponseFormats: []string{
			"aud",
			"diarized_json",
			"json",
			"srt",
			"text",
			"verbose_json",
			"vtt",
			"vtt_json",
		},
	},
}
