// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MTokens is per 1M input tokens, in the currency the
// provider bills in.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package voyage

import (
	"github.com/joakimcarlsson/ai/rerankers"
)

// Model IDs served by this catalog.
const (
	Rerank1      string = "rerank-1"
	Rerank2      string = "rerank-2"
	Rerank2Lite  string = "rerank-2-lite"
	Rerank25     string = "rerank-2.5"
	Rerank25Lite string = "rerank-2.5-lite"
	RerankLite1  string = "rerank-lite-1"
)

// Models maps model IDs to their configurations.
var Models = map[string]rerankers.RerankerModel{
	Rerank1: {
		ID:              Rerank1,
		Name:            "Rerank 1 [Legacy]",
		Provider:        "voyage",
		APIModel:        "rerank-1",
		Currency:        "USD",
		CostPer1MTokens: 0.05,
		MaxQueryTokens:  2000,
		MaxTotalTokens:  8000,
	},
	Rerank2: {
		ID:              Rerank2,
		Name:            "Rerank 2 [Legacy]",
		Provider:        "voyage",
		APIModel:        "rerank-2",
		Currency:        "USD",
		CostPer1MTokens: 0.05,
		MaxQueryTokens:  4000,
		MaxTotalTokens:  16000,
	},
	Rerank2Lite: {
		ID:              Rerank2Lite,
		Name:            "Rerank 2 Lite [Legacy]",
		Provider:        "voyage",
		APIModel:        "rerank-2-lite",
		Currency:        "USD",
		CostPer1MTokens: 0.02,
		MaxQueryTokens:  2000,
		MaxTotalTokens:  8000,
	},
	Rerank25: {
		ID:              Rerank25,
		Name:            "Rerank 2.5",
		Provider:        "voyage",
		APIModel:        "rerank-2.5",
		Currency:        "USD",
		CostPer1MTokens: 0.05,
		MaxQueryTokens:  8000,
		MaxTotalTokens:  32000,
	},
	Rerank25Lite: {
		ID:              Rerank25Lite,
		Name:            "Rerank 2.5 Lite",
		Provider:        "voyage",
		APIModel:        "rerank-2.5-lite",
		Currency:        "USD",
		CostPer1MTokens: 0.02,
		MaxQueryTokens:  8000,
		MaxTotalTokens:  32000,
	},
	RerankLite1: {
		ID:              RerankLite1,
		Name:            "Rerank Lite 1 [Legacy]",
		Provider:        "voyage",
		APIModel:        "rerank-lite-1",
		Currency:        "USD",
		CostPer1MTokens: 0.02,
		MaxQueryTokens:  1000,
		MaxTotalTokens:  4000,
	},
}
