// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MIn and CostPer1MOut are per 1M tokens where the model is
// priced per token, and per audio minute where it is priced by
// duration, matching the convention the hand-written catalogs use.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/stt"
)

// Model IDs served by this catalog.
const (
	GPT4oMiniTranscribe         string = "gpt-4o-mini-transcribe"
	GPT4OMiniTranscribe20250320 string = "gpt-4o-mini-transcribe-2025-03-20"
	GPT4oTranscribe             string = "gpt-4o-transcribe"
	GPT4oTranscribeDiarize      string = "gpt-4o-transcribe-diarize"
	GPTLiveTranscribe           string = "gpt-live-transcribe"
	GPTRealtimeTranslate        string = "gpt-realtime-translate"
	GPTRealtimeWhisper          string = "gpt-realtime-whisper"
	GPTTranscribe               string = "gpt-transcribe"
	Whisper1                    string = "whisper-1"
)

// Models maps model IDs to their configurations.
var Models = map[string]stt.TranscriptionModel{
	GPT4oMiniTranscribe: {
		ID:            GPT4oMiniTranscribe,
		Name:          "GPT-4o Mini Transcribe",
		Provider:      "openai",
		APIModel:      "gpt-4o-mini-transcribe",
		Currency:      "USD",
		CostPer1MIn:   1.25,
		CostPer1MOut:  5,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4OMiniTranscribe20250320: {
		ID:       GPT4OMiniTranscribe20250320,
		Name:     "",
		Provider: "openai",
		APIModel: "gpt-4o-mini-transcribe-2025-03-20",
		Currency: "USD",
	},
	GPT4oTranscribe: {
		ID:            GPT4oTranscribe,
		Name:          "GPT-4o Transcribe",
		Provider:      "openai",
		APIModel:      "gpt-4o-transcribe",
		Currency:      "USD",
		CostPer1MIn:   2.5,
		CostPer1MOut:  10,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportedResponseFormats: []string{"json"},
	},
	GPT4oTranscribeDiarize: {
		ID:            GPT4oTranscribeDiarize,
		Name:          "GPT-4o Transcribe Diarize",
		Provider:      "openai",
		APIModel:      "gpt-4o-transcribe-diarize",
		Currency:      "USD",
		CostPer1MIn:   2.5,
		CostPer1MOut:  10,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsDiarization:      true,
		SupportedResponseFormats: []string{"json", "text", "diarized_json"},
	},
	GPTLiveTranscribe: {
		ID:                GPTLiveTranscribe,
		Name:              "GPT Live Transcribe",
		Provider:          "openai",
		APIModel:          "gpt-live-transcribe",
		Currency:          "USD",
		CostPer1MIn:       0.017,
		SupportsStreaming: true,
	},
	GPTRealtimeTranslate: {
		ID:            GPTRealtimeTranslate,
		Name:          "GPT Realtime Translate",
		Provider:      "openai",
		APIModel:      "gpt-realtime-translate",
		Currency:      "USD",
		CostPer1MIn:   0.034,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
	GPTRealtimeWhisper: {
		ID:            GPTRealtimeWhisper,
		Name:          "GPT Realtime Whisper",
		Provider:      "openai",
		APIModel:      "gpt-realtime-whisper",
		Currency:      "USD",
		CostPer1MIn:   0.017,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsStreaming:        true,
		SupportedResponseFormats: []string{"json"},
	},
	GPTTranscribe: {
		ID:                GPTTranscribe,
		Name:              "GPT Transcribe",
		Provider:          "openai",
		APIModel:          "gpt-transcribe",
		Currency:          "USD",
		CostPer1MIn:       0.0045,
		SupportsStreaming: true,
	},
	Whisper1: {
		ID:            Whisper1,
		Name:          "Whisper v2",
		Provider:      "openai",
		APIModel:      "whisper-1",
		Currency:      "USD",
		CostPer1MIn:   0.006,
		MaxFileSizeMB: 25,
		SupportedFormats: []string{
			"flac",
			"mp3",
			"mp4",
			"mpeg",
			"mpga",
			"m4a",
			"ogg",
			"wav",
			"webm",
		},
		SupportsTimestamps:     true,
		SupportsWordTimestamps: true,
		SupportsTranslation:    true,
		SupportedResponseFormats: []string{
			"json",
			"text",
			"srt",
			"verbose_json",
			"vtt",
		},
	},
}
