// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// CostPer1MChars is per 1M characters, in the currency the provider
// bills in. Default format and latency are not published and are
// carried over from the previous catalog.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package deepgram

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	Aura1   string = "aura-1"
	Aura2   string = "aura-2"
	FluxTTS string = "flux-tts"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	Aura1: {
		ID:       Aura1,
		Name:     "Aura-1",
		Provider: "deepgram",
		APIModel: "aura-1",
		Currency: "USD",
	},
	Aura2: {
		ID:       Aura2,
		Name:     "Aura-2",
		Provider: "deepgram",
		APIModel: "aura-2",
		Currency: "USD",
	},
	FluxTTS: {
		ID:       FluxTTS,
		Name:     "Flux TTS",
		Provider: "deepgram",
		APIModel: "flux-tts",
		Currency: "USD",
	},
}
