package deepgram

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Deepgram Aura text-to-speech model/voice IDs. Deepgram's TTS model
// identifier encodes voice and language together (format:
// aura[-2]-<voice>-<lang>).
const (
	Aura2Thalia    string = "aura-2-thalia-en"
	Aura2Andromeda string = "aura-2-andromeda-en"
	Aura2Helena    string = "aura-2-helena-en"
	Aura2Amalthea  string = "aura-2-amalthea-en"
	Aura2Apollo    string = "aura-2-apollo-en"
	Aura2Arcas     string = "aura-2-arcas-en"
	Aura2Aries     string = "aura-2-aries-en"
	Aura2Asteria   string = "aura-2-asteria-en"
	Aura2Athena    string = "aura-2-athena-en"
	Aura2Atlas     string = "aura-2-atlas-en"
	Aura2Aurora    string = "aura-2-aurora-en"
	Aura2Callista  string = "aura-2-callista-en"
	Aura2Cora      string = "aura-2-cora-en"
	Aura2Cordelia  string = "aura-2-cordelia-en"
	Aura2Delia     string = "aura-2-delia-en"
	Aura2Draco     string = "aura-2-draco-en"
	Aura2Electra   string = "aura-2-electra-en"
	Aura2Harmonia  string = "aura-2-harmonia-en"
	Aura2Hera      string = "aura-2-hera-en"
	Aura2Hermes    string = "aura-2-hermes-en"
	Aura2Hyperion  string = "aura-2-hyperion-en"
	Aura2Iris      string = "aura-2-iris-en"
	Aura2Janus     string = "aura-2-janus-en"
	Aura2Juno      string = "aura-2-juno-en"
	Aura2Jupiter   string = "aura-2-jupiter-en"
	Aura2Luna      string = "aura-2-luna-en"
	Aura2Mars      string = "aura-2-mars-en"
	Aura2Minerva   string = "aura-2-minerva-en"
	Aura2Neptune   string = "aura-2-neptune-en"
	Aura2Odysseus  string = "aura-2-odysseus-en"
	Aura2Ophelia   string = "aura-2-ophelia-en"
	Aura2Orion     string = "aura-2-orion-en"
	Aura2Orpheus   string = "aura-2-orpheus-en"
	Aura2Pandora   string = "aura-2-pandora-en"
	Aura2Phoebe    string = "aura-2-phoebe-en"
	Aura2Pluto     string = "aura-2-pluto-en"
	Aura2Saturn    string = "aura-2-saturn-en"
	Aura2Selene    string = "aura-2-selene-en"
	Aura2Theia     string = "aura-2-theia-en"
	Aura2Vesta     string = "aura-2-vesta-en"
	Aura2Zeus      string = "aura-2-zeus-en"
	AuraAsteria    string = "aura-asteria-en"
	AuraLuna       string = "aura-luna-en"
	AuraStella     string = "aura-stella-en"
	AuraZeus       string = "aura-zeus-en"
)

// Models maps Deepgram Aura TTS model IDs to their
// configurations. Each model identifies a specific voice + language; pick
// the variant that matches the desired voice. Aura-2 models offer lower
// latency (~90ms TTFB) and higher quality at a higher per-character cost.
//
// Pricing source: https://deepgram.com/pricing.
// Fetched: 2026-07-26.
var Models = map[string]tts.AudioModel{
	Aura2Amalthea: {
		ID:             Aura2Amalthea,
		Name:           "Deepgram Aura-2 Amalthea",
		Provider:       "deepgram",
		APIModel:       "aura-2-amalthea-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Apollo: {
		ID:             Aura2Apollo,
		Name:           "Deepgram Aura-2 Apollo",
		Provider:       "deepgram",
		APIModel:       "aura-2-apollo-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Arcas: {
		ID:             Aura2Arcas,
		Name:           "Deepgram Aura-2 Arcas",
		Provider:       "deepgram",
		APIModel:       "aura-2-arcas-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Aries: {
		ID:             Aura2Aries,
		Name:           "Deepgram Aura-2 Aries",
		Provider:       "deepgram",
		APIModel:       "aura-2-aries-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Asteria: {
		ID:             Aura2Asteria,
		Name:           "Deepgram Aura-2 Asteria",
		Provider:       "deepgram",
		APIModel:       "aura-2-asteria-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Athena: {
		ID:             Aura2Athena,
		Name:           "Deepgram Aura-2 Athena",
		Provider:       "deepgram",
		APIModel:       "aura-2-athena-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Atlas: {
		ID:             Aura2Atlas,
		Name:           "Deepgram Aura-2 Atlas",
		Provider:       "deepgram",
		APIModel:       "aura-2-atlas-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Aurora: {
		ID:             Aura2Aurora,
		Name:           "Deepgram Aura-2 Aurora",
		Provider:       "deepgram",
		APIModel:       "aura-2-aurora-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Callista: {
		ID:             Aura2Callista,
		Name:           "Deepgram Aura-2 Callista",
		Provider:       "deepgram",
		APIModel:       "aura-2-callista-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Cora: {
		ID:             Aura2Cora,
		Name:           "Deepgram Aura-2 Cora",
		Provider:       "deepgram",
		APIModel:       "aura-2-cora-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Cordelia: {
		ID:             Aura2Cordelia,
		Name:           "Deepgram Aura-2 Cordelia",
		Provider:       "deepgram",
		APIModel:       "aura-2-cordelia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Delia: {
		ID:             Aura2Delia,
		Name:           "Deepgram Aura-2 Delia",
		Provider:       "deepgram",
		APIModel:       "aura-2-delia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Draco: {
		ID:             Aura2Draco,
		Name:           "Deepgram Aura-2 Draco",
		Provider:       "deepgram",
		APIModel:       "aura-2-draco-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Electra: {
		ID:             Aura2Electra,
		Name:           "Deepgram Aura-2 Electra",
		Provider:       "deepgram",
		APIModel:       "aura-2-electra-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Harmonia: {
		ID:             Aura2Harmonia,
		Name:           "Deepgram Aura-2 Harmonia",
		Provider:       "deepgram",
		APIModel:       "aura-2-harmonia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Hera: {
		ID:             Aura2Hera,
		Name:           "Deepgram Aura-2 Hera",
		Provider:       "deepgram",
		APIModel:       "aura-2-hera-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Hermes: {
		ID:             Aura2Hermes,
		Name:           "Deepgram Aura-2 Hermes",
		Provider:       "deepgram",
		APIModel:       "aura-2-hermes-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Hyperion: {
		ID:             Aura2Hyperion,
		Name:           "Deepgram Aura-2 Hyperion",
		Provider:       "deepgram",
		APIModel:       "aura-2-hyperion-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Iris: {
		ID:             Aura2Iris,
		Name:           "Deepgram Aura-2 Iris",
		Provider:       "deepgram",
		APIModel:       "aura-2-iris-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Janus: {
		ID:             Aura2Janus,
		Name:           "Deepgram Aura-2 Janus",
		Provider:       "deepgram",
		APIModel:       "aura-2-janus-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Juno: {
		ID:             Aura2Juno,
		Name:           "Deepgram Aura-2 Juno",
		Provider:       "deepgram",
		APIModel:       "aura-2-juno-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Jupiter: {
		ID:             Aura2Jupiter,
		Name:           "Deepgram Aura-2 Jupiter",
		Provider:       "deepgram",
		APIModel:       "aura-2-jupiter-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Luna: {
		ID:             Aura2Luna,
		Name:           "Deepgram Aura-2 Luna",
		Provider:       "deepgram",
		APIModel:       "aura-2-luna-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Mars: {
		ID:             Aura2Mars,
		Name:           "Deepgram Aura-2 Mars",
		Provider:       "deepgram",
		APIModel:       "aura-2-mars-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Minerva: {
		ID:             Aura2Minerva,
		Name:           "Deepgram Aura-2 Minerva",
		Provider:       "deepgram",
		APIModel:       "aura-2-minerva-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Neptune: {
		ID:             Aura2Neptune,
		Name:           "Deepgram Aura-2 Neptune",
		Provider:       "deepgram",
		APIModel:       "aura-2-neptune-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Odysseus: {
		ID:             Aura2Odysseus,
		Name:           "Deepgram Aura-2 Odysseus",
		Provider:       "deepgram",
		APIModel:       "aura-2-odysseus-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Ophelia: {
		ID:             Aura2Ophelia,
		Name:           "Deepgram Aura-2 Ophelia",
		Provider:       "deepgram",
		APIModel:       "aura-2-ophelia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Orion: {
		ID:             Aura2Orion,
		Name:           "Deepgram Aura-2 Orion",
		Provider:       "deepgram",
		APIModel:       "aura-2-orion-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Orpheus: {
		ID:             Aura2Orpheus,
		Name:           "Deepgram Aura-2 Orpheus",
		Provider:       "deepgram",
		APIModel:       "aura-2-orpheus-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Pandora: {
		ID:             Aura2Pandora,
		Name:           "Deepgram Aura-2 Pandora",
		Provider:       "deepgram",
		APIModel:       "aura-2-pandora-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Phoebe: {
		ID:             Aura2Phoebe,
		Name:           "Deepgram Aura-2 Phoebe",
		Provider:       "deepgram",
		APIModel:       "aura-2-phoebe-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Pluto: {
		ID:             Aura2Pluto,
		Name:           "Deepgram Aura-2 Pluto",
		Provider:       "deepgram",
		APIModel:       "aura-2-pluto-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Saturn: {
		ID:             Aura2Saturn,
		Name:           "Deepgram Aura-2 Saturn",
		Provider:       "deepgram",
		APIModel:       "aura-2-saturn-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Selene: {
		ID:             Aura2Selene,
		Name:           "Deepgram Aura-2 Selene",
		Provider:       "deepgram",
		APIModel:       "aura-2-selene-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Theia: {
		ID:             Aura2Theia,
		Name:           "Deepgram Aura-2 Theia",
		Provider:       "deepgram",
		APIModel:       "aura-2-theia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Vesta: {
		ID:             Aura2Vesta,
		Name:           "Deepgram Aura-2 Vesta",
		Provider:       "deepgram",
		APIModel:       "aura-2-vesta-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Zeus: {
		ID:             Aura2Zeus,
		Name:           "Deepgram Aura-2 Zeus",
		Provider:       "deepgram",
		APIModel:       "aura-2-zeus-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Thalia: {
		ID:             Aura2Thalia,
		Name:           "Deepgram Aura-2 Thalia",
		Provider:       "deepgram",
		APIModel:       "aura-2-thalia-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Andromeda: {
		ID:             Aura2Andromeda,
		Name:           "Deepgram Aura-2 Andromeda",
		Provider:       "deepgram",
		APIModel:       "aura-2-andromeda-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	Aura2Helena: {
		ID:             Aura2Helena,
		Name:           "Deepgram Aura-2 Helena",
		Provider:       "deepgram",
		APIModel:       "aura-2-helena-en",
		Currency:       "USD",
		CostPer1MChars: 30,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	AuraAsteria: {
		ID:             AuraAsteria,
		Name:           "Deepgram Aura Asteria",
		Provider:       "deepgram",
		APIModel:       "aura-asteria-en",
		Currency:       "USD",
		CostPer1MChars: 15,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	AuraLuna: {
		ID:             AuraLuna,
		Name:           "Deepgram Aura Luna",
		Provider:       "deepgram",
		APIModel:       "aura-luna-en",
		Currency:       "USD",
		CostPer1MChars: 15,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	AuraStella: {
		ID:             AuraStella,
		Name:           "Deepgram Aura Stella",
		Provider:       "deepgram",
		APIModel:       "aura-stella-en",
		Currency:       "USD",
		CostPer1MChars: 15,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
	AuraZeus: {
		ID:             AuraZeus,
		Name:           "Deepgram Aura Zeus",
		Provider:       "deepgram",
		APIModel:       "aura-zeus-en",
		Currency:       "USD",
		CostPer1MChars: 15,
		SupportedFormats: []string{
			"mp3",
			"linear16",
			"mulaw",
			"alaw",
			"opus",
			"flac",
			"aac",
		},
		DefaultFormat:     "mp3",
		SupportsStreaming: true,
	},
}
