// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-20
//
// Pricing is per image, in the currency the provider bills in. Where
// the source publishes a single rate per model, an entry's size and
// quality table is written only when the model is new to the catalog
// and is carried over from then on.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package xai

import (
	"github.com/joakimcarlsson/ai/image"
)

// Model IDs served by this catalog.
const (
	GrokImagineImage        string = "grok-imagine-image"
	GrokImagineImage20      string = "grok-imagine-image-2.0"
	GrokImagineImageQuality string = "grok-imagine-image-quality"
)

// Models maps model IDs to their configurations.
var Models = map[string]image.GenerationModel{
	GrokImagineImage: {
		ID:       GrokImagineImage,
		Name:     "Grok Imagine Image",
		Provider: "xai",
		APIModel: "grok-imagine-image",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {
				"default": 0.02,
			},
		},
		MaxPromptTokens:    1000,
		SupportedQualities: []string{"default"},
		DefaultQuality:     "default",
		SupportedAspectRatios: []string{
			"1:1",
			"16:9",
			"9:16",
			"4:3",
			"3:4",
			"3:2",
			"2:3",
			"2:1",
			"1:2",
			"19.5:9",
			"9:19.5",
			"20:9",
			"9:20",
			"auto",
		},
		DefaultAspectRatio: "1:1",
	},
	GrokImagineImage20: {
		ID:       GrokImagineImage20,
		Name:     "grok-imagine-image-2.0",
		Provider: "xai",
		APIModel: "grok-imagine-image-2.0",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.04},
		},
	},
	GrokImagineImageQuality: {
		ID:       GrokImagineImageQuality,
		Name:     "grok-imagine-image-quality",
		Provider: "xai",
		APIModel: "grok-imagine-image-quality",
		Currency: "USD",
		Pricing: map[string]map[string]float64{
			"default": {"default": 0.05},
		},
	},
}
